@startuml
title "As a Buyer, I want to get the list of items on direct sale of a given publisher" - SD
hidefootbox

skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam ArrowFontColor #3B4953

autonumber
autoactivate off

actor Buyer
participant ":GetDirectSaleItemsByPublishingCompanyUI" as UI
participant ":GetDirectSaleItemsByPublishingCompanyController" as CTL
participant ":IPublishingCompanyRepo" as PCR
participant ":IDirectSaleRepo" as DSR
participant "directSale:DirectSale" as DirectSale
participant ":IItemRepo" as IR
participant "item:Item" as Item
participant ":IEditionRepo" as ER
participant "edition:Edition" as Edition


Buyer -> UI: I want the list of items on direct %n()sale of a given publishing company
activate UI
UI -> CTL : findAllKeys()
activate CTL
CTL -> PCR : findAllKeys()
activate PCR
ref over PCR
[[sd-ref-diagrams/Find_All_Publishing_Company_Ids.puml Find all PublicationIds from persistence (via JPA)]]
end ref
PCR --> CTL : publishingCompanyIds
deactivate PCR

CTL --> UI : publishingCompanyIds
deactivate CTL
UI --> Buyer: Which publishing company?
deactivate UI
Buyer -> UI: publishingCompanyId
activate UI


UI -> CTL: getDirectSaleItemsByPublishingCompanyId(publishingCompanyId)
activate CTL

CTL -> DSR: findAll()
activate DSR
ref over DSR
[[sd-ref-diagrams/Find_All_Direct_Sales.puml Final all DirectSales from persistence (via JPA)]]
end ref
DSR --> CTL: directSales
deactivate DSR

create "listOfItemsOnDirectSaleByPublishingCompany:List<ItemId>"
CTL -->> "listOfItemsOnDirectSaleByPublishingCompany:List<ItemId>" : <<create>>

loop for directSale : directSales
CTL -> DirectSale : getItemIds()
activate DirectSale
DirectSale --> CTL : itemIds
deactivate DirectSale

loop for itemId : itemIds
CTL -> IR : ofIdentity(itemId)
activate IR
ref over IR
    [[sd-ref-diagrams/Retrieve_Item.puml Retrieve Item from persistence (via JPA)]]
end ref
IR --> CTL : reconstructedItem
deactivate IR
CTL -> Item : getEditionId()
activate Item
Item --> CTL : editionId
deactivate Item

CTL -> ER : ofIdentity(editionId)
activate ER
ref over ER
[[sd-ref-diagrams/Retrieve_Edition.puml Retrieve Edition from persistence (via JPA)]]
end ref
ER --> CTL : reconstructedEdition
deactivate ER


CTL -> Edition : isByPublishingCompanyId(publishingCompanyId)
activate Edition
Edition --> CTL : true
deactivate Edition

CTL -> "listOfItemsOnDirectSaleByPublishingCompany:List<ItemId>" : add(itemId)
activate "listOfItemsOnDirectSaleByPublishingCompany:List<ItemId>"
deactivate "listOfItemsOnDirectSaleByPublishingCompany:List<ItemId>"
end
end


CTL --> UI: listOfItemsOnDirectSaleByPublishingCompany
deactivate CTL

UI --> Buyer: Here's the list.
deactivate UI

@enduml