@startuml
title "As a Buyer, I want to get the list of items on direct sale of a given publisher" - SD
hidefootbox

skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam ArrowFontColor #3B4953

autonumber
autoactivate off

actor Buyer
participant ":GetDirectSaleItemsByPublishingCompanyUI" as UI
participant ":GetDirectSaleItemsByPublishingCompanyController" as CTL
participant ":IPublishingCompanyRepo" as PCR
participant ":IDirectSaleRepo" as DSR
participant "directSale:DirectSale" as DirectSale
participant ":IItemRepo" as IR
participant "item:Item" as Item
participant ":IEditionRepo" as ER
participant "edition:Edition" as Edition


Buyer -> UI: I want the list of items \non direct sale of a given publishing company
activate UI
UI -> CTL : findAllKeys()
activate CTL
CTL -> PCR : findAllKeys()
activate PCR

PCR --> CTL : publishingCompanyIds
deactivate PCR

CTL --> UI : publishingCompanyIds
deactivate CTL
UI --> Buyer: Select publishingCompanyId
deactivate UI
Buyer -> UI: publishingCompanyId
activate UI


UI -> CTL: getDirectSaleItemsByPublishingCompanyId(publishingCompanyId)
activate CTL

CTL -> DSR: findAll()
activate DSR

DSR --> CTL: directSales
deactivate DSR

create "listOfItemsOnDirectSaleByPublishingCompany:List<ItemId>"
CTL -->> "listOfItemsOnDirectSaleByPublishingCompany:List<ItemId>" : <<Create>>

loop for directSale : directSales
CTL -> DirectSale : getItemIds()
activate DirectSale
DirectSale --> CTL : itemIds
deactivate DirectSale

loop for itemId : itemIds
CTL -> IR : ofIdentity(itemId)
activate IR
IR --> CTL : item
deactivate IR
CTL -> Item : getEditionId()
activate Item
Item --> CTL : editionId
deactivate Item

CTL -> ER : ofIdentity(editionId)
activate ER
ER --> CTL : edition
deactivate ER


CTL -> Edition : hasPublishingCompanyId = isByPublishingCompanyId(publishingCompanyId)

opt hasPublishingCompanyId
CTL -> "listOfItemsOnDirectSaleByPublishingCompany:List<ItemId>" : add(itemId)
activate "listOfItemsOnDirectSaleByPublishingCompany:List<ItemId>"
"listOfItemsOnDirectSaleByPublishingCompany:List<ItemId>" --> CTL : true
deactivate "listOfItemsOnDirectSaleByPublishingCompany:List<ItemId>"
end
end
end


CTL --> UI: listOfItemsOnDirectSaleByPublishingCompany
deactivate CTL

UI --> Buyer: Here's the list! Done!
deactivate UI

@enduml