@startuml
title US024 - "As a Buyer, I want to get the list of items on auction of a given publication" - Level 1 SD
hidefootbox

skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam ArrowFontColor #3B4953

autonumber
autoactivate off

actor Buyer
participant ":GetAuctionItemsByPublicationUI" as UI
participant ":GetAuctionItemsByPublicationController" as CTL
participant "_ar:AuctionRepo" as AR

Buyer -> UI: I want the list of items on auction of a given publication
activate UI
UI --> Buyer: What is the publication's name?
deactivate UI
Buyer -> UI: publicationName
activate UI


UI -> CTL: getAuctionItemsByPublication(publicationName)
activate CTL

CTL -> AR: getAuctionItemsByPublication(publicationName)
activate AR

AR --> CTL: copyOfListOfAuctionItemsByPublication
deactivate AR

CTL --> UI: copyOfListOfAuctionItemsByPublication
deactivate CTL

UI --> Buyer: Here's the list! done!
deactivate UI

@enduml