@startuml
title "As a user, I want to create my library" - Level 2 SD
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---
actor User
participant ":CreateLibraryUI" as UI
participant ":CreateLibraryController" as CTL
participant ":LibraryFactory" as LF
participant ":MemLibraryRepo" as LR

User -> UI: I want to create my library
activate UI

UI -> CTL: createLibrary(userId)
activate CTL

CTL -> LF: createLibrary(userId)
activate LF
create "myLibrary:Library"
LF -->> "myLibrary:Library": <<create>>
LF --> CTL: myLibrary
deactivate LF

CTL -> LR : hasId = containsOfIdentity(myLibrary.identity())

    opt !hasId
    CTL -> LR: save(myLibrary)

    end

CTL --> UI: true
deactivate CTL

UI --> User: done!
deactivate UI

@enduml