@startuml
'==== Title ====
title US017 - "As a User, I want to create a private list of my publications, give it a name and set a genre" - CD
top to bottom direction

'==== basic style ====
skinparam monochrome false
skinparam shadowing true
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ArrowColor #57595BAA
skinparam classAttributeIconSize 0

'==== entities ====
interface IListOfPublicationsRepo {
+ addListOfPublications(user : User, name : String, genre : Genre) : ListOfPublications
+ findListsByUser(user : User) : List<ListOfPublications>
}

class MemoListOfPublicationsRepo {
- _listsOfPublications : List<ListOfPublications>
- _genreRepo : GenreRepo
+ addListOfPublications(user : User, name : String, genre : Genre) : ListOfPublications
}

class CreatePrivateListOfPublicationsController {
	-_listOfListOfPublicationsRepo : IListOfPublicationsRepo
	-_genreRepo : GenreRepo
	+ getOfficialGenres() : List<Genre>
	+ createListOfPublications(user : User, name : String, genre : Genre) : ListOfPublications
}

Class ListOfPublications {
-_user : User
-_name : String
-_genre : Genre
-_isPrivate : boolean
}

'==== connections ====
MemoListOfPublicationsRepo "1" --> "*" ListOfPublications: instantiates through
IListOfPublicationsRepo <|.. MemoListOfPublicationsRepo
CreatePrivateListOfPublicationsController  "1" ..> "1" IListOfPublicationsRepo: calls
CreatePrivateListOfPublicationsUI "1" ..> "1" CreatePrivateListOfPublicationsController: invokes

@enduml
