@startuml
'==== basic style ====
hide stereotype
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox

autonumber

title "As a User, I want to get the list (title, author, type and ISBN/SSN) \nof publications in my library - SD"

' --- Actor and participants ---

actor User
participant ":Client" as client
participant ":Server" as server
database "DB" as DB

User -> client : access to "My Library" CONFIRMAR SSD
activate client
client -> server : GET /my-library
activate server

server -> DB : select
activate DB
DB --> server : data
deactivate DB

server --> client : 200
deactivate server
client --> User : Items of your library
deactivate client

User -> client : View Item
activate client
client -> server : GET /my-library/{ItemId}
activate server

server -> DB : select
activate DB
DB --> server : data
deactivate DB

server --> client : 200
deactivate server
client --> User : here is the details!
deactivate client

@enduml