@startuml
'https://plantuml.com/class-diagram
title US004 - "Register a new Appraisal Entity, including the genres and publication types it can appraise" - CD


'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0

class RegisterNewAppraisalEntityUI {
}

class RegisterNewAppraisalEntityController {
- _appraisalEntityRepo : MemoAppraisalEntityRepo
- _genreRepo : GenreRepo
- _publicationTypeRepo : PublicationTypeRepo
+ registerNewAppraisalEntity(name : Name, publicationTypes : List<PublicationType>, genres : List<Genre>) : AppraisalEntity
+ getPublicationTypes() : List<PublicationType>
+ getGenres() : List<Genre>
}

interface IAppraisalEntityRepo {
+ registerNewAppraisalEntity(name : Name, publicationTypes: List<PublicationType>, genres : List<Genre>) : AppraisalEntity
}

class MemoAppraisalEntityRepo {
-_appraisalEntity : List<AppraisalEntity>
- appraisalEntityExists(name:Name) : boolean
}

class AppraisalEntityFactory {
+ createAppraisalEntity(name : Name, publicationTypes: List<PublicationType>, genres : List<Genre>) : AppraisalEntity
}
interface IGenreRepo {
- _genre : List<Genre>
+ getAll() : List<Genre>
}

interface IPublicationTypeRepo {
-_publicationType : List<PublicationType>
+ getAll() : List<PublicationType>
}

class AppraisalEntity{
- _name : Name
- _publicationTypes : List<PublicationType>
- _genres : List<Genre>
+ AppraisalEntity(name : Name, publicationTypes : List<PublicationType>, genres : List<Genre>)
}

RegisterNewAppraisalEntityUI "1" ..> "1" RegisterNewAppraisalEntityController : uses
RegisterNewAppraisalEntityController "1" ..> "1" IGenreRepo : accesses
RegisterNewAppraisalEntityController "1" ..> "1" IPublicationTypeRepo : accesses
RegisterNewAppraisalEntityController "1" ..> "1" IAppraisalEntityRepo : uses
IAppraisalEntityRepo "1" <|.. "1" MemoAppraisalEntityRepo
MemoAppraisalEntityRepo "1" --> "1" AppraisalEntityFactory : uses
AppraisalEntityFactory "1" --> "*" AppraisalEntity : creates

@enduml