@startuml
'==== basic style ====

'hides unwanted text
hide stereotype

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox

'undefined objects
skinparam object {
  BackgroundColor<<highlight>> 91C6BCAA
  BorderColor<<highlight>> 4B9DA9AA
  FontColor<<highlight>> 547792AA
}
skinparam shadowing<<highlight>> false

autonumber

title US012 - "As a User, I want to get the list (title, author, type and ISBN/ISSN) of publications in my library" - SD


' --- Actor and participants ---'

actor User
participant ":ListOfPublicationsInMyLibraryUI" as UI
participant ":ListOfPublicationsInMyLibraryController" as Ctl
participant ":ILibraryRepo" as LibRepo
participant "library:Library" as Lib



User -> UI: Display List of my Publications
activate UI

UI -> Ctl: getListOfPublicationDetails(userId)
activate Ctl

Ctl -> LibRepo: findByUser(userId)
activate LibRepo
LibRepo --> Ctl: library
deactivate LibRepo

Ctl -> Lib: getPublicationDetails()

create "listWithDetails: List<PublicationsDetails>" as listOfPubs
activate Lib
Lib -->> listOfPubs: <<Create>>



loop for each itemId in library

create "pDetails:PublicationDetails" as list
    Lib -->> list: <<Create>>

    Lib -> listOfPubs: add(pDetails)
activate listOfPubs
listOfPubs --> Lib :true
end

deactivate listOfPubs
Lib --> Ctl: listWithDetails
deactivate Lib

Ctl --> UI: listWithDetails
deactivate Ctl

UI --> User: Publications list displayed\n with details
deactivate UI



@enduml