@startuml
'==== basic style ====

'hides unwanted text
hide stereotype

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox

'undefined objects
skinparam object {
  BackgroundColor<<highlight>> 91C6BCAA
  BorderColor<<highlight>> 4B9DA9AA
  FontColor<<highlight>> 547792AA
}
skinparam shadowing<<highlight>> false

autonumber

title US012 - "As a User, I want to get the list (title, author, type and ISBN/ISSN) of publications in my library" - SD


' --- Actor and participants ---'

actor User
participant ":ListOfItemsInMyLibraryUI" as UI
participant ":ListOfItemsInMyLibraryController" as Ctl
participant ":ILibraryRepo" as LibRepo
participant ":IItemRepo" as ItRepo
participant ":IEditionRepo" as EdRepo
participant ":IPublicationRepo" as PubRepo
participant ":IPublicationTypeRepo" as PTRepo
participant ":IAuthorRepo" as AutRepo
participant ":ItemDetailsMapper" as Mapper


User -> UI: Display list of information\n of Items in my library
activate UI

UI -> Ctl: getListOfItemInfoInMyLibrary(userId)
activate Ctl

Ctl -> LibRepo: getItemsInLibraryByUserId(userId)
activate LibRepo
LibRepo --> Ctl: listOfItemIds
deactivate LibRepo
create "listOfItemDetailsDTOs: List<ItemDetailsDTO>" as listOfDTO
Ctl -->> listOfDTO: <<create>>

loop for each itemId in listOfItemIds

Ctl -> ItRepo: ofIdentity(itemId)
activate ItRepo
ItRepo --> Ctl : item
deactivate ItRepo
Ctl -> EdRepo : ofIdentity(item.get_editionId())
activate EdRepo
EdRepo --> Ctl : edition
deactivate EdRepo
Ctl -> PubRepo : ofIdentity(edition.getPublicationId())
activate PubRepo
PubRepo --> Ctl : publication
deactivate PubRepo
Ctl -> PTRepo : ofIdentity(edition.getPublicationTypeId())
activate PTRepo
PTRepo --> Ctl : publicationType
deactivate PTRepo
Ctl -> AutRepo : ofIdentity(publication.getAuthorId())
activate AutRepo
AutRepo --> Ctl : author
deactivate AutRepo

Ctl -> Mapper : toDTO(edition, publication, publicationType, author)
activate Mapper
create "itemDetailsDTO:ItemDetailsDTO" as DTO
Mapper -->> DTO : <<create>>
Mapper --> Ctl : itemDetailsDTO
deactivate Mapper

Ctl -> listOfDTO : add(itemDetailsDTO)

end

Ctl --> UI: listOfItemDetailsDTOs
deactivate Ctl

UI --> User: Items details displayed!
deactivate UI



@enduml