
@startuml
title **"As an Administrator, I want to register a new country in the system"**  SD
hide footbox

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

actor "Admin" as Administrator
participant ":RegisterNewCountryUI" as UI
participant ":RegisterCountryController" as Ctl
participant ":CountryFactory" as Factory
participant ":ICountryRepo" as IR

Administrator -> "UI": I want to register a country in the system.
activate "UI"
"UI" --> Administrator: What is the country's name?
Administrator -> "UI": country name.
"UI" -> "Ctl": registerCountry(countryName)
activate "Ctl"


Ctl -> "Factory" : createCountry(countryName)

activate "Factory"

create "newCountry:Country"
Factory -->> "newCountry:Country" : <<create>>(countryName)
Factory --> Ctl: newCountry
deactivate "Factory"

ref over Ctl
[[sd-ref-diagrams/Verify_Country.puml Verify the existence of newCountry in persistence]]
end ref

Ctl -> IR : save(newCountry)

ref over IR
[[sd-ref-diagrams/Save_Country.puml Save newCountry and return saved domain object]]
end ref
activate IR
IR --> Ctl : country
deactivate IR
Ctl --> UI : country
deactivate Ctl
UI --> Administrator : Registered successfully!
deactivate UI

@enduml