@startuml
title "As a Buyer, I want to get the list of items on auction of a given author" - SD
hidefootbox

skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam ArrowFontColor #3B4953

autonumber
autoactivate off

actor Buyer
participant ":GetItemsOnAuctionOfA\nGivenAuthorUI" as UI
participant ":GetItemsOnAuctionOfA\nGivenAuthorController" as CTL
participant "publication:Publication" as Publication


Buyer -> UI: I want the list of items \non auction of a given author
activate UI
UI -> CTL : findAllKeys()
activate CTL
ref over CTL
[[sd-ref-diagrams/Get_Author_Ids.puml Get All Author Ids]]
end ref



CTL --> UI : authorIds
deactivate CTL
UI --> Buyer: Select authorId
deactivate UI
Buyer -> UI: authorId
activate UI


UI -> CTL: getAuctionItems\nByAuthorId(authorId)
activate CTL

ref over CTL
[[sd-ref-diagrams/Get_Auctions.puml Get Auctions]]
end ref

create "listOfItemsOnAuctionByAuthor:List<ItemId>"
CTL -->> "listOfItemsOnAuctionByAuthor:List<ItemId>" : <<Create>>

loop for auction : auctions
ref over CTL
[[sd-ref-diagrams/Get_Items_Ids_Auction.puml Get Items Ids on Auction]]
end ref

loop for itemId : itemIds
ref over CTL
[[sd-ref-diagrams/Get_Items.puml Get Items]]
end ref

ref over CTL
[[sd-ref-diagrams/Get_Edition_Id_Item.puml Get Edition Ids on Item]]
end ref

ref over CTL
[[sd-ref-diagrams/Get_Edition.puml Get Edition]]
end ref

ref over CTL
[[sd-ref-diagrams/Get_Publication_Id.puml Get Publication Id]]
end ref

ref over CTL
[[sd-ref-diagrams/Get_Publication.puml Get Publication]]
end ref

CTL -> Publication : hasAuthorId = isByAuthorId(authorId)

opt hasAuthorId
CTL -> "listOfItemsOnAuctionByAuthor:List<ItemId>" : add(itemId)
activate "listOfItemsOnAuctionByAuthor:List<ItemId>"
"listOfItemsOnAuctionByAuthor:List<ItemId>" --> CTL : true
deactivate "listOfItemsOnAuctionByAuthor:List<ItemId>"
end
end
end


CTL --> UI: listOfItemsOnAuctionByAuthor
deactivate CTL

UI --> Buyer: Here's the list! Done!
deactivate UI

@enduml
