@startuml
title "As a Buyer, I want to get the list of items on auction \nof a given author" - Level 3 SD
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---
actor Buyer
participant ":GetItemsOnAuction\nOfAGivenAuthorUI" as UI
participant ":GetItemsOnAuction\nOfAGivenAuthorCtl" as CTL
participant "mAR:MemoAuctionRepo" as DSR
participant "auction:Auction" as DS
participant "item:Item" as IT
participant "publication:Publication" as PUB



' --- Dialog ---
Buyer -> UI: I want a list of Items on auction of a given author
activate UI
UI --> Buyer: What is the author's name?
deactivate UI
Buyer -> UI: authorID
activate UI
UI -> CTL: getAuctionItemsId\nByAuthorId(authorID)
activate CTL
CTL -> DSR: getAuctionItemsId\nByAuthorId(authorID)
activate DSR

create "listOfItemsIdOnAuctionByAuthorId: List<ItemId>" as List
DSR -->> List: <<create>>

loop for each auction in mAR
    DSR -> DS: isByAuthorId(authorId)
    activate DS
    DS -> IT: isByAuthorId(authorId)
    activate IT
    IT -> PUB: isByAuthorId(authorId)
    activate PUB
    PUB --> IT: true
    deactivate PUB
    IT --> DS: true
    deactivate IT
    DS --> DSR: true
    deactivate DS
    DSR -> List: add(auction.getItemId())
    activate List
    List --> DSR: true
    deactivate List
end



create "copyOfListOfItemsIdOnAuctionByAuthorId: List<ItemId>" as Copy
DSR -> Copy: List.copyOf(listOfItemsIdOnAuctionByAuthorId)

'participant "author:Author" as AUT

DSR --> CTL: copyOf\nListOfItemsIdOnAuctionByAuthorId
deactivate DSR
CTL --> UI: copyOf\nListOfItemsIdOnAuctionByAuthorId
deactivate CTL
UI --> Buyer: Here's the list!
deactivate UI

@enduml