@startuml
'==== Title ====
title "As a User, I want to use a Web UI to put for sale in an auction a publication in my library" - SD

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox
autonumber

participant ":AuctionRestController" as REST
participant ":AuctionLinkProvider" as Link
participant ":AuctionService" as Service
participant ":AuctionFactory" as Factory
participant ":IAuctionRepo" as auctionRepo
participant ":IItemRepo" as itemRepo
participant "item:Item" as Item
participant ":Auction\nResponseDTOMapper" as Mapper
participant "Database" as DB


loop for each itemIdString
    create "itemId:ItemId" as itemId
    REST -->> itemId : create(itemIdString)
end

create "currency:Currency" as currency
REST -->> currency : currency = valueOf(priceCurrency)

create "startingPrice:Price" as startingPrice
REST -->> startingPrice : startingPrice = create(value, currency)

create "reservePrice:Price" as reservePrice
REST -->> reservePrice : reservePrice = create(value, currency)

opt outrightPrice != null
    create "outrightPrice:Price" as outrightPrice
    REST -->> outrightPrice : outrightPrice = create(value, currency)
end

create "startDate:ZonedDateTime" as startDate
REST -->> startDate : startDate = atZone(UTC)

create "endDate:ZonedDateTime" as endDate
REST -->> endDate : endDate = atZone(UTC)

create "email:Email" as email
REST -->> email : create(emailString)

create "seller:UserId" as seller
REST -->> seller : create(email)

REST -> Service : putItemOnAuction (itemIds, startingPrice, \nreservePrice, outrightPrice, startDate, endDate, seller)
activate Service

loop for each item - validation
    Service -> itemRepo : ofIdentity(itemId)
    activate itemRepo
    itemRepo -> DB : ofIdentity(itemId)
    activate DB
    DB --> itemRepo : item
    deactivate DB
    itemRepo --> Service : item
    deactivate itemRepo

    Service -> Item : getSaleStatus()
    activate Item
    Item --> Service : saleStatus
    deactivate Item
end

Service -> Factory : createAuction (\n  itemsId, startingPrice, reservePrice,\n  outrightPrice, startDate, endDate, user)
activate Factory
Factory --> Service : auction
deactivate Factory

Service -> auctionRepo : containsOfIdentity(auctionId)
activate auctionRepo
auctionRepo -> DB : containsOfIdentity(auctionId)
activate DB
DB --> auctionRepo : false
deactivate DB
auctionRepo --> Service : false
deactivate auctionRepo

Service -> auctionRepo : save(auction)
activate auctionRepo
auctionRepo -> DB : save(auction)
activate DB
DB --> auctionRepo : auctionSaved
deactivate DB
auctionRepo --> Service : auctionSaved
deactivate auctionRepo

loop for each item - update
    Service -> itemRepo : ofIdentity(itemId)
    activate itemRepo
    itemRepo -> DB : ofIdentity(itemId)
    activate DB
    DB --> itemRepo : item
    deactivate DB
    itemRepo --> Service : item
    deactivate itemRepo

    Service -> Item : markAsAuction()
    activate Item
    deactivate Item

    Service -> itemRepo : save(item)
    activate itemRepo
    itemRepo -> DB : save(item)
    activate DB
    DB --> itemRepo : itemSaved
    deactivate DB
    itemRepo --> Service : itemSaved
    deactivate itemRepo
end

Service --> REST : Auction
deactivate Service

REST -> Mapper : toDTO(auction)
activate Mapper
Mapper --> REST : AuctionResponseDTO
deactivate Mapper

REST -> REST : dto.add(selfRel)
deactivate REST

ref over REST
[[../Process_View_Level_3_SD.puml Return to main diagram]]
end ref

@enduml