@startuml
title US015 -"As a User, I want to put for sale a publication %n() in my library in a direct sale" - SD
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---
actor User
participant "UI:PublicationForDirectSaleUI" as UI
participant "Ctl15:PublicationForDirectSaleCTL" as Ctl
participant "_lr:LibraryRepo" as LibraryRepo
participant "_pr:PublicationRepo" as PublicationRepo
participant "_ir:ItemRepo" as ItemRepo
participant "_dsr:DirectSaleRepo" as DirectSaleRepo

' --- System dialog ---
User -> UI: I want to put for direct sale a publication in my library.
activate "UI"

' --- Get the list of publications in the User's library ---
UI -> Ctl: getPublicationsList(userID)
activate "Ctl"
Ctl -> LibraryRepo: getPublicationsList(userID)
activate "LibraryRepo"
LibraryRepo --> Ctl: publicationsList
deactivate "LibraryRepo"
Ctl --> UI: publicationsList
' --- Done! ---

UI --> User: What publication?
User -> UI: publication(publicationID, saleType, condition)
UI --> User: Please fill the Direct Sale form.
User -> UI: DirectSale(price, timeLimit)

' --- Get the selected publication ---
UI -> Ctl: getPublication(publicationID)
Ctl -> PublicationRepo: getPublication(publicationID)
activate "PublicationRepo"
PublicationRepo --> Ctl: p1:Publication
deactivate "PublicationRepo"
' --- Done! ---

' ---  Instance the physical copy of the selected publication ---
Ctl -> ItemRepo: createItem(p1:Publication, saleType, condition)
activate "ItemRepo"
create "item:Item" as itemInstance
ItemRepo -> itemInstance: createItem(p1:Publication, saleType, condition)
ItemRepo --> Ctl: item
deactivate "ItemRepo"

' --- Create a direct sale ---
Ctl -> DirectSaleRepo: createDirectSale(item:Item, price, timeLimit)
activate DirectSaleRepo
create "directSale:DirectSale" as directSaleInstance
DirectSaleRepo -> directSaleInstance: createDirectSale(item:Item, price, timeLimit)

' --- Details on relationship between Item and DirectSale ---
note over directSaleInstance
A directSale can only exist
in association with an item.
end note

' --- Return to user ---
DirectSaleRepo --> Ctl: directSale
deactivate "DirectSaleRepo"
Ctl --> UI: directSale
deactivate "Ctl"
UI --> User: Your item was successfully put up for sale!
deactivate "UI"

@enduml