@startuml
title US015 - "As a User, I want to put for sale a publication %n() in my library in a direct sale" - SSD
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---
actor User
participant ":MiteLovers" as System

' --- System dialog ---
User -> System: I want to put for Direct Sale a publication in my library!
activate "System"
System --> User: What publication?
deactivate "System"
User -> System: publicationID
activate "System"
System --> User: Please select the item's condition.
deactivate "System"
User -> System: condition
activate "System"
System --> User: Please fill the Direct Sale form.
deactivate "System"
User ->System: DirectSale(price, timeLimit)
activate "System"
System --> User: Done!
deactivate "System"

@enduml
