@startuml
title US015 -"As a User, I want to put for sale a publication %n() in my library in a direct sale" - SD
hide footbox

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

actor User
participant ":PublicationInLibraryForDirectSaleUI" as UI
participant ":PublicationInLibraryForDirectSaleController" as Ctl
participant ":LibraryRepo" as LibraryRepo
participant "userLibrary:Library" as userLibrary
participant ":DirectSaleRepo" as DirectSaleRepo
participant ":DirectSaleFactory" as DirectSaleFactory
participant "directSale:DirectSale" as directSale

User -> UI: I want to put for direct sale a publication in my library
activate UI

UI -> Ctl: getItemsInLibrary(user)
activate Ctl
Ctl -> LibraryRepo: findLibraryByUser(user)
activate LibraryRepo
LibraryRepo --> Ctl: userLibrary
deactivate LibraryRepo

Ctl -> userLibrary: getItemsInLibrary()
activate userLibrary
userLibrary --> Ctl: itemsList
deactivate userLibrary

Ctl --> UI: itemsList
deactivate Ctl
UI --> User: Which item would you like to sell?
deactivate UI

User -> UI: item.
activate UI

UI --> User: What is the price and time limit for this sale?
User -> UI: price, time limit
deactivate UI

UI -> Ctl: addItemForDirectSale(item, price, timeLimit)
activate Ctl

Ctl -> DirectSaleRepo: addDirectSale(item, price, timeLimit)
activate DirectSaleRepo

DirectSaleRepo -> DirectSaleFactory: createDirectSale(item, price, timeLimit)
activate DirectSaleFactory
create directSale
DirectSaleFactory -> directSale: create(item, price, timeLimit)
DirectSaleFactory --> DirectSaleRepo: directSale
deactivate DirectSaleFactory

DirectSaleRepo -> DirectSaleRepo: add(directSale)
DirectSaleRepo --> Ctl: directSale
deactivate DirectSaleRepo

Ctl --> UI: directSale
deactivate Ctl
UI --> User: Your item was successfully put up for sale!
deactivate UI

@enduml