@startuml
title US009 - "As a user, I want to create my library" - Level 2 SD
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---
actor User
participant ":CreateLibraryUI" as UI
participant ":CreateLibraryController" as CTL
participant ":LibraryRepo" as LR
participant ":LibraryFactory" as LF

' --- UI interaction ---
User -> UI: I want to create my library
activate UI


' --- Use case execution ---
UI -> CTL: createMyLibrary(user)
activate CTL

CTL -> LR: createMyLibrary(user)
activate LR



    opt myLibraryExists(user) == false
        LR -> LF: createMyLibrary(user)
        activate LF
        create "myLibrary:Library"
        LF -> "myLibrary:Library": create(user)
        LF --> LR: myLibrary
        deactivate LF

        LR -> LR: add(myLibrary)


    end

LR --> CTL: myLibrary
deactivate LR

'activate "myLibrary:Library"
'"myLibrary:Library" --> "_lr:LibraryRepo": myLibrary
'deactivate "myLibrary:Library"

CTL --> UI: myLibrary
deactivate CTL

UI --> User: done!
deactivate UI

@enduml