@startuml
title US009 - "As a user, I want to create my library" - Level 1 SD
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---
actor User
participant ":CreateLibraryUI" as UI
participant ":CreateLibraryController" as CTL
participant ":LibraryRepo" as LR

' --- UI interaction ---
User -> UI: I want to create my library
activate UI


' --- Use case execution ---
UI -> CTL: createMyLibrary(user)
activate CTL
CTL -> LR: createMyLibrary(user)
activate LR

    opt myLibraryExists(user) == false
        create "myLibrary:Library"
        LR -> "myLibrary:Library": create(user)
        LR -> LR: add(myLibrary)
    end


'activate "myLibrary:Library"
'"myLibrary:Library" --> "_lr:LibraryRepo": myLibrary
'deactivate "myLibrary:Library"
LR --> CTL: myLibrary
deactivate LR
CTL --> UI: myLibrary
deactivate CTL
UI --> User: done!
deactivate UI

@enduml