@startuml

title "US003 - As an Administrator, I want to add a publication genre to the official \ngenre list, so that new publications can be of this genre" - SD

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ArrowColor #57595BAA
skinparam ActivationBackgroundColor WhiteSmoke
hidefootbox

autonumber

actor Administrator
participant "U1:UIAddGenre" as UI
participant "Ctl1:AddGenreController" as Ctl
participant "_gr:GenreRepo" as gr
participant "_listgr:List <Genre>" as list

Administrator -> UI: I want to add a publication genre
activate UI
UI --> Administrator: What is the genre name?
deactivate UI
Administrator -> UI: genreName
activate UI

UI -> Ctl: addGenre(genreName)
activate Ctl
Ctl -> gr: addGenre(genreName)
activate gr

opt existsGenre(genreName) == false
        create "genre:Genre"
        gr -> "genre:Genre": create()
        gr -> list: add()
        activate list
    end

list --> gr: true
deactivate list
gr --> Ctl: genre
deactivate gr

Ctl --> UI: genre
deactivate Ctl

UI --> Administrator: genre added successfully to the \nofficial genre list!
deactivate UI

@enduml