@startuml

title "US003 - As an Administrator, I want to add a publication genre to the official \ngenre list, so that new publications can be of this genre" - SD

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ArrowColor #57595BAA
skinparam ActivationBackgroundColor WhiteSmoke
hide footbox

autonumber

actor Administrator
participant ":AddGenreUI" as UI
participant ":AddGenreController" as Ctl
participant "_genreRepo:GenreRepo" as gr
participant "_genreFactory:GenreFactory" as gf
participant "_genresList:List <Genre>" as list

Administrator -> UI: I want to add a publication genre
activate UI
UI --> Administrator: What is the genre name?
deactivate UI
Administrator -> UI: genreName
activate UI

UI -> Ctl: addGenre(genreName)
activate Ctl
Ctl -> gr: addGenre(genreName)
activate gr

opt !genreExists(genreName)
        gr -> gf : createGenre(genreName)
        activate gf
        create "genre:Genre"
        gf -> "genre:Genre": create(genreName)
        gf --> gr : genre
        gr -> list: add(genre)
        activate list
        list --> gr: true
        deactivate list
    end


gr --> Ctl: genre
deactivate gr

Ctl --> UI: genre
deactivate Ctl

UI --> Administrator: genre added successfully to the \nofficial genre list!
deactivate UI

@enduml