@startuml
title US014 - "As a User, I want to get the list of official publication types" %n() SD

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox

actor User

participant ":UIPublicationTypeList" as UI
participant ":GetPublicationType%n()ListController" as CTRL
participant ":IPublication%n()TypeRepo" as PTR

User -> UI : 1. I want the list of %n()all publication types.
Activate UI
UI -> CTRL : 2. getListOf%n()PublicationTypes()
Activate CTRL
CTRL -> PTR : 3. findAll()
Activate PTR

PTR --> CTRL : 4. Iterable%n()<PublicationType>
Deactivate PTR
CTRL --> UI : 5. Iterable%n()<PublicationType>
Deactivate CTRL
UI --> User : 6. Here is the list of %n()official publication %n()types.
Deactivate UI

@enduml
