@startuml
title OPTIONS for user on /auctions/{auctionId} %n()ref SD

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox
autonumber

participant ":AuctionRestController" as REST
participant ":UserService" as userService
participant ":IUserRepo" as userRepo
participant ":AuctionLinkProvider" as Link
participant "Database" as DB


REST -> userService : getUserByEmail(emailString)
activate REST
activate userService

create "email:Email" as email
userService -->> email : createEmail(emailString)

create "userId:UserId" as userId
userService -->> userId : createUserId(email)

userService -> userRepo : ofIdentity(userId)
activate userRepo
userRepo -> DB : ofIdentity(userId)
activate DB
DB --> userRepo : user
deactivate
userRepo --> userService : user
deactivate userRepo

userService --> REST : user
deactivate userService

create "bidOptions:RepresentationModel<?>" as bidOptions
REST -->> bidOptions : createRepresentationModel()

REST -> Link : getLinks(user, auctionId)
activate Link
Link --> REST : _links = List<Link>
deactivate Link

loop for each link in _links
    REST -> bidOptions : add(link)
    activate bidOptions
    deactivate bidOptions
end

deactivate REST

ref over REST
Process_View_Level_3_SD.puml]
end ref

@enduml