@startuml
title POST (place bid on auction) %n()ref SD

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox
autonumber

participant "Router" as router
participant ":AuctionRestController" as REST
participant ":AuctionLinkProvider" as Link
participant ":AuctionService" as Service
participant ":IAuctionRepo" as auctionRepo
participant "auction%n():Auction" as Auction
participant ":BidFactory" as BidFactory
participant ":Bid\nResponseDTOMapper" as Mapper
participant "Database" as DB

' ===== POST /auctions/{auctionId}/bids =====

[o-> router : POST {bids href} + %n(){placeBidRequestDTO}
activate router
router -> REST : placeBid(auctionIdString, %n()userIdFromHeader, placeBidRequestDTO)
create "email:Email" as email
activate REST

REST -->> email : createEmail(userIdFromHeader)

create "userId:UserId" as userId
REST -->> userId : createUserId(email)

create "currency:Currency" as currency
REST -->> currency : valueOf(placeBidRequestDTO.getCurrency())

create "offerPrice:Price" as offerPrice
REST -->> offerPrice : createPrice(placeBidRequestDTO.getOfferPrice, currency)

REST -> Service : placeBid(auctionIdString, userId, offerPrice)
activate Service

create "auctionId:AuctionId" as auctionId
Service -->> auctionId : createAuctionId(auctionIdString)

Service -> auctionRepo : ofIdentity(auctionId)
activate auctionRepo
auctionRepo ->o] : FETCH
auctionRepo <--o] : DATA
deactivate DB
auctionRepo --> Service : auction
deactivate auctionRepo


Service -> Auction : placeBid(userId, offerPrice)
activate Auction

Auction -> BidFactory : createBid%n()(userId, offerPrice)
activate BidFactory
create "bid:Bid" as bid
BidFactory -->> bid : <<create>>
BidFactory --> Auction : bid
deactivate BidFactory
Auction --> Service : bid
deactivate Auction

Service -> auctionRepo : save(auction)
activate auctionRepo
auctionRepo ->o] : SAVE
auctionRepo <--o] : OK
deactivate DB

deactivate auctionRepo
create "bidPlacementResult:BidPlacementResult" as Result
Service -->> Result : createBidPlacementResult(auction, bid)
Service --> REST : bidPlacementResult
deactivate Service

note right of REST
  BidPlacementResult is a record containing:
  - auction (updated aggregate)
  - bid (newly created bid)
end note

REST -> Result : getAuction()
activate Result
Result --> REST : auction
deactivate Result
REST -> Result : getBid()
activate Result
Result --> REST : bid
deactivate Result

REST -> Mapper : toDTO(auction, bid)
activate Mapper
Mapper --> REST : bidResponseDTO
deactivate Mapper

deactivate Service

REST -> Link : addLinksForCreatedBid(bidResponseDTO)
activate Link
deactivate Link

note right of Link
  Adds HATEOAS links to the same DTO instance
end note

create "response:ResponseEntity<Object>" as response
REST -->> response : new ResponseEntity<>(bidResponseDTO, 201 Created)
REST --> router : response
deactivate REST

[o<-- router : 201 Created + bidResponseDTO %n() + auction link + bids link
deactivate REST

ref over router
[[../Process_View_Level_3_SD.puml Back to main diagram]]
end ref

@enduml