@startuml
title US005 - As an Administrator, I want to register an Author in the system \n so that publications of that author can be added.
hidefootbox

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

actor Administrator


Administrator -> ":CreateAuthorUI": I want to register an Author
":CreateAuthorUI" --> Administrator: What is the author's name?

Administrator -> ":CreateAuthorUI": authorName
activate ":CreateAuthorUI"

":CreateAuthorUI" -> ":CreateAuthorController": createAuthor(authorName)

activate ":CreateAuthorController"
":CreateAuthorController"-> ":MemoAuthorRepo": createAuthor(authorName)

activate ":MemoAuthorRepo"
opt existsByName(authorName) == false
":MemoAuthorRepo" -> ":AuthorFactory": createAuthor(authorName)

activate ":AuthorFactory"
create "myAuthor:Author"
":AuthorFactory" -->> "myAuthor:Author": <<create>>
":AuthorFactory" --> ":MemoAuthorRepo": myAuthor
deactivate ":AuthorFactory"
":MemoAuthorRepo" -> ":MemoAuthorRepo": add(myAuthor)
end
":MemoAuthorRepo" --> ":CreateAuthorController": myAuthor
deactivate ":MemoAuthorRepo"

":CreateAuthorController" --> ":CreateAuthorUI": myAuthor
deactivate ":CreateAuthorController"

":CreateAuthorUI" --> Administrator: Done!
deactivate ":CreateAuthorUI"

@enduml