@startuml
'https://plantuml.com/sequence-diagram
hide footbox
title "As a User, I want to add one of my publications to a list of mine" - SDD

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

actor User
participant ":MiteLovers" as System

User -> System : I want to add one of my publications to one of my lists
activate "System"
System --> User : Select what list you want to add them to
deactivate System
User -> System : listOfPublications
activate System
System --> User : Select what available publications you want to add
deactivate System
User -> System : publicationsToAdd
activate System
System --> User : Done
deactivate "System"

@enduml