@startuml
title "As a User, I want to add one of my publications to a list of mine" SD
hide footbox

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

actor "User"
participant ":AddItemToListUI" as UI
participant ":AddItemToListController" as Ctl
participant ":ILibraryRepo" as ILibraryRepo
participant ":IListOfItemsRepo" as IListRepo

"User" -> UI : I want to add one of my items to a list of mine
activate UI

UI -> Ctl : getItemsInMyLibrary(userId)
activate Ctl
Ctl -> ILibraryRepo : getItemsInLibraryByUserId(userId)
activate ILibraryRepo
ILibraryRepo --> Ctl : List<ItemId>
deactivate ILibraryRepo
Ctl --> UI : List<ItemId>
deactivate Ctl

UI --> "User" : Select which item you wish to add
deactivate UI
"User" -> UI : itemId
activate UI

UI -> Ctl : getMyLists(userId)
activate Ctl
Ctl -> IListRepo : findListsByUserId(userId)
activate IListRepo
IListRepo --> Ctl : Map<ListOfItemsId, String>
deactivate IListRepo
Ctl --> UI : Map<ListOfItemsId, String>
deactivate Ctl

UI --> "User" : Select which list you wish to add it to
deactivate UI
"User" -> UI : listOfItemsId
activate UI

UI -> Ctl : addItemToList(itemId, listOfItemsId)
activate Ctl

Ctl -> IListRepo : ofIdentity(listOfItemsId)
activate IListRepo
IListRepo --> Ctl : list
deactivate IListRepo

Ctl -> "list:ListOfItems" : addItem(itemId)
activate "list:ListOfItems"
deactivate "list:ListOfItems"

Ctl -> IListRepo : save(list)

ref over IListRepo
[[sd-ref-diagrams/Save_ListOfItems.puml Save list and return saved domain object]]
end ref

activate IListRepo
IListRepo --> Ctl : savedList
deactivate IListRepo

Ctl --> UI : true
deactivate Ctl
UI --> "User" : Done!
deactivate UI

@enduml