@startuml
title US004 - "Register a new Appraisal Entity, including the genres and publication types it can appraise" - SD
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber


actor Administrator
participant "UI1:RegisterNewAppraisalEntityUI" as UI
participant "Ctl1:RegisterNewAppraisalEntityController" as ctl
participant "_ptr:IPublicationTypeRepo" as ptr
participant "_gr:IGenreRepo" as grRepo
participant "_aer:MemoAppraisalEntityRepo" as aeRepo
participant "aef:AppraisalEntityFactory" as aeFactory

Administrator -> UI: I want to register an Appraisal Entity
activate UI
UI --> Administrator: What is the Appraisal Entity's name?
deactivate UI
Administrator -> UI: name
activate UI
UI -> ctl: getPublicationTypes()
activate ctl
ctl -> ptr: getPublicationTypes()
activate ptr
ptr --> ctl: copyOfListOfPublicationTypes
deactivate ptr
ctl --> UI: copyOfListOfPublicationTypes
deactivate ctl

UI --> Administrator: Here's the list of Publication Types, \n which one(s) can it appraise?
deactivate UI

Administrator -> UI: publicationTypes
activate UI
UI -> ctl: getGenres()
activate ctl
ctl -> grRepo: getGenres()
activate grRepo
grRepo --> ctl: copyOfListOfGenres
deactivate grRepo
ctl --> UI: copyOfListOfOfficialGenres
deactivate ctl
UI --> Administrator: Here's the list of Genres, which \n one(s) can it appraise?
deactivate UI

Administrator -> UI: genres
activate UI
UI -> ctl: registerNewAppraisalEntity(name, publicationTypes, genres)
activate ctl
ctl -> aeRepo: registerNewAppraisalEntity(name, publicationTypes, genres)
activate aeRepo
create "_listae:List <AppraisalEntity>"
aeRepo -->> "_listae:List <AppraisalEntity>": <<Create>>

opt appraisalEntityExists(name, publicationTypes, genres) == false
        aeRepo -> aeFactory: createAppraisalEntity(name, publicationTypes, genres)
        create "_AppraisalEntity:AppraisalEntity"
        activate aeFactory
        aeFactory -->> "_AppraisalEntity:AppraisalEntity": <<Create>>
        aeFactory -> aeRepo: _AppraisalEntity
        deactivate aeFactory
        aeRepo -> "_listae:List <AppraisalEntity>":add(_AppraisalEntity)
        activate "_listae:List <AppraisalEntity>"
        "_listae:List <AppraisalEntity>" --> aeRepo: true
    end

deactivate "_listae:List <AppraisalEntity>"
aeRepo --> ctl: _AppraisalEntity
deactivate aeRepo
ctl --> UI: _AppraisalEntity
deactivate ctl
UI --> Administrator: Done!
deactivate UI



@enduml