@startuml
'==== Title ====
title US004 - "As an Administrator, I want to register an Appraisal Entity, including the list of genres and publication types it can appraisal" - SD


'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox
autonumber


' ==== Actor and participants ====
actor Administrator
participant ":RegisterNewAppraisalEntityUI" as UI
participant ":RegisterNew\nAppraisalEntityController" as CTL
participant ":IPublicationTypeRepo" as PTR
participant ":IGenreRepo" as grRepo
participant ":MemoAppraisalEntityRepo" as aeRepo
participant ":AppraisalEntityFactory" as Factory


'==== UI interaction ====
Administrator -> UI: I want to register an Appraisal Entity
activate UI
UI --> Administrator: What is the Appraisal Entity's name?
deactivate UI
Administrator -> UI: name
activate UI

'==== Use case execution ====
UI -> CTL: getPublicationTypes()
activate CTL
CTL -> PTR: findAllKeys()
activate PTR
PTR --> CTL: List<PublicationTypeId>
deactivate PTR
CTL --> UI: List<PublicationTypeId>
deactivate CTL

UI --> Administrator: Here's the list of Publication Types, \n which one(s) can it appraise?
deactivate UI

Administrator -> UI: publicationTypes
activate UI
UI -> CTL: getGenres()
activate CTL
CTL -> grRepo: findAllKeys()
activate grRepo
grRepo --> CTL: List<GenreId>
deactivate grRepo
CTL --> UI: List<GenreId>
deactivate CTL

UI --> Administrator: Here's the list of Genres, which \n one(s) can it appraise?
deactivate UI

Administrator -> UI: genres
activate UI
UI -> CTL: registerNewAppraisalEntity(\nname, publicationTypeIds, genreIds)
activate CTL
CTL -> aeRepo: addAppraisalEntity(name, publicationTypeIds, genreIds)
activate aeRepo

aeRepo -> Factory: createAppraisalEntity(\nname, publicationTypeIds, genreIds)
create "appraisalEntity:AppraisalEntity"

activate Factory
Factory -->> "appraisalEntity:AppraisalEntity": <<create>>
Factory -> aeRepo: appraisalEntity
deactivate Factory

aeRepo -> aeRepo : isRepeated = containsOfIdentity(appraisalEntity.identity())

opt !isRepeated

        aeRepo -> aeRepo : save(appraisalEntity)

    end

aeRepo --> CTL: appraisalEntity
deactivate aeRepo
CTL --> UI: appraisalEntity
deactivate CTL
UI --> Administrator: Done!
deactivate UI

@enduml