
@startuml
title **"As an Administrator, I want to register a user in the system"**  SD
hide footbox

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

actor "Admin" as Administrator
participant ":RegisterNewUserUI" as UI
participant ":RegisterNewUserController" as Ctl
participant ":UserFactory" as Factory
participant ":IUserRepo" as IR

Administrator -> "UI": I want to register a user in the system.
activate "UI"
"UI" --> Administrator: What is the name and the email?
Administrator -> "UI": name, email
"UI" -> "Ctl": registerNewUser(name, email)
activate "Ctl"


Ctl -> "Factory" : createUser(name, email)

activate "Factory"

create "newUser:User"
Factory -->> "newUser:User" : <<create>>(name, email)
Factory --> Ctl: newUser
deactivate "Factory"

ref over Ctl
[[sd-ref-diagrams/Verify_User.puml Verify the existence of newUser in persistence]]
end ref

Ctl -> IR : save(newUser)

ref over IR
[[sd-ref-diagrams/Save_User.puml Save newUser and return saved domain object]]
end ref
activate IR
IR --> Ctl : reconstructedUser
deactivate IR
Ctl --> UI : reconstructedUser
deactivate Ctl
UI --> Administrator : Registered successfully!
deactivate UI

@enduml