@startuml
'==== Title ====
title "As an Administrator, I want to register a new city in the system" SD

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox
autonumber

participant ":RegisterCityController" as CTL
participant ":JpaCityRepo" as JPA
participant ":CityAssembler" as CASS
participant "city:City" as CITY
participant ":ICitySpringDataRepo" as SDREPO
participant ":CityFactory" as FACTORY
database "DB" as DB

activate CTL
CTL -> JPA : save(city)
activate JPA
JPA -> CASS : toDataModel(city)
activate CASS
CASS -> CITY : stringId = identity().toString()
activate CITY
deactivate CITY
CASS -> CITY : stringName = getName()
activate CITY
deactivate CITY
CASS -> CITY : countryId = getCountryId().toString()
activate CITY
deactivate CITY
create "dm:CityDataModel"
CASS -> "dm:CityDataModel" : <<create>>(stringId, stringName, countryId)
CASS --> JPA : dm
deactivate CASS

JPA -> SDREPO : save(dm)
activate SDREPO
SDREPO -> DB : savedDM = save(dm)
SDREPO --> JPA : savedDM
deactivate SDREPO

JPA -> CASS : toDomain(savedDM)
activate CASS
CASS -> "dm:CityDataModel" : name = get_name()
activate "dm:CityDataModel"
deactivate "dm:CityDataModel"
create "countryId:CountryId"
CASS -> "countryId:CountryId" : <<create>>(get_countryId)
create "cityId:CityId"
CASS -> "cityId:CityId" : <<create>>(name, countryId)
CASS -> FACTORY : createCity(name, countryId, cityId)
create "recontructedCity:City"
activate FACTORY
FACTORY -> "recontructedCity:City" : <<create>>(name, countryId, cityId)
FACTORY --> CASS : reconstructedCity
deactivate FACTORY
CASS --> JPA : reconstructedCity
deactivate CASS
JPA --> CTL : reconstructedCity

ref over CTL
[[../Register_City_SD.puml Back to Main Diagram]]
end ref





@enduml