@startuml
'==== Title ====
title "As a User, I want to use a Web UI to create a private list of my publications, \n give it a name, set a genre and, eventually, share it." - SD

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox
autonumber

' ==== Actor and participants ====
actor User
participant ":Client" as CLI
participant ":Server" as SER
database "DB" as DB

User -> CLI : Show me what I can do here
activate CLI
CLI -> SER : OPTIONS /my-lists {...}
activate SER
SER --> CLI : [POST], [GET], [PATCH], [DELETE]
deactivate SER
CLI --> User : These are your available resources
deactivate CLI

User -> CLI : Show me my lists of items
activate CLI
CLI -> SER : GET /my-lists {...}
activate SER
SER -> DB : select
DB --> SER : data
SER --> CLI : HTTP STATUS 200 {...}
deactivate SER
CLI --> User : display lists of items
deactivate CLI

User -> CLI : create a new list
activate CLI
CLI -> SER : GET /genres {...}
activate SER
SER -> DB : select
DB --> SER : data
SER --> CLI : HTTP STATUS 200 {...}
note right of CLI
Populates the item dropdown inside
the create new list form with all available genres
end note
deactivate SER
CLI --> User : displays available genres
deactivate CLI

User -> CLI : name, genreId
activate CLI
CLI -> SER : POST /my-lists {"name": "Sci-fi books", "genreId": "SCIENCE FICTION"}
activate SER
SER -> DB : insert
DB --> SER : data
SER --> CLI : HTTP STATUS 201 {...}
deactivate SER
CLI --> User : Success!
deactivate CLI

@enduml