@startuml
title "Get items on auction of a given genre, sorted ascendingly by deadline" - SD
hidefootbox

skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam ArrowFontColor #3B4953

autonumber
autoactivate off

actor Buyer
participant ":GetItemsOnAuctionOfA\nGivenGenreUI" as UI
participant ":GetItemsOnAuctionOfA\nGivenGenreController" as CTL
participant "itemRepo:IItemRepo" as IRepo
participant "publication:Publication" as Publication
participant "auctionRepo:IAuctionRepo" as ARepo


Buyer -> UI: I want the list of items \non auction of a given genre
activate UI
UI -> CTL : findAllKeys()
activate CTL
ref over CTL
[[sd-ref-diagrams/Get_Genre_Ids.puml Get All Genre Ids]]
end ref

CTL --> UI : genreIds
deactivate CTL
UI --> Buyer: Select genreId
deactivate UI
Buyer -> UI: genreId
activate UI

UI -> CTL: getAuctionItems\nByGenreId(genreId)
activate CTL

ref over CTL
[[../sd-ref-diagrams/Get_Items.puml Get ItemIds of a Given Genre]]
end ref
note right of CTL: This ref returns 'itemIdsOfGenre'

CTL -> ARepo : findByItemsIdSorted(itemIdsOfGenre)
activate ARepo
note right: Sorts results by AuctionEndDate Asc
ARepo --> CTL : sortedItemsByDeadline
deactivate ARepo

CTL --> UI: sortedItemsByDeadline
deactivate CTL

UI --> Buyer: Here's the sorted list!
deactivate UI


@enduml
