@startuml
title "As a Buyer, I want to get the list of items on auction of a given genre" - SD
hidefootbox

skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam ArrowFontColor #3B4953

autonumber
autoactivate off

actor Buyer
participant ":GetItemsOnAuctionOfA\nGivenGenreUI" as UI
participant ":GetItemsOnAuctionOfA\nGivenGenreController" as CTL
participant "publication:Publication" as Publication


Buyer -> UI: I want the list of items \non auction of a given genre
activate UI
UI -> CTL : findAllKeys()
activate CTL
ref over CTL
[[sd-ref-diagrams/Get_Genre_Ids.puml Get All Genre Ids]]
end ref



CTL --> UI : genreIds
deactivate CTL
UI --> Buyer: Select genreId
deactivate UI
Buyer -> UI: genreId
activate UI


UI -> CTL: getAuctionItems\nByGenreId(authorId)
activate CTL

ref over CTL
[[sd-ref-diagrams/Get_Auctions.puml Get Auctions]]
end ref

create "listOfItemsOnAuction\nByGenre:List<ItemId>"
CTL -->> "listOfItemsOnAuction\nByGenre:List<ItemId>" : <<Create>>

loop for auction : auctions
ref over CTL
[[sd-ref-diagrams/Get_Items_Id_Auction.puml Get Items Ids on Auction]]
end ref

loop for itemId : itemIds
ref over CTL
[[sd-ref-diagrams/Get_Items.puml Get Items]]
end ref

ref over CTL
[[sd-ref-diagrams/Get_Edition_Id_Item.puml Get Edition Ids on Item]]
end ref

ref over CTL
[[sd-ref-diagrams/Get_Edition.puml Get Edition]]
end ref

ref over CTL
[[sd-ref-diagrams/Get_Publication_Id.puml Get Publication Id]]
end ref

ref over CTL
[[sd-ref-diagrams/Get_Publication.puml Get Publication]]
end ref

CTL -> Publication : hasGenreId = isByGenreId(GenreId)

opt hasGenreId
CTL -> "listOfItemsOnAuction\nByGenre:List<ItemId>" : add(itemId)
activate "listOfItemsOnAuction\nByGenre:List<ItemId>"
"listOfItemsOnAuction\nByGenre:List<ItemId>" --> CTL : true
deactivate "listOfItemsOnAuction\nByGenre:List<ItemId>"
end
end
end


CTL --> UI: listOfItemsOnAuctionByGenre
deactivate CTL

UI --> Buyer: Here's the list! Done!
deactivate UI

@enduml
