@startuml
'https://plantuml.com/sequence-diagram

autonumber
title "As a Buyer, I want to get the list of items on auction of a given genre" - SD

hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---'

actor Buyer
participant "UI1: GetAuctionItemsByGenreUI" as UI
participant "ctl: GetAuctionItemsByGenreController" as CTL
participant "IGenreRepo" as GR
participant "ar: IAuctionRepo" as AuctionRepo
participant "auction: Auction" as Auction
participant "IItemRepo" as IR
participant "item: Item" as Item
participant "IEditionRepo" as ER
participant "edition: Edition" as Edition
participant "IPublicationRepo" as PR
participant "publication: Publication" as Pub

Buyer -> UI: I want the list of items %n()on auction of a given genre
activate UI
UI -> CTL:findAllKeys()
activate CTL
CTL -> GR:findAllKeys()
activate GR

GR --> CTL:genreIds
deactivate GR

CTL --> UI:genreIds
deactivate CTL
UI --> Buyer: Select genreId
deactivate UI

Buyer -> UI: genreId
activate UI

UI -> CTL: getAuctionItemsByGenreId(genreId)
activate CTL

CTL -> AuctionRepo: findAll()
activate AuctionRepo

AuctionRepo --> CTL: auctions
deactivate AuctionRepo

create "listOfItemsOnAuctionByGenre : List<ItemId>" as List
CTL -->> List : <<Create>>

loop for auction : auctions
CTL -> Auction : getItemsId()
activate Auction
Auction --> CTL : itemsId
deactivate Auction

loop for itemId : itemsId
     CTL -> IR: ofIdentity(itemsId)
     activate IR
     IR --> CTL : item
     deactivate IR
     CTL -> Item : getEditionId()
     activate Item
     Item --> CTL : editionId
     deactivate Item

     CTL -> ER : ofIdentity(editionId)
     activate ER
     ER --> CTL : edition
     deactivate ER
     CTL -> Edition : getPublicationId()
     activate Edition
     Edition --> CTL : publicationId
     deactivate Edition

     CTL -> PR : ofIdentity(publicationId)
     activate PR
     PR --> CTL : publication
     deactivate PR

     CTL -> Pub : hasGenreId = isByGenreId(genreId)

    opt hasGenreId
        CTL -> List : add(itemId)
        activate List
        List --> CTL : true
        deactivate List
        end
    end
end

CTL --> UI: listOfItemsOnAuctionByGenre
deactivate CTL

UI --> Buyer: Here's your list!
deactivate UI

@enduml