@startuml

title CD (Class Diagram) - to get list of all publication types (US014)

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam backgroundColor CornSilk
skinparam classBackgroundColor WhiteSmoke
skinparam classAttributeIconSize 0

class UIPublicationTypeList {
}

class GetPublicationTypeListController {
    - publicationTypeRepo : PublicationTypeRepo
    + getListOfPublicationTypes() : List<PublicationType>
}

class PublicationTypeRepo {
    - publicationTypes : List<PublicationType>
    + existsPublicationType(typeName : String) : boolean
    + createPublicationType(typeName : String) : PublicationType
    + getAll() : List<PublicationType>
}

UIPublicationTypeList "1" ..> "1" GetPublicationTypeListController : invokes
GetPublicationTypeListController "1" ..> "1" PublicationTypeRepo : use

@enduml
