@startuml
title SD N2 (Sequence Diagram) - to get list of publication types (US014)

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox

actor User

participant "UI : UserPublicationTypeList" as UI
participant "Ctrl : GetPublicationTypeListController" as CTRL
participant "_Ptr : PublicationTypeRepo" as SVC

User -> UI : 1. I want to know all publication types
UI -> CTRL : 2. getListOfPublicationTypes()
CTRL -> SVC : 3. getAll()

SVC --> CTRL : 4. PublicationTypeList
CTRL --> UI : 5. PublicationTypeList
UI --> User : 6. Here's the list!

@enduml
