@startuml
title "As a User, I want to register a new publication in the system" - SD

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox
autonumber

' --- Actor and participants ---
actor User
participant ":RegisterPublicationUI" as UI
participant ":RegisterNew\nPublicationController" as Ctl
participant ":PublicationFactory" as PF
participant ":IPublicationRepo" as IR
' --- UI interaction ---
User -> UI: I want to register \na new publication
activate UI

UI -> Ctl: getAuthorsId()
activate Ctl
ref over Ctl
[[sd-ref-diagrams/Get_Author_Ids.puml Retrieve the list of all author Ids]]
end ref

Ctl --> UI: authorIds
deactivate Ctl
UI --> User: Select authorId
deactivate UI

User -> UI: authorId
activate UI

UI -> Ctl: getGenresId()
activate Ctl
ref over Ctl
[[sd-ref-diagrams/Get_Genre_Ids.puml Retrieve the list of all genre Ids]]
end ref

Ctl --> UI: genreIds
deactivate Ctl
UI --> User: Select genreId
deactivate UI

User -> UI: genreId
activate UI

UI --> User: Fill in the title and release year
deactivate UI

User -> UI: title, releaseYear
activate UI

' --- Use case execution ---
UI -> Ctl: registerPublication(title, authorId, \nreleaseYear, genreId, synopsis)
activate Ctl


' --- Creation  ---
Ctl -> PF: createPublication\n(title, authorId, releaseYear, genreId, synopsis)
activate PF
create "newPublication:Publication"
PF -->> "newPublication:Publication": createPublication\n(title, authorId, releaseYear, genreId, synopsis)
PF --> Ctl: newPublication
deactivate PF

ref over Ctl
[[sd-ref-diagrams/Verify_Publication.puml Verify the existence of newPublication in persistence]]
end ref

Ctl -> IR : save(newPublication)
activate IR

ref over IR
[[sd-ref-diagrams/Save_Publication.puml Save newPublication and return saved domain object]]
end ref

IR -> Ctl : reconstructedPublication
deactivate IR

Ctl --> UI : reconstructedPublication
deactivate Ctl

UI --> User : You have \nsuccessfully \nregistered a \nnew publication.

@enduml
