@startuml
'https://plantuml.com/class-diagram
title US010 - "As a User, I want to register a new publication in the system" - CD

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0

'==== classes ====
class RegisterPublicationUI {}

class RegisterNewPublicationController {
  + registerPublication(publicationType: PublicationType, %n()identifier: Identifier, publicationYear: Year, title: Title, author: Author, %n()publisher: PublishingCompany, edition: Edition, %n()genre: Genre) : Publication
}

interface IPublicationRepo {
  + addPublication(publicationType: PublicationType, %n()identifier: Identifier, publicationYear: Year, title: Title, author: Author, %n()publisher: PublishingCompany, edition: Edition, %n()genre: Genre) : Publication
}

class MemoPublicationRepo{
- _publications: List<Publication>
  - add(publication: Publication) : Publication
  - contains(publication: Publication): boolean
}

class PublicationFactory{
+ createPublication(publicationType: PublicationType, %n()identifier: Identifier, publicationYear: Year, title: Title, author: Author, %n()publisher: PublishingCompany, edition: Edition, %n()genre: Genre) : Publication
}

class Publication{
  - _publicationType: PublicationType
  - _identifier: Identifier
  - _publicationYear: Year
  - _title: Title
  - _author: Author
  - _publisher: Publisher
  - _edition: Edition
  - _genre: Genre
}

/' interface EditionId {
  + getIdentifier(): String
 }
class ISBN {
  - _isbn: String
  + equals(Object): boolean
  + getIdentifier(): String
  }
class ISSN {
  - _issn: String
  + equals(Object): boolean
  + getIdentifier(): String
  }

class NoEditionId {
  - _noIdentifier: String
  + NoEditionId()
  + getIdentifier(): String
  }
'/
'==== relations ====
RegisterPublicationUI "1" ..> "1" RegisterNewPublicationController : uses
RegisterNewPublicationController "1" --> "1" IPublicationRepo: uses
IPublicationRepo "1" <|.. "1" MemoPublicationRepo
MemoPublicationRepo "1" --> "*" PublicationFactory : uses
PublicationFactory "1" --> "*" Publication : creates
'Publication --> "1" EditionId : has


' --- identifier hierarchy ---
/'EditionId <|.. ISBN
EditionId <|.. ISSN
EditionId <|.. NoEditionId'/

note right of MemoPublicationRepo
  these methods are
  implementation details
  of MemoPublicationRepo
end note

note right of Publication
  abstract editorial work,
  independent of any specific copy;
  previously named PublicationInfo
end note

note left of Publication
identifier is either %n()ISBN, ISSN or %n()NoIdentifier
end note

@enduml