@startuml
title "As a User, I want to register a new publication in the system" - SD

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox
autonumber

' --- Actor and participants ---
actor User
participant ":RegisterPublicationUI" as UI
participant ":RegisterNew\nPublicationController" as Ctl
participant ":MemPublicationRepo" as PR
participant ":PublicationFactory" as PF

' --- UI interaction ---
User -> UI: I want to register \na new publication
activate UI
UI --> User: Fill in the publication's \ninformation
deactivate UI

User -> UI: title, author, \n releaseYear, genre
activate UI

' --- Use case execution ---
UI -> Ctl: registerPublication(title, authorId, \nreleaseYear, genreId)
activate Ctl


' --- Creation  ---
Ctl -> PF: createPublication\n(title, authorId, releaseYear, genreId)
activate PF
create "newPublication:Publication"
PF -->> "newPublication:Publication": <<create>>
PF --> Ctl: newPublication
deactivate PF

' --- Duplication check ---
Ctl -> PR : isRepeated = containsOfIdentity(newPublication.identity())
    opt !isRepeated == true
            Ctl -> PR: save(newPublication)
PR --> Ctl: newPublication
    end

deactivate PR

Ctl --> UI: newPublication
deactivate Ctl

UI --> User: You have \nsuccessfully \nregistered a \nnew publication.
deactivate UI
@enduml
