@startuml
hide footbox
title US017 - "As a User, I want to create a private list of my publications, give it a name and set a genre" - SD

'==== basic style ===='
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ArrowColor #57595BAA

autonumber
autoactivate off

'==== Actor and Participants ===='
actor "User"

participant ":CreatePrivateListOfItemsUI" as UI
participant ":CreatePrivateListOfItemsController" as CTL
participant ":IListOfItemsRepo" as IRepo
participant ":ListOfItemsFactory" as Factory
participant ":IGenreRepo" as IGenreRepo

'==== UI interaction ===='
"User" -> UI: I want to create a private list
activate UI

"User" <-- UI: What is the list's name?
deactivate UI
"User" -> UI: name
activate UI

UI -> CTL: getMapOfOfficialGenres()
activate CTL
CTL -> IGenreRepo: getMapOfOfficialGenres()
activate IGenreRepo
CTL <-- IGenreRepo: copyMapOfOfficialGenres
deactivate IGenreRepo
UI <-- CTL: copyMapOfOfficialGenres
deactivate CTL

"User" <-- UI: What genre?
deactivate UI
"User" -> UI: genreId
activate UI

'==== Use case execution ===='
UI -> CTL: addListOfItems\n(userId, name, genreId)
activate CTL
CTL -> IRepo: addListOfItems\n(userId, name, genreId)
activate IRepo


    opt existsListOfItems (listOfItems) == false

        IRepo -> Factory: createListOfItems\n(userId, name, genreId)
        activate Factory

        create "listOfItems:ListOfItems" as listOfItems
        Factory -->> listOfItems: <<create>>
        note right of listOfItems
                  The private attribute
                  (_isPrivate = true)
                  is set by default
                  in the constructor
              end note
        Factory --> IRepo: listOfItems
        deactivate Factory
        IRepo --> IRepo: save(listOfItems)

    end


IRepo --> CTL: listOfItems
deactivate IRepo
UI <-- CTL: listOfItems
deactivate CTL
"User" <-- UI: Private list successfully created!
deactivate UI

@enduml