@startuml
'==== Title ====
title US017 - "As a User, I want to create a private list of my publications, give it a name and set a genre" - CD
top to bottom direction

'==== basic style ====
skinparam monochrome false
skinparam shadowing true
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ArrowColor #57595BAA
skinparam classAttributeIconSize 0

'==== Entities ===='
interface IListOfItemsRepo {
    + addListOfItems(userId : UserId, name : String, genreId : GenreId) : ListOfItems
}

class MemoListOfItemsRepo {
    - _listsOfItems: List<ListOfItemsId>

    + addListOfItems(userId : UserId, name : String, genreId : GenreId) : ListOfItems
}

class CreatePrivateListOfItemsController {
	+ getAllGenres() : Map<GenreId, String>
	+ createListOfItems(userId : UserId, name : String, genreId : GenreId) : ListOfItems
}

class ListOfItemsFactory {
    + createListOfItems(userId, name, genreId) : ListOfItems
}

interface IGenreRepo {
    + getMapOfOfficialGenres(): Map<GenreId, String>
}

class MemoGenreRepo {
    + getMapOfOfficialGenres(): Map<GenreId, String>
}

class ListOfItemsId {
    + newId(): static
}

interface DomainId {}

class ListOfItems {
    - _id : ListOfItemsId
    - _userId : UserId
    - _name : String
    - _genreId : GenreId
    - _itemIds : List<ItemId>
    - _isPrivate : boolean

    + getListOfItemsId(): ListOfItemsId
    + getItemIds(): List<ItemId>
    + addItem(itemId : ItemId): void
}

class ItemId {}

interface AggregateRoot {}


'==== Interactions ===='

CreatePrivateListOfItemsUI "1" ..> "1" CreatePrivateListOfItemsController: invokes
CreatePrivateListOfItemsController "1" ..> "1" IGenreRepo: calls
IGenreRepo <|.. MemoGenreRepo: implements
CreatePrivateListOfItemsController  "1" ..> "1" IListOfItemsRepo: calls
IListOfItemsRepo <|.. MemoListOfItemsRepo: implements
MemoListOfItemsRepo "1" --> "*" ListOfItemsFactory: delegates
ListOfItemsFactory "1" --> "*" ListOfItems: creates
ListOfItems "1" --> "1" ListOfItemsId: has
ListOfItems "*" --> "*" ItemId: references
ListOfItems ..|> AggregateRoot: implements
ListOfItemsId ..|> DomainId: implements


@enduml
