@startuml
title "As a Buyer, I want to get the list of items on direct sale of a given publication" - SD
hidefootbox

skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam ArrowFontColor #3B4953

autonumber
autoactivate off

actor Buyer
participant ":GetDirectSaleItemsByPublicationsUI" as UI
participant ":GetDirectSaleItemsByPublicationsController" as CTL
participant ":IPublicationRepo" as PR
participant ":IDirectSaleRepo" as DSR
participant "directSale:DirectSale" as DirectSale
participant ":IItemRepo" as IR
participant "reconstructed%n()Item:Item" as Item
participant ":IEditionRepo" as ER
participant "reconstructed%n()Edition:Edition" as Edition


Buyer -> UI: I want to get a list of items %n()on direct sale of a given publication
activate UI
UI -> CTL : findAllKeys()
activate CTL
CTL -> PR : findAllKeys()
activate PR
ref over PR
[[sd-ref-diagrams/Find_All_Publication_Ids.puml Find all PublicationIds from persistence (via JPA)]]
end ref
PR --> CTL : publicationIds
deactivate PR

CTL --> UI : publicationIds
deactivate CTL
UI --> Buyer: Which publication?
deactivate UI
Buyer -> UI: publicationId
activate UI


UI -> CTL: getDirectSaleItemsByPublication(publicationId)
activate CTL

CTL -> DSR: findAll()
activate DSR
ref over DSR
[[sd-ref-diagrams/Find_All_Direct_Sales.puml Final all DirectSales from persistence (via JPA)]]
end ref
DSR --> CTL: directSales
deactivate DSR

create "listOfItemsOnDirectSale%n()ByPublication:List<ItemId>"
CTL -->> "listOfItemsOnDirectSale%n()ByPublication:List<ItemId>" : <<create>>

loop for directSale : directSales
CTL -> DirectSale : getItemsId()
activate DirectSale
DirectSale --> CTL : itemIds
deactivate DirectSale

loop for itemId : itemIds
CTL -> IR : ofIdentity(itemId)
activate IR
ref over IR
    [[sd-ref-diagrams/Retrieve_Item.puml Retrieve Item from persistence (via JPA)]]
end ref
IR --> CTL : reconstructedItem
deactivate IR
CTL -> Item : getEditionId()
activate Item
Item --> CTL : editionId
deactivate Item

CTL -> ER : ofIdentity(editionId)
activate ER
ref over ER
[[sd-ref-diagrams/Retrieve_Edition.puml Retrieve Edition from persistence (via JPA)]]
end ref
ER --> CTL : reconstructedEdition
deactivate ER


CTL -> Edition : isByPublicationId(publicationId)
activate Edition
Edition --> CTL : true
deactivate Edition

CTL -> "listOfItemsOnDirectSale%n()ByPublication:List<ItemId>" : add(itemId)
activate "listOfItemsOnDirectSale%n()ByPublication:List<ItemId>"

deactivate "listOfItemsOnDirectSale%n()ByPublication:List<ItemId>"
end
end


CTL --> UI: listOfItemsOnDirectSaleByPublication
deactivate CTL

UI --> Buyer: Here is the list.
deactivate UI

@enduml