@startuml
title US016 – "As a User, I want to put for sale a publication in my library in an auction" %n() SD
hide footbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber

' --- Actor and participants ---
actor "User" as User
participant ":PublicationSaleAuctionUI" as UI
participant ":PublicationSaleAuctionController" as Controller
participant ":LibraryRepo" as LibraryRepo
participant "userLibrary: Library" as userLibrary
participant ":ItemRepo" as ItemRepo
participant ":AuctionRepo" as AuctionRepo
participant ":ItemFactory" as ItemFactory
participant ":AuctionFactory" as AuctionFactory

' Design of happy path

User -> UI : I want to put a publication in my library for sale in an auction
activate UI
UI -> Controller : getLibraryPublicationList(user)
activate Controller
Controller -> LibraryRepo : findByUser(user)
activate LibraryRepo
LibraryRepo --> Controller : userLibrary: Library
deactivate LibraryRepo
Controller -> userLibrary : getPublicationsInLibrary()
activate userLibrary
userLibrary --> Controller : publicationsList
note right userLibrary
 getPublicationsInLibrary() returns publicationsList,
 an unmodifiable copy of the publications in the user’s
 library, represented as PublicationDetails objects
end note
deactivate userLibrary
Controller --> UI : publicationsList
deactivate Controller
UI --> User : Which publication?
User -> UI : publication
UI --> User : What is its condition?
User -> UI : Please provide auction details
User -> UI : startingPrice, auctionStartDate, auctionEndDate
UI -> Controller: putPublicationOnAuction(user, publication, %n()condition, startPrice, startDate, endDate)
activate Controller
note over Controller: LibraryRepo: Same retrieval logic %n()as in getLibraryPublicationList(user) %n()but for separate use case
Controller -> LibraryRepo: findByUser(user)
activate LibraryRepo
LibraryRepo --> Controller: userLibrary: Library
deactivate LibraryRepo
Controller -> userLibrary : getPublicationFromLibrary(publication)
activate userLibrary
userLibrary --> Controller : p1
deactivate userLibrary
note left Controller
 Publication is retrieved from
 userLibrary, ensuring it belongs to
 that Library, then is turned into
 an Item to be put for sale in auction
end note

Controller -> ItemRepo : createItem(p1, condition)
activate ItemRepo
ItemRepo -> ItemFactory : createItem(p1, condition)
activate ItemFactory
create i1 as "i1: Item"
ItemFactory --> i1 : create()
ItemFactory --> ItemRepo : i1
deactivate ItemFactory
ItemRepo --> Controller : i1
deactivate ItemRepo

Controller -> AuctionRepo : createAuction(i1, startPrice, startDate, endDate)
activate AuctionRepo
AuctionRepo -> AuctionFactory : createAuction(i1, startPrice, startDate, endDate)
activate AuctionFactory
create a1 as "a1: Auction"
AuctionFactory --> a1: create()
AuctionFactory --> AuctionRepo : a1
deactivate AuctionFactory
AuctionRepo --> Controller : a1
deactivate AuctionRepo

Controller -> i1 : setAuction(a1)
activate i1
i1 --> Controller : [ok]
deactivate i1

Controller --> UI : a1
deactivate Controller
UI --> User : Your item was successfully put up for sale in an auction
deactivate UI

@enduml