@startuml
'https://plantuml.com/class-diagram
title US016 – "As a User, I want to put for sale a publication in my library in an auction %n() CD


'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0


class PublicationSaleAuctionUI {
}

class PublicationSaleAuctionCtl {
  - _libraryRepo: LibraryRepo
  - _publicationRepo: PublicationRepo
  - _itemRepo: ItemRepo
  - _auctionRepo: AuctionRepo
  --
  + getLibraryPublicationList(user: User): List<PublicationDetails>
  + putPublicationOnAuction(publicationId: PublicationId, condition: Condition,
                           startPrice: Price, startDate: ZonedDateTime,
                           endDate: ZonedDateTime): boolean
}

class LibraryRepo {
  - _libraries: List<Library>
  + findByUser(user: User): Library
}

class Library {
  - _owner: User
  - publications: List<Publication>
  + getPublicationsInLibrary(): List<PublicationDetails>
}

class Publication {
}

class PublicationRepo {
  - _publications: List<Publication>
  + findPublicationById(id: PublicationId): Publication
}

class ItemRepo {
  - items: List<Item>
  + createItem(publication: Publication, condition: Condition): Item
}

class Item {
  - publication: Publication
  - condition: Condition
  - auction: Auction
  + setAuction(auction: Auction): void
}

class AuctionRepo {
  - itemsOnAuction: List<Auction>
  + createAuction(item: Item, startPrice: Price,
                  startDate: ZonedDateTime, endDate: ZonedDateTime): Auction
}

class Auction {
  - _item: Item
  - _startingPrice: Price
  - _auctionStartDate: ZonedDateTime
  - _auctionEndDate: ZonedDateTime
}

' UI → Controller
PublicationSaleAuctionUI "1" ..> "1" PublicationSaleAuctionCtl : uses

' Controller → Repos
PublicationSaleAuctionCtl "1" ..> "1" LibraryRepo : calls
PublicationSaleAuctionCtl "1" ..> "1" PublicationRepo : calls
PublicationSaleAuctionCtl "1" ..> "1" ItemRepo : calls
PublicationSaleAuctionCtl "1" ..> "1" AuctionRepo : calls

' Repos → Domain objects
LibraryRepo "1"--> "*" Library : manages
PublicationRepo "1" --> "*" Publication: manages
ItemRepo "1" --> "*" Item : manages
AuctionRepo "1" --> "*" Auction : manages

' Domain relationships
Item "1" --> "1" Auction : sets
note right of Item
  Item has either Auction or DirectSale
  (not both; US016 sets Auction only)
end note
Library "1" --> "*" Publication : contains

note right of Publication
Publication is instantiated and used %n()as data/a parameter for this US016
end note

note as N1
Only US016 SD methods/attributes shown
end note

@enduml