@startuml
title US016 – "As a User, I want to put for sale a publication in my library in an auction" %n() SD
hide footbox

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber

actor "User" as User
participant "UI:PublicationSaleAuctionUI" as UI
participant "Ctl:PublicationSaleAuctionController" as Controller
participant "_lr:LibraryRepo" as LibraryRepo
participant "userLibrary: Library" as userLibrary
participant "_ar:AuctionRepo" as AuctionRepo
participant "_af:AuctionFactory" as AuctionFactory
participant "selectedItem:Item" as selectedItem
participant "newAuction: Auction" as newAuction

User -> UI : I want to put an item from my library\nfor sale in an auction
activate UI

UI -> Controller : getLibraryItemsList(user)
activate Controller

Controller -> LibraryRepo : findLibraryByUser(user)
activate LibraryRepo
LibraryRepo --> Controller : userLibrary
deactivate LibraryRepo

Controller -> userLibrary : getItemsInLibrary()
activate userLibrary
userLibrary --> Controller : itemsList
deactivate userLibrary

Controller --> UI : itemsList
deactivate Controller

UI --> User : Select the item to sell
deactivate UI
User -> UI : selectedItem
activate UI

UI --> User : Provide auction details
deactivate UI
User -> UI : startPrice, startDate, endDate
activate UI

UI -> Controller : putItemOnAuction(selectedItem,\nstartPrice, startDate, endDate)
activate Controller


Controller -> AuctionRepo : createAuction(selectedItem, startPrice, startDate, endDate)
activate AuctionRepo

AuctionRepo -> AuctionFactory : createAuction(selectedItem, startPrice, startDate, endDate)
activate AuctionFactory
create newAuction
AuctionFactory --> newAuction : create()
AuctionFactory --> AuctionRepo : newAuction
deactivate AuctionFactory

AuctionRepo --> Controller : newAuction
deactivate AuctionRepo

Controller -> selectedItem : setAuction(newAuction)
activate selectedItem
selectedItem --> Controller : ok
deactivate selectedItem

Controller --> UI : newAuction
deactivate Controller

UI --> User : Item successfully put on auction
deactivate UI

@enduml