@startuml
title "As a Buyer, I want to get the list of items on direct sale of a given author" - SD
hidefootbox

skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam ArrowFontColor #3B4953

autonumber
autoactivate off

actor Buyer
participant ":GetDirectSale\nItemsByAuthorUI" as UI
participant ":GetDirectSale\nItemsByAuthorController" as CTL
participant ":IDirectSaleRepo" as DSR
participant "directSale:DirectSale" as DirectSale
participant "IItemRepo"
participant "listOfItemsOnDirectSale\nByAuthor:List<ItemId>" as LIST
'==== UI interaction ====
Buyer -> UI: I want the list of items \non direct sale of a given author
activate UI

'==== Use case execution ====
UI -> CTL : findAllKeys()
activate CTL
ref over CTL
[[sd-ref-diagrams/Get_Authors_Ids.puml Retrieves the list of all Authors Ids]]
end ref



CTL --> UI : authorIds
deactivate CTL
UI --> Buyer: Select authorId
deactivate UI
Buyer -> UI: authorId
activate UI


UI -> CTL: getDirectSaleItemsByAuthorId(authorId)
activate CTL
ref over CTL
[[sd-ref-diagrams/Get_DirectSale_Items.puml Retrieves the list of all Direct Sale Items by Authors Ids]]
end ref


create LIST
CTL -->> LIST : <<create>>

loop for directSale : directSales
CTL -> DirectSale : getItemIds()
activate DirectSale
DirectSale --> CTL : itemIds
deactivate DirectSale

loop for itemId : itemIds

ref over CTL
[[sd-ref-diagrams/Get_Item_by_id.puml Get each Item by Id and retrieve its Edition Id]]
end ref



ref over CTL
[[sd-ref-diagrams/Get_Edition_by_Id.puml Get each Edition by Id and retrieve its Publication Id]]
end ref


ref over CTL
[[sd-ref-diagrams/Get_Publication_by_Id.puml Retrieves each Publication by Id]]
end ref


CTL -> Publication : hasAuthorId = isByAuthorId(authorId)

opt hasAuthorId
CTL -> LIST : add(itemId)
activate LIST
LIST --> CTL : true
deactivate LIST
end
end
end

ref over CTL
[[sd-ref-diagrams/Query_Repo.puml Query repository ordered by description]]
end ref



CTL --> UI: sortedlistOfItemsOnDirectSaleByAuthor
deactivate CTL

UI --> Buyer: Here's the list! Done!
deactivate UI

@enduml