@startuml
title US001 - "As an Administrator, I want to register a user in the system" - SD
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---
actor Admin
participant "UI1:RegisterNewUserUI" as UI
participant "Ctl1:RegisterNewUserController" as Ctl
participant "_ur:UserRepo" as UR

' --- UI interaction ---
Admin -> UI: I want to register a user in the system
activate UI
UI --> Admin:What is the name and the email
deactivate UI


Admin -> UI: Name, test@email.pt
activate UI



UI -> Ctl: registerNewUser(name, email )
activate Ctl

' --- Verify user existence and create ---
Ctl -> UR: registerNewUser(name, email)
activate UR
opt If email does not exist

' --- Create email, name and User---
create "newEmail:Email"
UR -> "newEmail:Email": createEmail(email)
create "newName:Name"
UR -> "newName:Name": createName(name)
create "newUser:User"
UR -> "newUser:User": createUser(name, email)
UR -> UR: add newUser
end
UR --> Ctl: newUser
deactivate UR
Ctl --> UI:newUser
deactivate Ctl
UI --> Admin: New User registered!
deactivate UI

@enduml