@startuml
title US024 - "As a Buyer, I want to get the list of items on auction of a given publication" - Level 2 SD
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---
actor Buyer
participant ":GetAuctionItemsByPublicationUI" as UI
participant ":GetAuctionItemsByPublicationController" as CTL
participant "_mar:MemoAuctionRepo" as mAR
participant "auction:Auction" as AU
participant "item:Item" as IT



' --- Dialog ---
Buyer -> UI: I want the list of items on auction of a given publication
activate UI
UI --> Buyer: Which publication?
deactivate UI
Buyer -> UI: publicationId
activate UI
UI -> CTL: getAuctionItemsByPublicationId(publicationId)
activate CTL
CTL -> mAR: getAuctionItemsByPublicationId(publicationId)
activate mAR

create "listOfAuctionItemsByPublicationId: List<ItemId>" as List
mAR -> List: <<Create>>()

loop for each auction in _mar
    mAR -> AU: isByPublicationId(publicationId)
    activate AU
    AU -> IT: isByPublicationId(publicationId)
    activate IT
    IT --> AU: true
    deactivate IT
    AU --> mAR: true
    deactivate AU



    opt isByPublicationId == true
        mAR -> List: add(auction.getItemId())
        activate List
        List --> mAR: true
        deactivate List
    end
end

create "copyOfListOfAuctionItemsByPublicationId: List<ItemId>" as Copy
mAR -> Copy: List.copyOf(ListOfAuctionItemsByPublicationId)


mAR --> CTL: copyOfListOfAuctionItemsByPublicationId
deactivate mAR
CTL --> UI: copyOfListOfAuctionItemsByPublicationId
deactivate CTL
UI --> Buyer: Here's the list! done!
deactivate UI

@enduml