@startuml
'==== Title ====
title MiteLovers – OOA-G2
top to bottom direction

'==== basic style ====

'hides unwanted text
hide stereotype

skinparam monochrome false

skinparam shadowing true
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ArrowColor #57595BAA

'undefined objects
skinparam object {
  BackgroundColor<<highlight>> 91C6BCAA
  BorderColor<<highlight>> 4B9DA9AA
  FontColor<<highlight>> 547792AA
}
skinparam shadowing<<highlight>> false


'==== entities ====
together {
object communityMember <<highlight>>
object user
object buyer
object supportService <<highlight>>
object seller
object appraisalService

}
object bidder
object logisticService <<highlight>>
together {
object publicationInfo
object book
object magazine
object item
object listing
object shoppingCart
object transaction
}
object auction
object bid

'=== OBJECTS IN DOUBT===
'object directSale
'object paymentProcessing
'object lineOfSale
'object activityHistory

'=== LISTING RELATIONS ===
publicationInfo "1" -- "*" book : < contains
publicationInfo "1" -- "*" magazine: < contains
book "0..1" --- "1" item: < represents
magazine "0..1" --- "1" item: < represents
item "1" -- "0..1" listing: < contains
listing "1" - "0..1" auction: < has
listing "*" -- "*" shoppingCart: < has
shoppingCart "1" -- "0..1" transaction: < processes

'===USER RELATIONS===
user "1" -- "0..1" bidder: < is a
user "1" -- "0..1" seller: < is a
user "1" -- "0..1" buyer: < is a
user "1" --[#4B9DA9AA] "0..1" supportService: < <font color="547792AA">supports</font>
user "1" --[#4B9DA9AA] "0..1" communityMember: < <font color="547792AA">is a</font>
buyer "*" -[#4B9DA9AA] "0..1" logisticService: <  <font color="547792AA">delivers to</font>
seller "*" -[#4B9DA9AA] "0..1" logisticService: < <font color="547792AA">collects from</font>
'logisticServices "1" --- "*" logisticAgent: manages

'===OTHER RELATIONS===
appraisalService "*" - "1" seller: < requests
appraisalService "*" -- "*" item: > appraises
seller "1" --- "1..*" listing:  > creates
supportService "1" --[#4B9DA9AA] "*" appraisalService: > <font color="547792AA">manages</font>
seller "*" --[#4B9DA9AA] "0..1" supportService: < <font color="547792AA">supports</font>
buyer "*" --[#4B9DA9AA] "0..1" supportService: < <font color="547792AA">supports</font>
bidder "*" --[#4B9DA9AA] "0..1" supportService: < <font color="547792AA">supports</font>
buyer "1" - "1" shoppingCart: > owns
bidder "1" --- "1..*" bid: < placed by
bid "*" ----- "1" auction: < holds
auction "1" -- "0..1" transaction: < processes
'logisticAgent "1" -- "1" transaction: handles
transaction "*" - "1" logisticService: < handles

@enduml
