@startuml
title US026 – "As a Buyer, I want to get the list of items on auction \nof a given author" - Level 3 SD
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---
actor Buyer
participant ":GetItemsOnAuction\nOfAGivenAuthorUI" as UI
participant ":GetItemsOnAuction\nOfAGivenAuthorController" as CTL
participant "mAR:MemoAuctionRepo" as DSR
participant "auction:Auction" as DS
participant "item:Item" as IT
participant "publication:Publication" as PUB



' --- Dialog ---
Buyer -> UI: I want a list of Items on auction of a given author
activate UI
UI --> Buyer: What is the author's name?
deactivate UI
Buyer -> UI: authorID
activate UI
UI -> CTL: getAuctionItems\nByAuthor(authorID)
activate CTL
CTL -> DSR: getAuctionItems\nByAuthor(authorID)
activate DSR

create "listOfItemsOnAuctionByAuthor: List<Item>" as List
DSR -->> List: <<create>>

loop for each auction in mAR
    DSR -> DS: isByAuthor(authorID)
    activate DS
    DS -> IT: isByAuthor(authorID)
    activate IT
    IT -> PUB: isByAuthor(authorID)
    activate PUB
    PUB --> IT: true
    deactivate PUB
    IT --> DS: true
    deactivate IT
    DS --> DSR: true
    deactivate DS
    DSR -> List: add(auction.getItem())
    activate List
    List --> DSR: true
    deactivate List
end



create "copyOfListOfItemsOnAuctionByAuthor: List<Item>" as Copy
DSR -> Copy: List.copyOf(listOfItemsOnAuctionByAuthor)

'participant "author:Author" as AUT

DSR --> CTL: copyOf\nListOfItemsOnAuctionByAuthor
deactivate DSR
CTL --> UI: copyOf\nListOfItemsOnAuctionByAuthor
deactivate CTL
UI --> Buyer: Here's the list!
deactivate UI

@enduml