@startuml
title "US067 - As a Buyer, I want to use the Web UI to bid on an auction." - REST SD

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox
autonumber

participant ":Client" as Client
participant ":AuctionRestController" as REST
participant ":UserService" as userService
participant ":IUserRepo" as userRepo
participant ":AuctionLinkProvider" as Link
participant ":AuctionService" as Service
participant ":IAuctionRepo" as auctionRepo
participant ":BidFactory" as BidFactory
participant "auction%n():Auction" as Auction
participant ":Bid\nResponseDTOMapper" as Mapper
database DB

' ===== OPTIONS /auctions/{auctionId}/bids =====

Client -> REST : OPTIONS /auctions/{auctionId}/bids { ... }
activate REST

REST -> userService : getUserByEmail(emailString)
activate userService

create "email:Email" as email
userService -->> email : createEmail(emailString)

create "userId:UserId" as userId
userService -->> userId : createUserId(email)

userService -> userRepo : ofIdentity(userId)
activate userRepo
userRepo -> DB : ofIdentity(userId)
activate DB
DB --> userRepo : user
deactivate
userRepo --> userService : user
deactivate userRepo

userService --> REST : user
deactivate userService

create "bidOptions:RepresentationModel<?>" as bidOptions
REST -->> bidOptions : createRepresentationModel()

REST -> Link : getBidLinks(user, auctionId)
activate Link
Link --> REST : _links = List<Link>
deactivate Link

loop for each link in _links
    REST -> bidOptions : add(link)
end

REST --> Client : 200 OK + _links
deactivate REST


' ===== POST /auctions/{auctionId}/bids =====

Client -> REST : POST /auctions/{auctionId}/bids %n(){ DTORequest } + userIdFromHeader
activate REST

create "email2:Email" as email2
REST -->> email2 : createEmail(userIdFromHeader)

create "userId2:UserId" as userId2
REST --> userId2 : createUserId(email2)

create "offerPrice:Price" as offerPrice
REST -->> offerPrice : createPrice(DTORequest.getOfferPrice, currency)

REST -> Service : placeBid(auctionId, userId2, offerPrice)
activate Service

Service -> auctionRepo : ofIdentity(auctionId)
activate auctionRepo
auctionRepo -> DB : ofIdentity(auctionId)
activate DB
DB --> auctionRepo : auction
deactivate DB
auctionRepo --> Service : auction
deactivate auctionRepo

Service -> BidFactory : createBid(userId2, offerPrice)
activate BidFactory
create "bid:Bid" as bid
BidFactory -->> bid : <<create>>
BidFactory --> Service : bid
deactivate BidFactory

Service -> Auction : placeBid(bid)
activate Auction
note right Service: returns auction updated %n() with placed bid
Auction --> Service : auction
deactivate Auction

Service -> auctionRepo : save(auction)
activate auctionRepo
auctionRepo -> DB : save(auction)
activate DB
DB --> auctionRepo : auction
deactivate DB
auctionRepo --> Service : auction
deactivate auctionRepo

Service -> Mapper : toBidResponseDTO(auction, bid)
activate Mapper
Mapper --> Service : BidResponseDTO
deactivate Mapper

Service --> REST : BidResponseDTO
deactivate Service

REST -> Link : addBidLinks(BidResponseDTO)
activate Link
Link --> REST : BidResponseDTO with _links
deactivate Link

REST --> Client : 201 Created + BidResponseDTO
deactivate REST

@enduml