@startuml
'==== Title ====
title "As an Administrator, I want to register an Appraisal Entity, including the list of genres and publication types it can appraisal" SD


'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox
autonumber


' ==== Actor and participants ====
participant ":RegisterNewAppraisalEntityController" as CTL
participant "appraisalEntity:AppraisalEntity" as AE
participant ":IAppraisalEntity\nRepo" as IREPO
participant ":IAppraisalEntity\nSpringDataRepo" as SDREPO
database "DB" as DB

activate CTL
CTL -> AE : identity()
activate AE
AE --> CTL : appraisalEntityId
deactivate AE
CTL -> IREPO: containsOfIdentity\n(appraisalEntityId)
activate IREPO
IREPO -> SDREPO : containsOfIdentity\n(appraisalEntityId.toString())
activate SDREPO
SDREPO -> DB : select
activate DB
DB --> SDREPO : false
deactivate DB
SDREPO --> IREPO : false
deactivate SDREPO
IREPO --> CTL : false
deactivate IREPO

ref over CTL
[[../Register_New_Appraisal_Entity_SD.puml Back to Main Diagram]]
end ref

'deactivate CTL

@enduml