@startuml
title "As a Buyer, I want to get the list of items on auction of a given author" - SD

'==== basic style ====
skinparam monochrome false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ArrowColor #57595BAA

autonumber
autoactivate off
hidefootbox

participant ":GetItemsOnAuctionOfA\nGivenAuthorController" as CTL
participant ":IAuthorRepo" as REPO

activate CTL
CTL -> REPO : findAllKeys()
activate REPO
REPO --> CTL : authorIds
deactivate REPO

ref over CTL
[[../Get_List_Of_Items_on_Auction_Of_Given_Author_SD.puml Back to Main Diagram]]
end ref
@enduml