@startuml
title US002 - "As an administrator, I want to add a publication type to the official type list, %n() so that new publications can be of this type" - Level 3 SD
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---
actor "Administrator" as Admin
participant "UI1:AddPublicationTypeUI" as UI
participant "Ctl1:AddPublicationTypeCtl" as Ctl
participant "I1:IPublicationType" as Interface
participant "mptr %n() :MemoPublicationTypeRepo" as REPO
participant "publicationType %n() :PublicationType" as PUBTYPE
participant "ptf:PublicationTypeFactory" as FACTORY

' --- System dialog ---
Admin -> UI: I want to add a new publication type!
activate "UI"
UI --> Admin: What type would you like to add?
deactivate "UI"
Admin -> UI: publicationTypeName
activate "UI"
UI -> Ctl: addPublicationType %n() (publicationTypeName)
activate "Ctl"
Ctl -> Interface: addPublicationType %n() (publicationTypeName)
activate "Interface"
Interface -> REPO: addPublicationType %n() (publicationTypeName)

    loop for each publicationType in ptr

        activate "REPO"
        REPO -> PUBTYPE: isSamePublicationType %n() (publicationTypeName)
        activate PUBTYPE
        PUBTYPE -> REPO: false
        deactivate PUBTYPE
    end

REPO -> FACTORY: createPublicationType (publicationTypeName)
activate FACTORY
create "publicationTypeName %n() :PublicationType" as instance
FACTORY -> instance: <<Create>>
FACTORY --> REPO: publicationTypeName
deactivate FACTORY
REPO -> REPO: add(publicationTypeName)
REPO --> Ctl: publicationTypeName
deactivate "Interface"
deactivate "REPO"
Ctl --> UI: publicationTypeName
deactivate "Ctl"
UI --> Admin: Publication Type successfully %n() added to the official type list!
deactivate "UI"


@enduml