@startuml
title US002 - "As an administrator, I want to add a publication type to the official type list, %n() so that new publications can be of this type" - SD
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---
actor "Administrator" as Admin
participant "UI:AddPublicationTypeUI" as UI
participant "Ctl:AddPublicationTypeCtl" as Ctl
participant "_ptr:PublicationTypeRepo" as REPO

' --- System dialog ---
Admin -> UI: I want to add a new publication type!
activate "UI"
UI --> Admin: What type would you like to add?
deactivate "UI"
Admin -> UI: Publication Type (typeName)
activate "UI"
UI -> Ctl: addPublicationType (typeName)
activate "Ctl"
Ctl -> REPO: addPublicationType (typeName)
activate "REPO"
REPO -> REPO: publicationTypeExists(typeName)
create "publicationType:PublicationType" as instance
REPO -> instance: createPublicationType(typeName)
activate "instance"
instance --> REPO: type
deactivate "instance"
REPO --> Ctl: type
deactivate "REPO"
Ctl --> UI: True
deactivate "Ctl"
UI --> Admin: Publication Type successfully added to the list!
deactivate "UI"


@enduml