@startuml
title US002 - "As an administrator, I want to add a publication type to the official type list, %n() so that new publications can be of this type" - SSD
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---
actor "Administrator" as Admin
participant ":MiteLovers" as System

' --- System dialog ---
Admin -> System: I want to add a new publication type!
activate "System"
System --> Admin: What type would you like to add?
deactivate "System"
Admin -> System: publicationType
activate "System"
System --> Admin: The new publication type was successfully added to the official type list!
deactivate "System"

@enduml