@startuml
title US002 - "As an administrator, I want to add a publication type to the official type list, %n() so that new publications can be of this type" - Level 3 SD
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---
actor "Administrator" as Admin
participant ":AddPublicationTypeUI" as UI
participant ":AddPublicationTypeCtl" as Ctl
participant "ptr:PublicationTypeRepo" as REPO
participant "publicationType:PublicationType" as PUBTYPE
participant ":PublicationTypeFactory" as FACTORY

' --- System dialog ---
Admin -> UI: I want to add a new publication type!
activate "UI"
UI --> Admin: What type would you like to add?
deactivate "UI"
Admin -> UI: publicationTypeName
activate "UI"
UI -> Ctl: addPublicationType (publicationTypeName)
activate "Ctl"
Ctl -> REPO: addPublicationType (publicationTypeName)

    loop for each publicationType in ptr

        activate "REPO"
        REPO -> PUBTYPE: isSamePublicationType(publicationTypeName)
        activate PUBTYPE
        PUBTYPE -> REPO: false
        deactivate PUBTYPE
    end

REPO -> FACTORY: newPublicationType(publicationTypeName)
activate FACTORY
create "newPublicationType:PublicationType" as instance
FACTORY -> instance: create(publicationTypeName)
FACTORY --> REPO: newPublicationType
deactivate FACTORY
REPO -> REPO: add(newPublicationType)
REPO --> Ctl: newPublicationType
deactivate "REPO"
Ctl --> UI: newPublicationType
deactivate "Ctl"
UI --> Admin: Publication Type successfully added to the official type list!
deactivate "UI"


@enduml