@startuml
'==== basic style ====
hide stereotype
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox

autonumber

title "As a User, in the Web UI, I want to be able to sort the list \nof publications in my library by title, author, type or ISBN/SSN - SD"

' --- Actor and participants ---

actor User
participant ":Frontend" as frontend
participant ":Backend" as backend
participant ":Database" as Database

User -> frontend : show me what I can do
activate frontend
frontend -> backend : OPTIONS /my-library\nX-User-Id: {email}
activate backend

backend --> frontend : available endpoints
deactivate backend
frontend --> User : here is what you can do
deactivate frontend

User -> frontend : I want to access to "My Library"
activate frontend
frontend -> backend : GET /my-library\nX-User-Id: {email}
activate backend

backend -> Database : select
activate Database
Database --> backend : data
deactivate Database

backend --> frontend : 200 OK\nCollectionModel<LibraryItemResponseDTO>\n+ _embedded + _links
deactivate backend
frontend --> User : Items of your library
deactivate frontend

User -> frontend : sort library by title/author/type/ISBN-SSN
activate frontend
frontend -> backend : GET /my-library?sort={field}\nX-User-Id: {email}
activate backend

backend -> Database : select ordered by {field}
activate Database
Database --> backend : sorted data
deactivate Database

backend --> frontend : 200 OK\nCollectionModel<LibraryItemResponseDTO>\n+ _embedded + _links
deactivate backend
frontend --> User : sorted items of your library
deactivate frontend

@enduml
