@startuml
'==== Title ====
title "As a Buyer, I want to use the Web UI to bid on an auction." - SD

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox
autonumber

' ==== Actor and participants ====
actor User
participant ":Client" as Client
participant ":Server" as Server

User -> Client : I would like to know %n() what I can do in %n() regard to an existing %n()auction
activate Client
Client -> Server : OPTIONS /auctions/{auctionId} { ... }
activate Server

ref over Server
[[rest-sd-ref-diagrams/OPTIONS_Place_Bid_SD.puml OPTIONS for user on /auctions/{auctionId}]]
end ref

Server --> Client : 200 OK + _links
deactivate Server
Client --> User : display HATEOAS %n() links
deactivate Client

User -> Client : I want to place a %n() bid on this auction
activate Client
Client -> Server : POST /auctions/{auctionId}/bids %n(){ placeBidRequestDTO } + %n()userIdFromHeader
activate Server

ref over Server
[[rest-sd-ref-diagrams/POST_Place_Bid_SD.puml POST (place bid on auction)]]
end ref

Server --> Client : 201 Created + bidResponseDTO
deactivate Server
Client --> User : Bid successfully %n() placed.
deactivate Client

@enduml