@startuml
title US006 – "As an Administrator, I want to register a Publishing Company in the system" %n() SD
hide footbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---
actor "Admin" as Administrator
participant "UI1:RegisterPublisherUI" as UI
note over "UI": not implementing UI now; %n() placeholder for tests
participant "Ctl1:RegisterPublisherController" as Ctl
participant "_pr:PublisherRepo" as Repo

' --- SD (Happy Path only)---

Administrator -> "UI": I want to register a publishing company.
activate "UI"
"UI" --> Administrator:Name of the publishing company?
Administrator -> "UI": publisherName
"UI" -> "Ctl": registerPublisher(publisherName)
activate "Ctl"
"Ctl" -> "Repo": registerPublisher(publisherName)
activate "Repo"
"Repo" -> "Repo": publisherExists(publisherName)
note right of "Repo": happy path (publisherExists returns false)
create "p1:Publisher"
"Repo" -> "p1:Publisher": create(publisherName)
note right of "Repo": create() instantiates new %n()Publisher via its constructor
"Repo" -> "Repo": add(p1);
note right of "Repo": add() represents _publishers.add() %n()(built-in List method)
"Repo" --> "Ctl": p1
deactivate "Repo"
"Ctl" --> "UI": p1
note right of "UI" : DTO preferred; returning p1 for %n()deadline of this sprint; in future will %n()implement DTO for best practice
deactivate "Ctl"
"UI" --> Administrator: Registered successfully!
deactivate "UI"

@enduml