@startuml
title US006 – "As an Administrator, I want to register a Publishing Company in the system" %n() SD
hide footbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---
actor "Admin" as Administrator
participant ":RegisterPublishingCompanyUI" as UI
participant ":RegisterPublishingCompanyController" as Ctl
participant ":PublishingCompanyRepo" as Repo
participant ":PublishingCompanyFactory" as Factory

' --- SD (Happy Path only)---

Administrator -> "UI": I want to register a publishing company.
activate "UI"
"UI" --> Administrator:Name of the publishing company?
Administrator -> "UI": publishingCompanyName
"UI" -> "Ctl": registerPublishingCompany(publishingCompanyName)
activate "Ctl"
"Ctl" -> "Repo": registerPublishingCompany(publishingCompanyName)
activate "Repo"

opt publishingCompanyExists(publishingCompanyName) == false
        "Repo" -> "Factory" : createPublishingCompany(publishingCompanyName)
        activate "Factory"
        create "pc1:PublishingCompany"
        "Factory" -> "pc1:PublishingCompany": create(publishingCompanyName)
        "Factory" --> "Repo": pc1
        deactivate "Factory"
        "Repo" -> "Repo": add(pc1);
        end

"Repo" --> "Ctl": pc1
deactivate "Repo"
"Ctl" --> "UI": pc1
deactivate "Ctl"
"UI" --> Administrator: Registered successfully!
deactivate "UI"

@enduml