@startuml
'https://plantuml.com/sequence-diagram
'==== basic style ====

'hides unwanted text
hide stereotype

skinparam monochrome false

skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ArrowColor #57595BAA

'undefined objects
skinparam object {
  BackgroundColor<<highlight>> 91C6BCAA
  BorderColor<<highlight>> 4B9DA9AA
  FontColor<<highlight>> 547792AA
}
skinparam shadowing<<highlight>> false


title "As a Buyer, I want to get the list of items on auction of a given publisher" - SSD

actor User
participant ": Mitelovers"

hidefootbox

User -> ": Mitelovers" : I want to get the list of items on auction of a given publisher
activate ": Mitelovers"
": Mitelovers" --> User : Select publishingCompanyId
deactivate ": Mitelovers"
User -> ": Mitelovers" : publishingCompanyId
activate ": Mitelovers"
": Mitelovers" --> User : Here's the list of items! Done!
deactivate ": Mitelovers"


@enduml
