@startuml
title "As a Buyer, I want to get the list of items on auction of a given publisher" - SD
hidefootbox

skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam ArrowFontColor #3B4953

autonumber
autoactivate off

actor Buyer
participant ":GetAuctionItemsByPublishingCompanyUI" as UI
participant ":GetAuctionItemsByPublishingCompanyController" as CTL

participant "edition:Edition" as Edition


Buyer -> UI: I want the list of items \non auction of a given publishing company
activate UI
UI -> CTL : findAllKeys()
activate CTL
ref over CTL
[[sd-ref-diagrams/Get_Publishing_Company_Id.puml Get All Publications Ids]]
end ref

CTL --> UI : publishingCompanyIds
deactivate CTL
UI --> Buyer: Select publishingCompanyId
deactivate UI
Buyer -> UI: publishingCompanyId
activate UI


UI -> CTL: getAuctionItemsByPublishingCompanyId(publishingCompanyId)
activate CTL
ref over CTL
[[sd-ref-diagrams/Get_Auction.puml Get Auctions]]
end ref

create "listOfItemsOnAuctionByPublishingCompany:List<ItemId>"
CTL -->> "listOfItemsOnAuctionByPublishingCompany:List<ItemId>" : <<Create>>

loop for auction : auctions
ref over CTL
[[sd-ref-diagrams/Get_Item_Id.puml Get Items Id]]
end ref

loop for itemId : itemIds
ref over CTL
[[sd-ref-diagrams/Get_Item.puml Get Item]]
end ref

ref over CTL
[[sd-ref-diagrams/Get_Edition_Id.puml Get Edition Id]]
end ref

ref over CTL
[[sd-ref-diagrams/Get_Edition.puml Get Edition]]
end ref

CTL -> Edition : hasPublishingCompanyId = isByPublishingCompanyId(publishingCompanyId)

opt hasPublishingCompanyId
CTL -> "listOfItemsOnAuctionByPublishingCompany:List<ItemId>" : add(itemId)
activate "listOfItemsOnAuctionByPublishingCompany:List<ItemId>"
"listOfItemsOnAuctionByPublishingCompany:List<ItemId>" --> CTL : true
deactivate "listOfItemsOnAuctionByPublishingCompany:List<ItemId>"
end
end
end


CTL --> UI: listOfItemsOnAuctionByPublishingCompany
deactivate CTL

UI --> Buyer: Here's the list! Done!
deactivate UI

@enduml@startuml
'https://plantuml.com/sequence-diagram

autonumber
title US028 "As a Buyer, I want to get the list of items on auction of a given publisher" - SD

hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---'
actor Buyer
participant ":GetAuctionItems\nByPublisherUI" as UI
participant ":GetAuctionItems\nByPublisherController" as Ctl
participant ":MemoAuctionRepo" as MemoRepo
participant "_auction:Auction" as auction

' --- Initial UI interaction ---'
Buyer -> UI:  I want to get the list of items\n on auction of a given publisher
activate UI
UI --> Buyer: What is the publisher?
deactivate UI
Buyer -> UI: publisherId
activate UI

' --- Get auction items ---'
UI -> Ctl: getAuctionItems\nByPublisherId(publisherId)
activate Ctl
Ctl -> MemoRepo: getAuctionItems\nByPublisherId(publisherId)
activate MemoRepo

'--- Loop through items and select by Publisher ---'
create "listOfAuctionItemsId\nByPublisherId: List<ItemId>" as List
MemoRepo -->> List : <<create>>
loop for each Auction in MemoAuctionRepo
     MemoRepo -> auction: isByPublisherId(publisherId)
    opt isByPublisher == true
        MemoRepo -> List: add(auction.getItemId\())
        activate List
        List --> MemoRepo :true
        Deactivate List
    end
end

'--- Make a copy of the list of selected items ---'
create "copyListOfAuctionItemsId\nByPublisherId: List<ItemId>" as Copy
MemoRepo -->> Copy : <<create>>
MemoRepo --> Ctl : copyListOfAuctionItems\nByPublisherId
deactivate MemoRepo
Ctl --> UI: copyListOfAuctionItems\nByPublisherId
deactivate Ctl

'--- Response ---'
UI --> Buyer: Here's the list!
deactivate UI

@enduml
