@startuml
title "As a user, I want to publicly share a List of mine" CD
top to bottom direction

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0

class ShareListPubliclyUI

package "controller" {
    class ShareListPubliclyController {
        + findListsByUser(userId : UserId) : Map<ListOfItemsId, String>
        + shareListPublicly(listOfItemsId : ListOfItemsId) : boolean
        + shareListPublicly(listOfItemsId : ListOfItemsId, duration : SharedDuration) : boolean
    }
}

package "domain" {

    package "listofitems" #b0c4d4 {
        class ListOfItems <<Root>> <<Entity>> {
            - _isPrivate : boolean
            + getUserId() : UserId
            + getName() : Name
            + getGenreId() : GenreId
            + getItemIds() : List<ItemId>
            + makePublic() : void
            + isPrivate() : boolean
            - _sharedUntil : LocalDateTime
            + makePublic(duration : SharedDuration) : void
            + getSharedUntil() : LocalDateTime
        }
    }

    package "repository" {
        interface IListOfItemsRepo <<Interface>> {
        }
    }

    package "valueobject" {
        class ListOfItemsId <<ValueObject>> #LightPink {}
        class UserId <<ValueObject>> {}
        class ItemId <<ValueObject>> {}
        class Name <<ValueObject>> {}
        class GenreId <<ValueObject>> {}
        class SharedDuration <<ValueObject>> {}
    }
}

package "ddd" {
    interface IRepository<ID, T> <<Interface>> {
        +save(entity : T) : T
        +findAll() : Iterable<T>
        +findAllKeys() : List<ID>
        +ofIdentity(id : ID) : Optional<T>
        +containsOfIdentity(id : ID) : boolean
    }
    interface DomainEntity<ID> <<Interface>> {
        +identity() : ID
        +sameAs(object : Object) : boolean
    }
    interface AggregateRoot<ID> <<Interface>> {}
}

ShareListPubliclyUI "1" ..> "1" ShareListPubliclyController : invokes
ShareListPubliclyController "1" ..> "1" IListOfItemsRepo : «use»

IListOfItemsRepo --|> IRepository
IListOfItemsRepo "1" -> "*" ListOfItems : persists

ListOfItems "1" --> "1" ListOfItemsId : has
ListOfItems "1" --> "1" Name : has
ListOfItems "*" --> "1" UserId : references
ListOfItems "*" --> "*" ItemId : references
ListOfItems "*" --> "1" GenreId : references
ListOfItems "*" --> "1" SharedDuration : references


ListOfItems .|> AggregateRoot
AggregateRoot --|> DomainEntity

@enduml