@startuml
'https://plantuml.com/class-diagram
title "As a user, I want to publicly share a List of mine.

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0

class ShareListPubliclyUI

class ShareListPubliclyController {
    - _listOfPublicationsRepo : IListOfPublicationsRepo
    + findListsByUser(userId : UserId) : List<ListOfPublications>
    + shareListPublicly(myList : ListOfPublications) : boolean
}

interface IListOfPublicationsRepo {

}

class MemoListOfPublicationsRepo {
    - _listsOfListOfPublications : List<ListOfPublications>

}

class ListOfPublications {
    - _name : String
    - _user : User
    - _items : List<Item>
    - _isPrivate : Boolean
    + makePublic() : void
    + getItems() : List<Item>
}

"ShareListPubliclyUI" "1" --> "1" "ShareListPubliclyController" : request
"ShareListPubliclyController" "1" --> "1" "IListOfPublicationsRepo" : uses
"IListOfPublicationsRepo" "1" --> "1" "ListOfPublications" : stores
IListOfPublicationsRepo <|.. MemoListOfPublicationsRepo

@enduml