@startuml
title "As a user, I want to publicly share a List of mine" SD
hide footbox

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

actor "User"
participant ":ShareListPubliclyUI" as UI
participant ":ShareListPubliclyController" as Ctl
participant ":IListOfItemsRepo" as IListRepo

"User" -> UI : I want to publicly share one of my lists
activate UI

UI -> Ctl : findListsByUser(userId)
activate Ctl
Ctl -> IListRepo : findListsByUserId(userId)
activate IListRepo
IListRepo --> Ctl : Map<ListOfItemsId, String>
deactivate IListRepo
Ctl --> UI : Map<ListOfItemsId, String>
deactivate Ctl

UI --> "User" : What list do you want to share?
deactivate UI
"User" -> UI : listOfItemsId
activate UI

UI -> Ctl : shareListPublicly(listOfItemsId)
activate Ctl

Ctl -> IListRepo : ofIdentity(listOfItemsId)
activate IListRepo
IListRepo --> Ctl : list
deactivate IListRepo

Ctl -> "list:ListOfItems" : makePublic()
activate "list:ListOfItems"
deactivate "list:ListOfItems"

Ctl -> IListRepo : save(list)

ref over IListRepo
[[sd-ref-diagrams/Save_ListOfItems.puml Save list and return saved domain object]]
end ref

activate IListRepo
IListRepo --> Ctl : savedList
deactivate IListRepo

Ctl --> UI : true
deactivate Ctl
UI --> "User" : List is now public!
deactivate UI

@enduml