@startuml
title US021 – "As a Buyer, I want to get the list of items on direct sale of a given genre" - Sequence Diagram
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

actor Buyer
participant ":UIListDirectSaleItemsByGenre" as UI
participant ":GetDirectSaleItemsByGenreController" as CTL
participant ":DirectSaleRepository" as DSR
participant ":DirectSale" as DS
participant ":Item" as Itm
participant ":Publication" as Pub

'-- Dialog --'

activate Buyer
Buyer -> UI : I want the list of items, in direct sale,\nof a given genre
activate UI

UI --> Buyer : What is the genre?
Buyer -> UI : The genre is genre

'-- System interaction --'

UI -> CTL : getDirectSaleItemsByGenre(genre)
activate CTL

CTL -> DSR : getDirectSaleItemsByGenre(genre)
activate DSR

loop for each DirectSale
    DSR -> DS : getItem()
    activate DS

    DS -> Itm : getPublication()
    activate Itm

    Itm -> Pub : matchGenre(genre)
    activate Pub

    opt publication.matchGenre(genre)
        DSR -> DSR : add Item to result list
    end

    deactivate Pub
    deactivate Itm
    deactivate DS
end

DSR --> CTL : List<Item>
deactivate DSR

CTL --> UI : List<Item>
deactivate CTL

UI --> Buyer : show items
deactivate UI
deactivate Buyer

@enduml