@startuml
title "As a Buyer, I want to get the list of items on direct sale of a given genre" SD
hidefootbox

skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam ArrowFontColor #3B4953

autonumber
autoactivate off

actor Buyer
participant ":GetDirectSaleItemsByGenreUI" as UI
participant ":GetDirectSaleItemsByGenreController" as CTL
participant ":IGenreRepo" as AR
participant ":IDirectSaleRepo" as DSR
participant "directSale:DirectSale" as DS
participant ":IItemRepo" as IR
participant "item:Item" as Item
participant ":IEditionRepo" as ER
participant "edition:Edition" as Edition
participant ":IPublicationRepo" as PR
participant "publication:Publication" as Publication


Buyer -> UI: I want the list of items on direct sale of a given genre
activate UI
UI -> CTL : findAllKeys()
activate CTL
CTL -> AR : findAllKeys()
activate AR

AR --> CTL : genreIds
deactivate AR

CTL --> UI : genreIds
deactivate CTL
UI --> Buyer: Select author
deactivate UI
Buyer -> UI: genreId
activate UI


UI -> CTL: getDirectSaleItemsByGenreId(genreId)
activate CTL

CTL -> DSR: findAll()
activate DSR

DSR --> CTL: Collection<DirectSale>
deactivate DSR

create "itemsOnDSofGivenGenre:List<ItemId>"
CTL -->> "itemsOnDSofGivenGenre:List<ItemId>" : <<Create>>

loop for directSale : Collection<DirectSale>
CTL -> DS : getItemIds()
activate DS
DS --> CTL : List<ItemId>
deactivate DS

loop for itemId : List<ItemId>
CTL -> IR : ofIdentity(itemId)
activate IR
IR --> CTL : item
deactivate IR
CTL -> Item : getEditionId()
activate Item
Item --> CTL : editionId
deactivate Item

CTL -> ER : ofIdentity(editionId)
activate ER
ER --> CTL : edition
deactivate ER
CTL -> Edition : getPublicationId()
activate Edition
Edition --> CTL : publicationId
deactivate Edition

CTL -> PR : ofIdentity(publicationId)
activate PR
PR --> CTL : publication
deactivate PR

CTL -> Publication : hasAuthor = isByGenre(genreId)

opt hasAuthor
CTL -> "itemsOnDSofGivenGenre:List<ItemId>" : add(itemId)
activate "itemsOnDSofGivenGenre:List<ItemId>"
"itemsOnDSofGivenGenre:List<ItemId>" --> CTL : true
deactivate "itemsOnDSofGivenGenre:List<ItemId>"
end
end
end


CTL --> UI: itemsOnDSofGivenGenre
deactivate CTL

UI --> Buyer: Here's the list! Done!
deactivate UI

@enduml