@startuml
'https://plantuml.com/class-diagram

title Auction Aggregate

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0


package domain {

    package auction #b0c4d4 {

        class Auction <<Entity>> <<Root>> {
            -ZonedDateTime _auctionStartDate;
            -ZonedDateTime _auctionEndDate;
            +getItemsId() : List<ItemId>
            +getBids() : List<Bid>
            +getStartingPrice() : Price
            +getOutrightPrice() : Price
            +finalizeAuction() : void
            -isAuctionStartDateValid(auctionStartDate : ZoneDateTime) : boolean
            -isOutrightPriceValid(outrightPrice : Price) : boolean
            -isReservePriceValid(reservePrice : Price) : boolean
            -isReserveMet (price : Price) : boolean
            -isAuctionEndDateValid(auctionEndDate : ZoneDateTime) : boolean
            +placeBid (userId : UserId, offerPrice : Price) : Bid
            +getHighestBid() : Bid
            -getSeller() : UserId
        }

        class Bid <<Entity>> {
            -Instant _BidDate
            +getUserId() : UserId
            +getOfferPrice() : Price
            +getBidDate() : Instant
            -validateBidder(UserId) : void
            -validateOfferPrice(UserId) : void
        }

        class BidFactory <<Factory>> {
            + createBid(userId : UserId, offerPrice : Price) : Bid
        }

        class AuctionFactory <<Factory>> {
            + createAuction(itemId : ItemId , startingPrice : Price, reservePrice : Price %n()  auctionStartDate : ZonedDateTime, auctionEndDate : ZonedDateTime) : Auction
            + createAuction(itemId : ItemId , startingPrice : Price, reservePrice : Price, outrightPrice : Price, %n()  auctionStartDate : ZonedDateTime, auctionEndDate : ZonedDateTime) : Auction
        }

    }

    package repository {

        interface IAuctionRepo {
       }
    }

    package valueobject {
        class AuctionId <<ValueObject>> #LightPink {
            _id : String
        }
        class BidId <<ValueObject>> #LightPink {
                    _id : UUID
                }
        class Price <<ValueObject>>
        class ItemId <<ValueObject>>
        class UserId <<ValueObject>>
    }
}


package ddd {
    interface IRepository<ID, T> <<Interface>> {
        +save(entity : T) : T
        +findAll() : Iterable<T>
        +findAllKeys() : List<ID>
        +ofIdentity(id : ID) : Optional <T>
        +containsOfIdentity(id : ID) : boolean
    }

    interface AggregateRoot<ID, T> <<Interface>>

    interface DomainEntity<ID> <<Interface>>{
        +identity() : T
        +sameAs(object : Object) : boolean
    }
}

IAuctionRepo "1" --> "*" Auction : manages
IAuctionRepo --|> IRepository
AggregateRoot --|> DomainEntity
AuctionFactory "1" ..> "*" Auction : <<create>>
Auction "1" *---- "*" Bid : aggregates
Auction --|> AggregateRoot
BidFactory "1" ..> "*" Bid : <<create>>
Auction "1" --> "1" AuctionId : has
Auction "*" ..> "1..2" UserId : references
Auction "1" o-- "1..*" ItemId : has
Auction "*" --> "1" Price : has
Auction ..> BidFactory : <<use>>
Bid "*" --> "1" Price : has
Bid "*" ..> "1" UserId : references
Bid -|> DomainEntity
Bid "1" --> "1" BidId : has

@enduml
