@startuml
'https://plantuml.com/class-diagram

title Auction Aggregate

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0


package DOMAIN {

    package AUCTION #b0c4d4 {

        class Auction <<Entity>> <<Root>> {
            -ZonedDateTime _auctionStartDate;
            -ZonedDateTime _auctionEndDate;
            +placeBid (userId : UserId, price : Price) : Bid
            +getHighestBid() : Bid
            +acceptBid(Bid : Bid) : void
            +finalizeAuction() : void
            +getItemsId() : ItemId
            +getBid() : Bid
            +getStartingPrice()
            +getOutrightPrice()
            +isByGenreId(genreId : GenreId) : boolean
            +isByAuthorId(authorId : AuthorId) : boolean
            +isByPublicationId(publicationId : PublicationId) : boolean
            +isByPublishingCompanyId(publisherId : PublishingCompanyId) : boolean
            -isAuctionStartDateValid(date : ZoneDateTime) : boolean
            -isAuctionEndDateValid(date : ZoneDateTime) : boolean
            -isOutrightPriceValid(price : Price) : boolean
            -isReservePriceValid(reservePrice : Price) : boolean
            -isReserveMet (price : Price) : boolean
        }

        class Bid <<Entity>> {
            -Instant _BidDate
            +getBidder()
            +getOfferPrice()
            +getBidDate()
            -validateBidder(UserId)
            -validateOfferPrice(UserId)
        }

        class BidFactory {
            + createBid(bidderId : UserId, offerPrice : Price) : Bid
        }

        class AuctionFactory {
            + createAuction(auctionId : AuctionId, itemId : ItemId , startingPrice : Price, reservePrice : Price %n()  auctionStartDate : ZonedDateTime, auctionEndDate : ZonedDateTime) : Auction
            + createAuction(auctionId : AuctionId, itemId : ItemId , startingPrice : Price, reservePrice : Price, outrightPrice : Price, %n()  auctionStartDate : ZonedDateTime, auctionEndDate : ZonedDateTime) : Auction
        }

    }

    package REPOSITORY {

        interface IAuctionRepo {
            createAuction(auctionId : AuctionId, itemId : ItemId , startingPrice : Price, reservePrice : Price, %n() outrightPrice : Price, auctionStartDate : ZonedDateTime, auctionEndDate : ZonedDateTime) : Auction
            createAuction(auctionId : AuctionId, itemId : ItemId , startingPrice : Price, reservePrice : Price, auctionStartDate : ZonedDateTime, %n() auctionEndDate : ZonedDateTime) : Auction
            getAuctionItemsByGenreId(genreId : GenreId) :  List<ItemId>
            getAuctionItemsByAuthorId(authorId : AuthorId) :  List<ItemId>
            getAuctionItemsByPublicationId(publicationId : PublicationId):  List<ItemId>
            getAuctionItemsByPublishingCompanyId(publisherId : PublishingCompanyId ):  List<ItemId>
        }
    }

    package VALUEOBJECT {
        class AuctionId <<ValueObject>> #LightPink {
            _id : UUID
            +createId() : AuctionId
        }
        class Price <<ValueObject>>
        class ItemId <<ValueObject>>
        class UserId <<ValueObject>>
        class GenreId <<ValueObject>>
        class AuthorId <<ValueObject>>
        class PublicationId <<ValueObject>>
        class PublishingCompanyId <<ValueObject>>
    }
}

package PERSISTENCE {

    package MEM {
        class MemoAuctionRepo <<Repo>>
    }
}

package DDD {
    interface IRepository<ID, T> <<Interface>> {
        +save(T) : T
        +findAll() : Iterable<T>
        +ofIdentity(ID) : Optional<T>
        +containsOfIdentity(ID) : boolean
    }
}

MemoAuctionRepo ..|> IAuctionRepo
IAuctionRepo "1" --> "*" Auction : manages
IAuctionRepo --|> IRepository
AuctionFactory "1" ..> "*" Auction : <<create>>
Auction "1" *---- "*" Bid : aggregates
BidFactory "1" ...> "*" Bid : <<create>>
MemoAuctionRepo "1" --> "*" Auction : persists
Auction "1" --> "1" AuctionId : has
Auction "*" --> "1" UserId : has
Auction "*" o-- "1..*" ItemId : has
Auction "*" --> "1" Price : has
Auction "*" .> "1..*" GenreId : references
Auction "*" .> "*" AuthorId : references
Auction "*" .> "1..*" PublicationId : references
Auction "*" .> "1..*" PublishingCompanyId : references
Bid "*" ...> "1" Price : references
Bid "*" ....> "1" UserId : references

@enduml