@startuml

'==== Title ====
title City Aggregate
top to bottom direction

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0

' ===== Persistence =====
Package "PERSISTENCE" {
    class MemoCityRepo <<Repo>> {
        - _cities : List<City>
        + save(City) : City
        + findAll() : Iterable<City>
        + ofIdentity(CityId) : Optional<City>
        + containsOfIdentity(CityId) : boolean
    }
}

' ===== Domain =====
Package "DOMAIN" {

    Package "CITY" <<Folder>> #b0c4d4 {

        class City <<Entity>> <<Root>> #lightgrey {
            - _name : String
            + identity() : CityId
            + sameAs(Object) : boolean
            + getName() : String
            + getCountry() : Country
            + toString() : String
        }

        class CityFactory <<Factory>> {
            + createCity(String, Country) : City
        }

    }

    Package "VALUEOBJECT" {

        class CityId <<DomainId>> #LightPink {
            - _normalizedName : String
            + getNormalizedName() : String
            + getCountryId() : CountryId
            + equals(Object) : boolean
            + hashCode() : int
            + toString() : String
        }

        class CountryId <<DomainId>> #LightPink {
            - _code : String
            + equals(Object) : boolean
            + hashCode() : int
            + toString() : String
        }

    }

    Package "REPOSITORY" <<Folder>> #d4c4b0 {
        interface ICityRepo <<Interface>>
    }

}

' ===== Cross-aggregate reference =====
class Country <<AggregateRoot>> #LightGray {
    + identity() : CountryId
    + getCountryName() : String
}

' ===== Relations =====
City "1" --> "ID 1" CityId : has
CityId "1" --> "1" CountryId : identified by

City ..> Country : references

ICityRepo "1" --> "*" City : manages
MemoCityRepo ..|> ICityRepo

CityFactory ..> City : <<create>>

@enduml