@startuml

title Country Aggregate

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0

top to bottom direction

Package "domain" {

    Package "country" <<Folder>> #b0c4d4 {
        class Country <<Entity>> <<Root>> {
            +identity() : CountryId
            +name() : CountryName
            +sameAs(Object) : boolean
        }

        class CountryFactory <<Factory>> {
            +createCountry(String countryName) : Country
        }
    }

    Package "valueobject" <<Folder>> {
        class CountryId <<ValueObject>> #LightPink {
        }

        class CountryName <<ValueObject>> {
        }
    }

    Package "repository" <<Folder>> {
        interface ICountryRepo <<Interface>> {
            +addCountry(String) : Country
        }
    }

    ' Layout adjustments
    country -[hidden]right- REPOSITORY
    valueobject -[hidden]right- repository
    country -[hidden]down- valueobject
}

Package "ddd" {
    interface "IRepository<ID, T>" as IRepository <<Interface>> {
        +save(entity: T) : T
        +findAll() : Iterable<T>
        +ofIdentity(id: ID) : Optional<T>
        +containsOfIdentity(id: ID) : boolean
        +findAllKeys() : List<ID>
    }

    interface AggregateRoot <ID >{
    }

    interface DomainEntity<ID, T> <<Interface>> {
        +identity() : ID
        +sameAs(Object) : boolean
    }
}

Package "persistence" {
    package "mem" {
        class MemoCountryRepo <<Repo>> {
        }
    }
}

' ===== Relations =====

CountryFactory "1" <-- "1" MemoCountryRepo : invokes
Country "1" ..> "1" CountryId : references
Country "1" --> "1" CountryName : has

ICountryRepo -|> IRepository
MemoCountryRepo ..|> ICountryRepo
Country "*" <- "1" MemoCountryRepo : persists

CountryFactory ..> Country : <<create>>

AggregateRoot -|> DomainEntity
Country .|> AggregateRoot


@enduml