@startuml

title Genre Aggregate - Persistence Refactoring

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0

top to bottom direction

Package "domain" {
    Package "genre" <<Folder>> #b0c4d4 {
        class Genre <<Entity>> <<Root>>  {
            -_genre : String
            +identity() : GenreId
        }
        class GenreFactory <<Factory>> {
            +createGenre(name : String) : Genre
        }
    }

    Package "valueobject" <<Folder>> {
        class GenreId <<ValueObject>> #LightPink {
            -_id : String
        }
    }

    Package "repository" <<Folder>> {
        interface IGenreRepo <<Interface>>
    }
}

Package "persistence" {
    package "mem" {
        class MemGenreRepo <<Repo>> #GhostWhite
    }

    package "jpa" #GhostWhite {
        class JpaGenreRepo <<Repo>> {
            -_iGenreSpringDataRepo : IGenreSpringDataRepo
            -_genreAssembler : GenreAssembler
        }

        package "datamodel" {
            class GenreDataModel <<Entity>> {
                -id : String
                -name : String
            }
        }

        package "assembler" {
            class GenreAssembler <<Component>> {
                +domain2DM(Genre) : GenreDataModel
                +DM2Domain(GenreDataModel) : Genre
            }
        }

        package "springdata" {
            interface IGenreSpringDataRepo <<Interface>> {
            }
        }
    }
}

Package "ddd" {
    interface IRepository<ID, T>
    interface AggregateRoot<ID>
}

' Relationships
Genre "1" --> "1" GenreId : has
IGenreRepo -|> IRepository
MemGenreRepo .|> IGenreRepo
JpaGenreRepo .|> IGenreRepo

' The JPA Bridge
JpaGenreRepo --> IGenreSpringDataRepo : uses
JpaGenreRepo --> GenreAssembler : uses
GenreAssembler ..> GenreDataModel : maps
GenreAssembler --> GenreFactory : uses

GenreFactory ..> Genre : <<create>>
Genre .|> AggregateRoot

@enduml