@startuml

title Genre Aggregate

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0

top to bottom direction

Package "DOMAIN" {

    Package "GENRE" <<Folder>> #b0c4d4 {
        class Genre <<Entity>> <<Root>>  {
            -_genre : String
            +getGenre() : String
            +identity() : GenreId
            +sameAs(Object) : boolean
            +equals(Object) : boolean
            +hashCode() : int
            +toString() : String
        }

        class GenreFactory <<Factory>> {
            +createGenre(name : String) : Genre
            '+createGenre(genreID: GenreID , name : String) : Genre'
        }
    }

    Package "VALUEOBJECT" <<Folder>> {
        class GenreId <<ValueObject>> #LightPink {
            -_id : String
        }
    }

    Package "REPOSITORY" <<Folder>> {
        interface IGenreRepo <<Interface>> {
            +addGenre(name : String) : Genre
        }
    }
}

Package "DDD" {
    interface IRepository<ID, T> <<Interface>> {
        +save(entity: T) : T
        +findAll() : Iterable<T>
        +ofIdentity(id :ID) : Optional<T>
        +containsOfIdentity(id :ID) : boolean
    }
}

Package "PERSISTENCE" {
    package "MEM" {
        class MemoGenreRepo <<Repo>> {
        }
    }
}

GenreFactory "1" <-- "1" MemoGenreRepo : invokes
Genre "1" --> "1" GenreId : has
IGenreRepo -|> IRepository
MemoGenreRepo ...|> IGenreRepo
Genre "*" <-- "1" MemoGenreRepo : persists

GenreFactory ..> Genre : <<create>>

@enduml