@startuml
title Item Aggregate

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0
skinparam packageTitleBackgroundColor #F0F8FF

skinparam package {
  BackgroundColor #F6F0D8
  BorderColor #4F4F4F
  FontColor #222222
}

skinparam class {
  BackgroundColor #F2F2F2
  BorderColor #666666
  FontColor #222222
  ArrowColor #666666
}

skinparam interface {
  BackgroundColor #F2F2F2
  BorderColor #666666
  FontColor #222222
  ArrowColor #666666
}


package "domain" {

  package "repository" {
    interface IItemRepo <<Interface>> {
    }
  }

  package "item" #AFC4D6 {

    class ItemFactory <<Factory>> {
      +createItem(editionID : EditionID, condition : %n()Condition, description : Description) : Item
      +createItem(itemId : ItemId, editionID : EditionID, %n()condition : Condition, description : Description, saleStatus : %n()SaleStatus) : Item
    }

    class Item <<Root>> <<Entity>> {
      +markAsAuction() : void
      +markAsDirectSale() : void
      +markAsSold() : void
      -ensureNotOnSale() : void
      +getEditionID() : EditionID
      +getCondition() : Condition
      +getSaleStatus() : SaleStatus
      +getDescription() : Description
    }
  }

  package "valueobject" {
    class Condition <<ValueObject>>
    class Description <<ValueObject>>
    class EditionID <<ValueObject>>
    class ItemID <<ValueObject>> #LightPink {

    - _id : SKU
    }
    class SaleStatus <<ValueObject>>

  }
}

package ddd {
    interface IRepository<ID, T> <<Interface>> {
        +save(entity : T) : T
        +findAllKeys() : Iterable<ID>
        +findAll() : Iterable<T>
        +ofIdentity(id : ID) : Optional<T>
        +containsOfIdentity(id : ID) : boolean
    }
    interface AggregateRoot <ID >{
        }
    interface DomainEntity<ID, T> <<Interface>> {
         +identity() : ID
         +sameAs(object : Object) : boolean
        }
}


ItemFactory "1" ..> "*" Item : <<create>>

Item "*" --> "1" Condition : has
Item "1" --> "1" Description : has
Item "1" --> "1" EditionID : references
Item "1" *-- "1" ItemID : has
Item "1" --> "1" SaleStatus : has

IItemRepo --|> IRepository
IItemRepo "1" --> "*" Item : persists
AggregateRoot -|> DomainEntity
Item .|> AggregateRoot

@enduml