@startuml
'https://plantuml.com/class-diagram
title PublicationType Aggregate DDD

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0

top to bottom direction

package "persistence" {

    package "mem" {

        class MemoPublicationTypeRepo <<Repo>> {

        }

    }
}

package "domain" {

    package "repository" {

        interface IPublicationTypeRepo <<Interface>> {
        + addPublicationType(publicationTypeName : String) : PublicationType
        }

    }

    package "valueobject" {
        class PublicationTypeId <<Value Object>> #LightPink {
        - _id : String
        }
    }

    package "publicationtype" #b0c4d4 {

        class PublicationType <<Root>> <<Entity>> {
        }

        class PublicationTypeFactory <<Factory>> {
        + createPublicationType(publicationTypeName : String) : PublicationType

        }

    }

}

Package "ddd" {
    interface IRepository<ID, T> <<Interface>> {
        +save(entity: T) : T
        +findAll() : Iterable<T>
        +ofIdentity(id: ID) : Optional<T>
        +containsOfIdentity(id: ID) : boolean
        +findAllKeys() : List<ID>
    }

    interface AggregateRoot <ID >{
    }

    interface DomainEntity<ID, T> <<Interface>> {
        +identity() : ID
        +sameAs(object : Object) : boolean
    }
}


MemoPublicationTypeRepo ..|> IPublicationTypeRepo
IPublicationTypeRepo --|> IRepository
MemoPublicationTypeRepo "1" --> "1" PublicationTypeFactory : invokes

MemoPublicationTypeRepo "1" --> "*" PublicationType : persists

PublicationType "1" --> "1" PublicationTypeId: has

PublicationTypeFactory "1" ..> "*" PublicationType: <<create>>
AggregateRoot -|> DomainEntity
PublicationType .|> AggregateRoot

@enduml