@startuml

'==== Title ====
title Publication Aggregate


'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0

top to bottom direction
' ===== Domain =====
Package "domain" {

    Package "publication" #b0c4d4 {

        class Publication <<Root>> <<Entity>> {
            -_releaseYear : Year
            +isByAuthorId( a : AuthorId) : boolean
            +isByGenreId(g : GenreId) : boolean
            +identity() : PublicationId
            +sameAs(Object) : boolean
        }

        class PublicationFactory <<Factory>> {
            +createPublication(t : Title, a : AuthorId, y : Year, gId: GenreId) : Publication
        }

    }

    Package "valueobject"  {

        class PublicationId <<ValueObject>> #LightPink {
           - _releaseYear : Year

        }

        class Title <<ValueObject>> {
        }

        class AuthorId <<ValueObject>> {
        }

        class GenreId <<ValueObject>>{
        }



    }

    Package "repository"   {
        interface IPublicationRepo <<Interface>>
    }

    Publication -[hidden]right- IPublicationRepo
    PublicationId -[hidden]right- IPublicationRepo

}

Package "ddd" {
    interface IRepository<ID, T> <<Interface>> {
        +save(entity : T) : T
        +findAll() : Iterable<T>
        +findAllKeys() : List<ID>
        +ofIdentity(id : ID) : Optional<T>
        +containsOfIdentity(id : ID) : boolean
    }
}

' ===== Persistence =====
Package "persistence" {
     package "mem"  {
     class MemoPublicationRepo <<Repo>>
    }
}

' ===== Relations =====
Publication "1" --> "ID 1" PublicationId : has
Publication "1"-> "1" Title : has
Publication "1"..> "1" AuthorId : references
Publication "1"..> "1" GenreId : references

PublicationId "1" --> "1" Title : has
PublicationId "1" -> "1" AuthorId : has

IPublicationRepo -|> IRepository
MemoPublicationRepo ..|> IPublicationRepo
Publication "*" <-- "1" MemoPublicationRepo : persists
PublicationFactory "1"<-- "1" MemoPublicationRepo : invokes
PublicationFactory ..> Publication : <<create>>

@enduml