@startuml

title Sale Aggregate - DDD

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0

top to bottom direction

Package "domain" {

    Package "sale" <<Folder>> #b0c4d4 {
        class Sale <<Entity>> <<Root>> {
            - _createdAt : LocalDateTime
            - _completedAt : LocalDateTime
            + get_buyerId() : UserId
            + get_totalAmount() : Price
            + get_saleLines() : List<SaleLine>
            + get_saleSaleStatus() : SaleSaleStatus
            + get_createdAt() : LocalDateTime
            + get_completedAt() : LocalDateTime
            + markSaleAsCompleted() : void
            + markSaleAsCancelled() : void
            - calculateTotalAmount() : Price
            - validateSaleLines(saleLines : List<SaleLine>) : List<SaleLine>
        }

        class SaleLine <<Entity>> {
            + get_saleLineId() : SaleLineId
            + get_directSaleId() : DirectSaleId
            + get_sellerId() : UserId
            + get_priceAtSale() : Price
                }

        class SaleFactory <<Factory>> {
            +createSale(buyerId : UserId, saleLines : List<SaleLine>) : Sale
            +createSale(saleId : SaleId, buyerId : UserId, saleLines : List<SaleLine>, createdAt : LocalDateTime, completedAt : LocalDateTime, saleSaleStatus : SaleSaleStatus) : Sale
        }
        class SaleLineFactory <<Factory>> {
            +createSaleLine(sellerId : UserId, priceAtSale : Price, directSaleId : DirectSaleId) : SaleLine
            +createSale(saleLineId : SaleLineId, sellerId : UserId, priceAtSale : Price, directSaleId : DirectSaleId) : SaleLine
        }
    }

    Package "valueobject" <<Folder>> {
        class SaleId <<ValueObject>> #LightPink {
                -_id :String
                    }

        class SaleLineId <<ValueObject>> #LightPink{
        -_id :String
                    }

        enum SaleSaleStatus {
            PENDING
            COMPLETED
            CANCELLED
        }

                class UserId <<Value Object>>
                class DirectSaleId <<Value Object>>
                class Price <<Value Object>>
    }

    Package "repository" <<Folder>> {
        interface ISaleRepo <<Interface>> {
            +findByUserId(userId : UserId) : List<Sale>
        }
    }
}

Package "ddd" {
    interface IRepository<ID, T> <<Interface>> {
        +save(entity : T) : T
        +findAll() : Iterable<T>
        +findAllKeys() : List<ID>
        +ofIdentity(id : ID) : Optional<T>
        +containsOfIdentity(id : ID) : boolean
    }
    interface AggregateRoot<ID> {}
    interface DomainEntity<ID, T> <<Interface>> {
        +identity() : ID
        +sameAs(object : Object) : boolean
    }
}


Sale "*" <- "1" ISaleRepo : persists

ISaleRepo --|> IRepository
SaleFactory "1" ..> "1..*" Sale : <<create>>
SaleLineFactory "1" ..> "1..*" SaleLine : <<create>>
Sale "1" *-- "*" SaleLine: has

Sale "1" -> "1" SaleId : has
Sale "*"..> "1" UserId : references
Sale "1" -> "1" Price : has
SaleLine "1" -> "1" Price : has

Sale "*" -> "1" SaleSaleStatus : has

SaleLine "*"..> "1" DirectSaleId : references
SaleLine "*"..> "1" UserId : references
SaleLine "1" -> "1" SaleLineId : has

Sale "1" ..> "1" SaleLineFactory : <<uses>>

Sale ..|> AggregateRoot
SaleLine ..|> DomainEntity
AggregateRoot -|> DomainEntity

@enduml