@startuml
title "As a Buyer, I want to get the list of items on direct sale %n() of a given genre" - Level 2 SD
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

actor Buyer
participant ":UIGetItemsOnDirectSaleByGenre" as UI
participant ":GetItemsOnDirectSaleByGenreController" as CTL
participant "_dsr:DirectSaleRepo" as DSR
participant "directSale:DirectSale" as DS

'-- Dialog --'
Buyer -> UI : I want the list of items in direct sale\nof a given genre
activate UI

UI --> Buyer : What is the genre?
deactivate UI

Buyer -> UI :genreName
activate UI

'-- System interaction --'
UI -> CTL : getDirectSaleItemsByGenre(genreName)
activate CTL

CTL -> DSR : getDirectSaleItemsByGenre(genreName)
activate DSR

create "listOfItemsOnDirectSaleByGenre:List<Item>" as List
DSR -> List: create()

' --- To run through each directSale available and check the genre associated with the corresponding Item ---
loop for each directSale in _dsr
    DSR -> DS : isByGenre(genreName)

    opt isByGenre == true
        DSR -> List: add (directSale.getItem())
        activate List
        List -> DSR: true
        deactivate List
    end
end

create "ListCopyOfItemsOnDirectSaleByGenre: List<Item>" as ListCopy

DSR -> ListCopy: List.copyOf(ListOfItemsOnDirectSaleByGenre)
DSR --> CTL: copyOfListCopyOfItemsOnDirectSaleByGenre
deactivate DSR

CTL --> UI: copyOfListCopyOfItemsOnDirectSaleByGenre
deactivate CTL

UI --> Buyer: Here's the list!
deactivate UI

@enduml