@startuml
title Class Diagram - US015 - "As a User, I want to put for sale a publication %n() in my library in a direct sale"

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0

top to bottom direction

class PublicationInLibraryForDirectSaleUI {
}

class PublicationInLibraryForDirectSaleController {
  - libraryRepo: ILibraryRepo
  - directSaleRepo: IDirectSaleRepo
  + getItemsInLibraryByUser(userID: UserID): List<Item>
  + addItemForDirectSale(itemID: ItemID, price: Price, timeLimit: Period): DirectSale
}

interface ILibraryRepo {
  + getItemsInLibraryByUser(userID: UserID): List<Item>
}

class Library {
  - _userID: UserID
  - _items: List<Item>
  + getItemsInLibrary(): List<Item>
}

class MemoLibraryRepo{
    - _libraries: List<Library>
}

class Item {
}

interface IDirectSaleRepo{
+ addDirectSale(itemID: ItemID, price: Price, timeLimit: Period): DirectSale
}

class MemoDirectSaleRepo {
  - _directSales: List<DirectSale>
  - _factory: DirectSaleFactory
}

class DirectSaleFactory {
  + createDirectSale(itemID: ItemID, price: Price, timeLimit: Period): DirectSale
}

class DirectSale {
  - itemID: ItemID
  - price: Price
  - timeLimit: Period
'  + DirectSale(item: Item, price: Price, timeLimit: Period)
}

PublicationInLibraryForDirectSaleUI "1" ..> "1" PublicationInLibraryForDirectSaleController : invokes
PublicationInLibraryForDirectSaleController "1" ..> "1" ILibraryRepo : calls
PublicationInLibraryForDirectSaleController "1" ..> "1" IDirectSaleRepo : calls

MemoLibraryRepo "1" --> "*" Library : contains
Library "1" --> "*" Item : contains
MemoLibraryRepo ..|> ILibraryRepo

MemoDirectSaleRepo ..|> IDirectSaleRepo
MemoDirectSaleRepo "1" --> "1" DirectSaleFactory : uses
DirectSaleFactory "1" --> "*" DirectSale : creates

'DirectSale "1" --> "1" Item : sells



@enduml