    @startuml

    title  "As an Administrator, I want to add a publication genre to the official \ngenre list, so that new publications can be of this genre" - SD

    '==== basic style ====
    skinparam monochrome false
    skinparam shadowing false
    skinparam defaultFontName Futura
    skinparam objectFontSize 20
    skinparam backgroundColor CornSilk
    skinparam objectBackgroundColor WhiteSmoke
    skinparam noteBackgroundColor #FFFFE0
    skinparam ArrowFontColor #3B4953
    skinparam ArrowColor #57595BAA
    skinparam ActivationBackgroundColor WhiteSmoke
    hide footbox

    autonumber

    actor Administrator
    participant ":AddGenreUI" as UI
    participant ":AddGenreController" as Ctl
    participant ":GenreFactory" as gf
    participant ":JpaGenreRepo" as gr
    participant ":GenreAssembler" as ass
    participant ":IGenreSpringDataRepo" as sd

    Administrator -> UI: I want to add a publication genre
    activate UI
    UI --> Administrator: What is the genre name?
    deactivate UI
    Administrator -> UI: genreName
    activate UI

    UI -> Ctl: addGenre(genreName)
    activate Ctl

    Ctl -> gf: createGenre(genreName)
    activate gf
    create "newGenre:Genre" as g
    gf -->> g: <<Create>>
    gf --> Ctl : newGenre
    deactivate gf

    Ctl -> gr : containsOfIdentity(newGenre.identity())
    activate gr
    gr -> sd : existsById(idString)
    activate sd
    sd --> gr : exists
    deactivate sd
    gr --> Ctl : exists
    deactivate gr

    opt !exists
        Ctl -> gr: save(newGenre)
        activate gr

        gr -> ass : domain2DM(newGenre)
        activate ass
        create "dm:GenreDataModel" as dm
        ass -->> dm : <<Create>>
        ass --> gr : dm
        deactivate ass

        gr -> sd : save(dm)
        activate sd
        sd --> gr : savedDm
        deactivate sd

        gr -> ass : DM2Domain(savedDm)
        activate ass
        ass -> gf : createGenre(name)
        ass --> gr : savedGenre
        deactivate ass

        gr --> Ctl: savedGenre
        deactivate gr
    end

    Ctl --> UI: savedGenre
    deactivate Ctl

    UI --> Administrator: Genre added successfully!
    deactivate UI

    @enduml