@startuml
title " As an Administrator, I want to add a publication genre to the official \ngenre list, so that new publications can be of this genre" CD

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0

' ===== UI & Controller =====
class AddGenreUI {
}

package "controller" {
    class AddGenreController {
        + addGenre(genreName : String) : Genre
    }
}

' ===== Domain =====
package "domain" {
    package "repository" {
        interface IGenreRepo <<Interface>> {
        }
    }

    package "genre" #b0c4d4 {
        class Genre <<Root>> <<Entity>>{
            + identity() : GenreId
            + sameAs(Object) : boolean
            + getGenre() : String
        }

        class GenreFactory <<Factory>> {
            + createGenre(genreName : String) : Genre        }
    }

    package "valueobject" {
        class GenreId <<ValueObject>> #LightPink {
            -_id : String
        }
    }
}

package "ddd" {
    interface IRepository<ID, T> <<Interface>> {
        save(T) : T
        findAll() : Iterable<T>
        findAllKeys() : List<ID>
        ofIdentity(ID) : Optional <T>
        containsOfIdentity(ID) : boolean
    }

    interface AggregateRoot<ID>
}

'==== Interactions ====
AddGenreUI "1" ..> "1" AddGenreController : invokes

AddGenreController "1" --> "1" IGenreRepo : calls
AddGenreController "1" --> "1" GenreFactory : invokes
AddGenreController "1" ..> "*" Genre : <<use>>

GenreFactory "1" ..> "*" Genre : <<create>>

Genre "1" --> "1" GenreId : has
Genre "*" <- "1" IGenreRepo : persists

IGenreRepo -|> IRepository
Genre ..|> AggregateRoot

@enduml