@startuml
title " As an Administrator, I want to add a publication genre to the official \ngenre list, so that new publications can be of this genre" CD

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0

'==== Classes ====
class AddGenreUI {

}

package "controller" {

    class AddGenreController {
    + addGenre(genreName : String) : Genre
    }
}

package "domain" {



    package "valueobject" {

        class GenreId <<ValueObject>> #lightpink {
        -_id : String
        }

    }

    package "repository" {

             interface IGenreRepo <<Interface>>{
                 + addGenre(genreName : String) : Genre
             }
         }

    package "genre" #b0c4d4 {

        class Genre  <<Root>> <<Entity>> {
            - _genre : String

        }

        class GenreFactory <<Factory>> {
            + createGenre(genreName : String) : Genre
        }
    }


}

package "persistence"  {
    package "memo" {

        class MemoGenreRepo {
        }
    }
}

package ddd {

     interface IRepository<ID, T> <<Interface>> {
        save(entity:T) : T
        findAll() : Iterable<T>
        findAllKeys () : List <ID>
        ofIdentity(id: ID) : Optional <T>
        containsOfIdentity(id: ID) : boolean
        }

        interface AggregateRoot <ID >{
         }
        interface DomainEntity<ID, T> <<Interface>> {
                +identity() : ID
                +sameAs(object:Object) : boolean
        }

}
'==== Relationships ====
AddGenreUI "1" .> "1" AddGenreController : invokes

AddGenreController "1" .> "1" IGenreRepo : <<use>>
AddGenreController  "1".....> "*" Genre : <<use>>


MemoGenreRepo .|> IGenreRepo
MemoGenreRepo "1" ---> " 1" GenreFactory : invokes
MemoGenreRepo "1" --> "*" Genre : persists
GenreFactory "1" ..> "*" Genre : <<create>>
Genre "1" ---> "1" GenreId: has

IGenreRepo --|> IRepository

AggregateRoot -|> DomainEntity
Genre .|> AggregateRoot

@enduml