@startuml
title US025 – "As a Buyer, I want to get the list of items on direct sale of a given author" - Level 2 SD
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---
actor Buyer
participant ":GetDirectSaleItemsByAuthorUI" as UI
participant ":GetDirectSaleItemsByAuthorController" as CTL
participant "dsr:DirectSaleRepo" as DSR
participant "directSale:DirectSale" as DS



' --- Dialog ---
Buyer -> UI: I want the list of items on direct sale of a given author
activate UI
UI --> Buyer: What is the author's name?
deactivate UI
Buyer -> UI: authorName
activate UI
UI -> CTL: getDirectSaleItemsByAuthor(authorName)
activate CTL
CTL -> DSR: getDirectSaleItemsByAuthor(authorName)
activate DSR

create "listOfDirectSaleItemsByAuthor: List<Item>" as List
DSR -> List: create()

loop for each directSale in dsr
    DSR -> DS: isByAuthor(authorName)
'    activate DS
'    DS -> DSR: true
'    deactivate DS
    opt isByAuthor == true
        DSR -> List: add(directSale.getItem())
        activate List
        List -> DSR: true
        deactivate List
    end
end

create "copyOfListOfDirectSaleItemsByAuthor: List<Item>" as Copy
DSR -> Copy: List.copyOf(ListOfDirectSaleItemsByAuthor)



DSR --> CTL: copyOfListOfDirectSaleItemsByAuthor
deactivate DSR
CTL --> UI: copyOfListOfDirectSaleItemsByAuthor
deactivate CTL
UI --> Buyer: Here's the list! done!
deactivate UI

@enduml