@startuml
title US0010 - "As a User, I want to register a new publication in the system" - SD

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox
autonumber

' --- Actor and participants ---
actor User
participant "UI1:UIPublicationRegister" as UI
participant "Ctl1:CtlPublicationRegister" as Ctl
participant "_pr:PublicationRepo" as PR

' --- UI interaction ---
User -> UI: I want to register a new publication
activate UI
UI --> User: Fill the registration form...
User -> UI: Publication data\n(type, identifier, date, title, ...)
UI -> UI: Validate mandatory fields

' --- Use case execution ---
UI -> Ctl: registerPublication(type, identifier, date, title, ...)
activate Ctl
Ctl -> PR: registerPublication(type, identifier, date, title, ...)
activate PR

' --- Validation Duplicates
PR -> PR: Check if Publication already exists

' --- Create
create "myPublication:Publication"
PR -> "myPublication:Publication": create(type, identifier, date, title, ...)
activate "myPublication:Publication"
"myPublication:Publication" --> PR: myPublication
deactivate "myPublication:Publication"

PR --> Ctl: myPublication
deactivate PR
Ctl --> UI: myPublication
deactivate Ctl

UI --> User: done!
deactivate UI
@enduml
