@startuml

'==== Title ====
title "As an Administrator, I want to register an Appraisal Entity, including the list of genres and publication types it can appraisal" CD
top to bottom direction


'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0


' ===== Domain =====
class RegisterNewAppraisalEntityUI {
}

package "controller" {

    class RegisterNewAppraisalEntityController {

        + registerNewAppraisalEntity(name : Name, publicationTypeIds : List<PublicationTypeId>, \ngenreIds : List<GenreId>) : AppraisalEntity
        + getPublicationTypes() : Iterable<PublicationType>
        + getGenres() : Iterable<Genre>

    }

}

package "persistence" {

    package "mem" {

        class MemAppraisalEntityRepo {

        }

        class MemGenreRepo {

        }

        class MemPublicationTypeRepo {

        }

    }

}

package "domain" {
    package "repository" {

        interface IAppraisalEntityRepo <<Interface>> {

        }

        interface IGenreRepo <<Interface>> {

        }

        interface IPublicationTypeRepo <<Interface>> {

        }

    }

    package "appraisalEntity" #b0c4d4 {

        class AppraisalEntity <<Root>> <<Entity>>{
            -_publicationTypeIds : List<PublicationTypeId>
            -_genreIds : List<GenreId>

            +identity() : AppraisalEntityId
            +sameAs(Object) : boolean
            +getName() : Name
            +getGenreIds () : List<GenreId>
            +getPublicationTypeIds() : List<PublicationTypeId>
        }

        class AppraisalEntityFactory <<Factory>> {
        + createAppraisalEntity(name : Name, \npublicationTypeIds: List<PublicationTypeId>, \ngenreIds : List<GenreId>) : AppraisalEntity
        }

    }

    Package "valueobject"  {

        '== Value Objects (Ids) ==
        class AppraisalEntityId <<ValueObject>> #LightPink {
        -_id : String

        }

        class GenreId <<ValueObject>> {

        }

        class PublicationTypeId <<ValueObject>> {

        }
        ' ===== Value Objects =====
        class Name <<ValueObject>> {

        }

    }

}

Package "ddd" {

    interface IRepository<ID, T> <<Interface>> {
    save(T) : T
    findAll() : Iterable<T>
    findAllKeys() : List<ID>
    ofIdentity(ID) : Optional <T>
    containsOfIdentity(ID) : boolean
    }

}


'==== Interactions ====
RegisterNewAppraisalEntityUI "1" ..> "1" RegisterNewAppraisalEntityController : invokes

RegisterNewAppraisalEntityController "1" ..> "1" IGenreRepo : calls
RegisterNewAppraisalEntityController "1" ..> "1" IPublicationTypeRepo : calls
RegisterNewAppraisalEntityController "1" ..> "1" IAppraisalEntityRepo : calls
RegisterNewAppraisalEntityController "1" ....> "*" AppraisalEntity : <<use>>
RegisterNewAppraisalEntityController "1" --> "1" AppraisalEntityFactory : invokes

AppraisalEntityFactory "1" ..> "*" AppraisalEntity : <<create>>

AppraisalEntity "1" --> "ID 1" AppraisalEntityId : has
AppraisalEntity "1" --> "1..*" GenreId : references
AppraisalEntity "1" --> "1..*" PublicationTypeId : references
AppraisalEntity "1" *-- "1" Name : has
AppraisalEntity "*" <- "1" MemAppraisalEntityRepo : persists

IAppraisalEntityRepo <|.. MemAppraisalEntityRepo
MemGenreRepo ..|> IGenreRepo
MemPublicationTypeRepo ..|> IPublicationTypeRepo

IAppraisalEntityRepo ----|> IRepository
IPublicationTypeRepo -|> IRepository
IGenreRepo -|> IRepository

@enduml