@startuml
'https://plantuml.com/sequence-diagram

autonumber
title US022 "As a Buyer, I want to get the list of items on auction of a given genre" - SD

hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---'

actor Buyer
participant ": GetAuctionItemsByUI" as UI
participant "ctl:GetAuctionItemsByGenreController" as Ctl
participant "ar: MemoAuctionRepo" as AuctionRepo
participant "auction:Auction" as auction

Buyer -> UI: Display list on auction\n items by genre
activate UI
UI --> Buyer: Which genre?
deactivate UI

Buyer -> UI: genre
activate UI

UI -> Ctl: getAuctionItemsByGenreId(genreId)
activate Ctl

Ctl -> AuctionRepo: getAuctionItemsByGenreId(genreId)
activate AuctionRepo


create "listOfAuction\nItemsByGenreId: List<ItemId>" as List
AuctionRepo -->> List : <<Create>>
loop for each Auction in AuctionRepo
     AuctionRepo -> auction: isByGenreId(genreId)
    opt isByGenreId == true
        AuctionRepo -> List: add(auction.getItemId())
        List --> AuctionRepo :true
    end
end

create "copyOfListOfAuction\nItemsByGenreId: List<ItemId>" as Copy
AuctionRepo -> Copy:List.copyOf(listOfAuctionItemsByGenreId)

AuctionRepo --> Ctl : copyOfListOfAuctionItemsByGenreId
deactivate AuctionRepo
Ctl --> UI: copyOfListOfAuctionItemsByGenreId
deactivate Ctl
UI --> Buyer: Here's your list!
deactivate UI

@enduml