@startuml
title "As a User, I want to put for sale a publication %n() in my library in an auction" - SD
hide footbox

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

actor User
participant ":PublicationInLibrary\nForAuctionUI" as UI
participant ":PublicationInLibrary\nForAuctionController" as Ctl
participant ":ILibraryRepo" as LibraryRepo
participant "listOfItemsId:List<ItemId>" as listOfItemsId
participant ":AuctionFactory" as AuctionFactory
participant "auction:Auction" as auction
participant ":IAuctionRepo" as AuctionRepo
participant ":IItemRepo" as itemRepo
participant "item:Item" as item

User -> UI: I want to put for auction\nan item in my library!
activate UI

UI -> Ctl: getItemsIdInLibraryByUserId\n(userId)
activate Ctl

Ctl -> LibraryRepo: getItemsIdInLibraryByUserId\n(userId)
activate LibraryRepo
create listOfItemsId
LibraryRepo --> listOfItemsId : <<create>>
LibraryRepo --> Ctl: listOfItemsId
deactivate LibraryRepo

Ctl --> UI: listOfItemIds
deactivate Ctl
UI --> User: Which items\nwould you like to sell?
deactivate UI

User -> UI: itemsId
activate UI

UI --> User: What is the price \nand time limit for this sale?
deactivate UI
User -> UI: price, time limit
activate UI

UI -> Ctl: putItemIdOnAuction\n(itemsId, startPrice, reservePrice,\n outrightPrice, startDate, endDate)
activate Ctl

Ctl -> AuctionFactory: createAuction\n(itemsId, startPrice, reservePrice,\n outrightPrice, startDate, endDate)
activate AuctionFactory
create auction
AuctionFactory -->> auction: <<create>>
AuctionFactory --> Ctl: auction
deactivate AuctionFactory

Ctl -> AuctionRepo : exists = containsOfIdentity(auction.identity())

opt !exists

loop itemId : listOfItemsId
    Ctl -> itemRepo : ofIdentity(itemId)
    activate itemRepo
    itemRepo --> Ctl : item
    deactivate itemRepo
    Ctl -> item: notOnSale = getSaleStatus()
    opt notOnSale
        Ctl -> item : markAsAuction()
    end
end


Ctl -> AuctionRepo : save(auction)
activate AuctionRepo
AuctionRepo --> Ctl : auction
deactivate AuctionRepo
end
Ctl --> UI: auction
deactivate Ctl
UI --> User: Your item was\nsuccessfully put up on an auction!
deactivate UI

@enduml