@startuml
title "As a User, I want to put for sale a %n()publication in my library in an auction" %n() SSD
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---
actor User
participant ":MiteLovers" as System

' --- System dialog ---
User -> System: I want to put for auction\nan item in my library
activate "System"
System --> User: Select ItemId
deactivate "System"
User -> System: itemId
activate "System"
System --> User: What are the starting, reserve and outright prices,\n plus the end date for this sale?
deactivate "System"
User -> System: starting price, reserve price, outright price, end date
activate "System"
System --> User: Your item was \nsuccessfully put up on an auction!
deactivate "System"

@enduml