@startuml
'==== Title ====
title "As an Administrator, I want to register an Author in the system, so that publications of that author can be added." - SD


'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox
autonumber
autoactivate off


' ==== Actor and participants ====
actor Administrator
participant ":CreateAuthorUI" as UI
participant ":CreateAuthorController" as CTL
participant ":IAuthorRepo" as IA
participant ":AuthorFactory" as factory


'==== UI interaction ====
Administrator -> UI: I want to register an Author
activate UI

UI --> Administrator: What is the author's name?
deactivate UI

Administrator -> UI: authorName
activate UI

UI -> CTL: createAuthor(authorName)

activate CTL

CTL -> factory: createAuthor(authorName)

activate factory
create "authorName:Author"
factory -->> "authorName:Author": <<create>> (authorName)
factory --> CTL: authorName
deactivate factory

CTL -> IA: save(authorName)
activate IA

ref over IA
[[sd-ref-diagrams/Save_Author.puml Save Author and return saved domain object]]
end ref

IA --> CTL: reconstructoredAuthor
deactivate IA

CTL --> UI: reconstructoredAuthor
deactivate CTL

UI --> Administrator: Done!
deactivate UI

@enduml