@startuml
'==== Title ====
title "As an Administrator, I want to register an Author in the system, so that publications of that author can be added." - SD


'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox
autonumber
autoactivate off


' ==== Actor and participants ====
actor Administrator


'==== UI interaction ====
Administrator -> ":CreateAuthorUI": I want to register an Author
activate ":CreateAuthorUI"

":CreateAuthorUI" --> Administrator: What is the author's name?
deactivate ":CreateAuthorUI"

Administrator -> ":CreateAuthorUI": authorName
activate ":CreateAuthorUI"

":CreateAuthorUI" -> ":CreateAuthorController": createAuthor(authorName)

activate ":CreateAuthorController"
":CreateAuthorController"-> ":MemoAuthorRepo": addAuthor(authorName)

activate ":MemoAuthorRepo"
":MemoAuthorRepo" -> ":AuthorFactory": createAuthor(authorName)

activate ":AuthorFactory"
create "author:Author"
":AuthorFactory" -->> "author:Author": <<create>>
":AuthorFactory" --> ":MemoAuthorRepo": author
deactivate ":AuthorFactory"
":MemoAuthorRepo" -> ":MemoAuthorRepo": save(author)


":MemoAuthorRepo" --> ":CreateAuthorController": author
deactivate ":MemoAuthorRepo"

":CreateAuthorController" --> ":CreateAuthorUI": author
deactivate ":CreateAuthorController"

":CreateAuthorUI" --> Administrator: Done!
deactivate ":CreateAuthorUI"

@enduml