@startuml
title US008 - "As an Administrator, I want to register a new city in the system" - SD
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing true
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ArrowColor #57595BAA

autonumber
autoactivate off

actor Administrator as Admin
participant ":RegisterCityUI" as UI
participant ":RegisterCityController" as Ctl
participant "_cr:CountryRepo" as CountryRepo
participant "_cir:CityRepo" as CityRepo
participant ":CityFactory" as Factory

Admin -> UI: I want to register a new City.
activate UI

UI -> Ctl: getCountries()
activate Ctl
Ctl -> CountryRepo: getAllCountries()
activate CountryRepo
Ctl <-- CountryRepo: listOfCountries
deactivate CountryRepo
UI <-- Ctl: listOfCountries
deactivate Ctl

UI -> Admin: show form (city name, listOfCountries)
deactivate UI

Admin -> UI: select country; enter cityName
activate UI
UI -> Ctl: registerCity(cityName, country)
activate Ctl

Ctl -> CityRepo: RegisterCity(cityName, country)
        activate CityRepo

    opt existsByNameAndCountry(cityName, country) == false

        CityRepo -> Factory: createCity(cityName, country)
        activate Factory
        create "newCity:City" as instance
        Factory -> instance: create(cityName, country)
        Factory --> CityRepo: newCity
        deactivate Factory
        CityRepo -> CityRepo: add(newCity)
    end

    CityRepo --> Ctl: RegisteredCity
    deactivate CityRepo

Ctl --> UI: RegisteredCity
deactivate Ctl
UI --> Admin: City registered successfully!
deactivate UI
@enduml
