@startuml
'https://plantuml.com/class-diagram
title US008 – "As an Administrator, I want to register a new city in the system" – CD

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam classAttributeIconSize 0


class RegisterCityUI {

}

class City {
  + City(name: String, country: Country)
  + getName(): String
  + getCountry(): Country
}

class CityRepo {
  + existsByNameAndCountry(name: String, country: Country): boolean
  + save(city: City): City
  + getAll(): List<City>
}

class CountryRepo {
  + getAllCountries(): List<Country>
  + findByName(countryName: String): Country
}

class CityRegisterController {
  + getCountries(): List<Country>
  + registerCity(name: String, country: Country): City
}

RegisterCityUI "1" ..> "1" CityRegisterController : invokes
CityRegisterController "1" --> "1" CountryRepo : uses
CityRegisterController "1" --> "1" CityRepo : uses
CityRepo "1" --> "*" City : manages
@enduml
