@startuml
title US008 - "As an Administrator, I want to register a new city in the system" - SD

'==== basic style ====
skinparam monochrome false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ArrowColor #57595BAA

autonumber
autoactivate off
hidefootbox

' ==== Actor and participants ====
actor Administrator as Admin
participant ":RegisterCityUI" as UI
participant ":RegisterCityController" as CTL
participant "_cr:MemoCountryRepo" as CouR
participant "_cir:MemoCityRepo" as CityR
participant ":CityFactory" as FCT

'==== UI interaction ====
Admin -> UI: I want to register a new City.
activate UI

UI -> CTL: getAllCountries()
activate CTL
CTL -> CouR: getAllCountries()
activate CouR
CTL <-- CouR: List.copyOfListOfCountries
deactivate CouR
UI <-- CTL: List.copyOfListOfCountries
deactivate CTL

UI --> Admin: Please choose a country \n and provide the city name.
deactivate UI

Admin -> UI: country, cityName
activate UI

UI -> CTL: registerCity(cityName, country)
activate CTL

CTL -> CityR: registerCity(cityName, country)
        activate CityR

    opt existsCityInACountry(cityName, country) == false

        CityR -> FCT: createCity(cityName, country)
        activate FCT
        create "c1:City" as instance
        FCT -->> instance: <<Create>>
        FCT --> CityR: c1
        deactivate FCT
        CityR -> CityR: add(c1)
    end

    CityR --> CTL: c1
    deactivate CityR

CTL --> UI: c1
deactivate CTL
UI --> Admin: City registered successfully!
deactivate UI
@enduml
