@startuml
'https://plantuml.com/class-diagram
title US018 - "As a User, I want to add one of my publications to a list of mine" - CD

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0


class AddItemToListUI {
}

class AddItemToListController {

    + getMyLists(userId : UserId) : Map<ListOfItemsId, String>
    + getItemsInMyLibrary(userId : UserId) : Map<ItemId, ItemSummary>
    + addItemToList(itemId : ItemId, listOfItemsId : ListOfItemsId) : boolean
}

interface IListOfItemsRepo {
    + findListsByUser(userId : UserId) : Map<ListOfItemsId, String>
    + findListById(listOfItemsId : ListOfItemsId) : ListOfItems
    + save(list : ListOfItems) : void
}

class MemoListOfItemsRepo{
    + getMyLists(userId : UserId)
}

class Library <<AggregateRoot>> {
    - _itemIds : List<ItemId>
    + getItemsInLibrary() : Map<ItemId, ItemSummary>
}

class ListOfItems <<AggregateRoot>> {
    - _listOfItemsId : ListOfItemsId
    - _itemIds : List<ItemId>
    + addItem(itemId : ItemId)
}

interface ILibraryRepo {
    + findLibraryByUser(userId : UserId) : LibraryId
    + getItemsInLibrary(libraryId : LibraryId) : Map<ItemId, ItemSummary>
}

class MemoLibraryRepo {
    + findLibraryByUser(userId)
}

class ItemSummary <<Value Object>> {
    - title: String
    - author: String
}

class ItemId {
}

'==== Interactions ===='

AddItemToListUI "1" ..> "1" AddItemToListController : invokes
AddItemToListController "1" ..> "1" IListOfItemsRepo : calls
AddItemToListController "1" ..> "1" ILibraryRepo : calls
MemoListOfItemsRepo "1" --> "*" ListOfItems: updates
MemoLibraryRepo "1" --> "*" Library : accesses
IListOfItemsRepo <|.. MemoListOfItemsRepo: implements
ILibraryRepo <|.. MemoLibraryRepo: implements
Library ..|> ItemSummary: uses
Library ..|> ItemId: references
ListOfItems ..|> ItemId: references

@enduml