@startuml
title "As an Administrator, I want to add a publication type to the official type list, %n() so that new publications can be of this type" SD
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---
actor "Administrator" as Admin
participant ":AddPublicationTypeUI" as UI
participant ":AddPublicationTypeController" as Ctl
participant ":PublicationTypeFactory" as FACTORY
participant ":IPublicationTypeRepo" as REPO

' --- System dialog ---
Admin -> UI: I want to add a %n()new publication type.
activate "UI"
UI --> Admin: What type would %n()you like to add?
deactivate "UI"
Admin -> UI: publicationTypeName
activate "UI"
UI -> Ctl: addPublicationType %n() (publicationTypeName)
activate "Ctl"
Ctl -> FACTORY: createPublicationType%n()(publicationTypeName)

activate FACTORY
create "newPublicationType\n:PublicationType" as instance
FACTORY -->> instance: <<create>>(publicationTypeName)
FACTORY --> Ctl: newPublicationType
deactivate FACTORY

ref over Ctl
[[sd-ref-diagrams/Verify_New_Publication_Type.puml Verify the existence of newPublicationType in persistence]]
end ref

Ctl -> REPO: save(newPublicationType)
activate REPO

ref over REPO
[[sd-ref-diagrams/Save_New_Publication_Type.puml Save newPublicationType and return saved domain object]]
end ref

Ctl <-- REPO: PublicationType
deactivate "REPO"
Ctl --> UI: PublicationType
deactivate "Ctl"
UI --> Admin: Added successfully!
deactivate "UI"

@enduml