@startuml
title "As an Administrator, I want to add a publication type to the official type list, %n() so that new publications can be of this type" SD
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---
actor "Administrator" as Admin
participant ":AddPublication%n()TypeUI" as UI
participant ":AddPublication%n()TypeCtl" as Ctl
participant ":PublicationType%n()Factory" as FACTORY
participant ":MemPublication%n()TypeRepo" as REPO

' --- System dialog ---
Admin -> UI: I want to add a %n()new publication type.
activate "UI"
UI --> Admin: What type would %n()you like to add?
deactivate "UI"
Admin -> UI: publicationTypeName
activate "UI"
UI -> Ctl: addPublicationType %n() (publicationTypeName)
activate "Ctl"
Ctl -> FACTORY: createPublicationType%n()(publicationTypeName)
activate FACTORY
create "newPublicationType %n() :PublicationType" as instance
FACTORY -->> instance: <<create>>
FACTORY --> Ctl: newPublicationType
deactivate FACTORY
note right of Ctl
  assuming happy path:
  containsOfIdentity(newPublicationType.identity())
   == false
end note
Ctl -> REPO: save(newPublicationType)
deactivate "REPO"
Ctl --> UI: newPublicationType
deactivate "Ctl"
UI --> Admin: Added successfully!
deactivate "UI"

@enduml