@startuml
title "As a User, I want to create a private list of my publications, give it a name and set a genre" SD
hide footbox

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

actor "User"
participant ":CreatePrivateListOfItemsUI" as UI
participant ":CreateListOfItemsController" as Ctl
participant ":IGenreRepo" as IGenreRepo
participant ":ListOfItemsFactory" as Factory
participant ":IListOfItemsRepo" as IRepo

"User" -> UI : I want to create a private list
activate UI
UI --> "User" : What is the list's name?
deactivate UI
"User" -> UI : name
activate UI

UI -> Ctl : getAllGenres()
activate Ctl
Ctl -> IGenreRepo : getListOfOfficialGenres()
activate IGenreRepo
IGenreRepo --> Ctl : genres
deactivate IGenreRepo
Ctl --> UI : genres
deactivate Ctl

UI --> "User" : What genre?
deactivate UI
"User" -> UI : genreId
activate UI

UI -> Ctl : createListOfItems(userId, name, genreId)
activate Ctl

Ctl -> Factory : createListOfItems(userId, name, genreId)
activate Factory
create "newList:ListOfItems"
Factory -->> "newList:ListOfItems" : <<create>>(userId, name, genreId)
Factory --> Ctl : newList
deactivate Factory

ref over Ctl
[[sd-ref-diagrams/Verify_ListOfItems.puml Verify the existence of newList in persistence]]
end ref

Ctl -> IRepo : save(newList)

ref over IRepo
[[sd-ref-diagrams/Save_ListOfItems.puml Save newList and return saved domain object]]
end ref

activate IRepo
IRepo --> Ctl : savedList
deactivate IRepo

Ctl --> UI : savedList
deactivate Ctl
UI --> "User" : Private list successfully created!
deactivate UI

@enduml