@startuml
'==== Title ====
title "As a User, I want to create a private list of my publications, give it a name and a set a genre" - SSD

'==== basic style ====
skinparam monochrome false

skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ArrowColor #57595BAA

hidefootbox
autonumber
autoactivate off

' ==== Actor and participants ====
actor User
participant ":MiteLovers" as ML

'==== UI interaction ====
User -> ML: I want to create a private list
activate ML
ML --> User: What is the list's name?
deactivate ML

User -> ML:  name
activate ML

User <-- ML:  What is the list's genre?
deactivate

User -> ML:  genre
activate ML

ML --> User : Private list successfully created!
deactivate ML
@enduml