@startuml
title "As a User, I want to create a private list of my publications, give it a name and set a genre" CD
top to bottom direction

skinparam monochrome false
skinparam shadowing true
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ArrowColor #57595BAA
skinparam classAttributeIconSize 0

class CreatePrivateListOfItemsUI

package "controller" {
    class CreateListOfItemsController {
        + getAllGenres() : Map<GenreId, String>
        + createListOfItems(userId : UserId, name : Name, genreId : GenreId) : ListOfItems
    }
}

package "domain" {

    package "listofitems" #b0c4d4 {
        class ListOfItems <<Root>> <<Entity>> {
            - _isPrivate : boolean
                        + getUserId() : UserId
                        + getName() : Name
                        + getGenreId() : GenreId
                        + getItemIds() : List<ItemId>
                        + addItem(itemId : ItemId) : void
                        + isPrivate() : boolean
                        + makePublic() : void
        }
        class ListOfItemsFactory <<Factory>> {
            + createListOfItems(userId : UserId, name : Name, genreId : GenreId) : ListOfItems
        }
    }

    package "repository" {
        interface IListOfItemsRepo <<Interface>> {
        }
        interface IGenreRepo <<Interface>> {
            + getListOfOfficialGenres() : Map<GenreId, String>
        }
    }

    package "valueobject" {
        class ListOfItemsId <<ValueObject>> #LightPink {}
        class UserId <<ValueObject>> {}
        class GenreId <<ValueObject>> {}
        class ItemId <<ValueObject>> {}
        class Name <<ValueObject>> {}
    }
}

package "ddd" {
    interface IRepository<ID, T> <<Interface>> {
        +save(entity : T) : T
        +findAll() : Iterable<T>
        +findAllKeys() : List<ID>
        +ofIdentity(id : ID) : Optional<T>
        +containsOfIdentity(id : ID) : boolean
    }
    interface DomainEntity<ID> <<Interface>> {
        +identity() : ID
        +sameAs(object : Object) : boolean
    }
    interface AggregateRoot<ID> <<Interface>> {}
}

CreatePrivateListOfItemsUI "1" ..> "1" CreateListOfItemsController : invokes
CreateListOfItemsController "1" ..> "1" IGenreRepo : «use»
CreateListOfItemsController "1" ..> "1" IListOfItemsRepo : «use»
CreateListOfItemsController "1" ..> "1" ListOfItemsFactory : «use»

ListOfItemsFactory ..> ListOfItems : «create»
IListOfItemsRepo --|> IRepository
IListOfItemsRepo "1" -> "*" ListOfItems : persists

ListOfItems "1" --> "1" ListOfItemsId : has
ListOfItems "*" --> "*" ItemId : references
ListOfItems "*" --> "1" UserId : references
ListOfItems "*" --> "1" GenreId : references
ListOfItems "1" --> "1" Name : has

ListOfItems .|> AggregateRoot
AggregateRoot --|> DomainEntity

@enduml