@startuml
'https://plantuml.com/sequence-diagram
hide footbox
title US011 - to add a publication to my library.

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off


actor User
participant ":AddPublicationUI" as UI
participant ":AddPublicationOnLibraryCtl" as CTL
participant ":IItemRepo" as ITEMREPO

participant ":ILibraryRepo" as LIBREPO
participant "myLibrary:Library" as LIB

User -> UI : I want to add an Item to my library
activate UI
UI -> CTL : getListOfAvailableItemsIds()
activate CTL
CTL -> ITEMREPO : findAllKeys()
activate ITEMREPO
ITEMREPO --> CTL : itemIds
deactivate ITEMREPO

create "availableItemIds:List<ItemIds>"
CTL -->> "availableItemIds:List<ItemIds>" : <<create>>

    loop  for each itemId in itemIds
    CTL -> LIBREPO : existsInAnyLibrary = existsItemIdInAnyLibrary(itemId)
    opt !existsInAnyLibrary
    CTL -> "availableItemIds:List<ItemIds>" : add
    end
    end

CTL --> UI : availableItemIds
deactivate CTL

UI --> User : Select what item you want to add
deactivate UI
User -> UI : selectedItemId
activate UI
UI -> CTL : addItemIdToLibrary(selectedItemId, userId)
activate CTL
CTL -> LIBREPO : existsInAnyLibrary = existsItemIdInAnyLibrary(selectedItemId)

    opt !existsInAnyLibrary

        CTL -> LIBREPO : findLibraryByUserId(userId)
        activate LIBREPO
        LIBREPO --> CTL : myLibrary
        deactivate LIBREPO
        CTL -> LIB : addItemIdToLibrary(selectedItemId)
        activate LIB
        LIB --> CTL : true
        deactivate LIB

    end
CTL --> UI : true
deactivate CTL
UI --> User : Done!
deactivate UI

@enduml