@startuml
title "As a User, I want to put for sale a publication %n() in my library in a direct sale" - SD
hide footbox

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

actor User
participant ":PublicationInLibrary\nForDirectSaleUI" as UI
participant ":PublicationInLibrary\nForDirectSaleController" as Ctl
participant ":ILibraryRepo" as LibraryRepo
participant "listOfItemsId:List<ItemId>" as listOfItemsId
participant ":DirectSaleFactory" as DirectSaleFactory
participant "directSale:DirectSale" as directSale
participant ":IDirectSaleRepo" as DirectSaleRepo
participant ":IItemRepo" as itemRepo
participant "item:Item" as item

User -> UI: I want to put for direct sale\nan item in my library!
activate UI

UI -> Ctl: getItemsIdInLibraryByUserId\n(userId)
activate Ctl

Ctl -> LibraryRepo: getItemsIdInLibraryByUserId\n(userId)
activate LibraryRepo
create listOfItemsId
LibraryRepo --> listOfItemsId : <<create>>
LibraryRepo --> Ctl: listOfItemsId
deactivate LibraryRepo

Ctl --> UI: listOfItemIds
deactivate Ctl
UI --> User: Which items\nwould you like to sell?
deactivate UI

User -> UI: itemsId
activate UI

UI --> User: What is the price \nand time limit for this sale?
deactivate UI
User -> UI: price, time limit
activate UI

UI -> Ctl: putItemIdOnDirectSale\n(listOfItemsId, price, timeLimit)
activate Ctl

Ctl -> DirectSaleFactory: createDirectSale\n(listOfItemsId, price, timeLimit)
activate DirectSaleFactory
create directSale
DirectSaleFactory -->> directSale: <<create>>
DirectSaleFactory --> Ctl: directSale
deactivate DirectSaleFactory

Ctl -> DirectSaleRepo : exists = containsOfIdentity(directSale.identity())

opt !exists

loop itemId : listOfItemsId
    Ctl -> itemRepo : ofIdentity(itemId)
    activate itemRepo
    itemRepo --> Ctl : item
    deactivate itemRepo
    Ctl -> item: notOnSale = getSaleStatus()
    opt notOnSale
        Ctl -> item : markAsDirectSale()
    end
end


Ctl -> DirectSaleRepo : save(directSale)
activate DirectSaleRepo
DirectSaleRepo --> Ctl : directSale
deactivate DirectSaleRepo
end
Ctl --> UI: directSale
deactivate Ctl
UI --> User: Your item was\nsuccessfully put up on a direct sale!
deactivate UI

@enduml