@startuml
title "As a User, I want to put for sale a publication %n() in my library in a direct sale" - SD
hide footbox

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

actor User
participant ":PublicationInLibrary\nForDirectSaleUI" as UI
participant ":PublicationInLibrary\nForDirectSaleController" as Ctl
participant "libraryId:LibraryId" as libraryId
participant ":ILibraryRepo" as LibraryRepo
participant "userLibrary:Library" as Library
participant ":DirectSaleFactory" as DirectSaleFactory
participant "directSale:DirectSale" as directSale
participant ":IDirectSaleRepo" as DirectSaleRepo
participant ":IItemRepo" as itemRepo
participant "item:Item" as item

User -> UI: I want to put an item in %n() my library on direct sale.
activate UI

UI -> Ctl: getItemsIdInLibraryByUserId\n(userId)
activate Ctl

Ctl -> libraryId : fromUserId(userId)
activate libraryId
libraryId --> Ctl : libaryId
deactivate libraryId
Ctl -> LibraryRepo : ofIdentity(libaryId)
activate LibraryRepo
LibraryRepo --> Ctl: userLibary
deactivate LibraryRepo
Ctl -> Library : getItemsIdInLibrary();
activate Library
Library --> Ctl : itemIds
deactivate Library
Ctl --> UI : itemIds
UI --> User: Which item?
deactivate UI

User -> UI: item
activate UI

UI --> User: What is the price and %n()time limit for this sale?
deactivate UI
User -> UI: price, timeLimit
activate UI

UI -> Ctl: putItemIdOnDirectSale\n(itemIds, price, timeLimit)
activate Ctl

Ctl -> DirectSaleFactory: createDirectSale\n(itemIds, price, timeLimit)
activate DirectSaleFactory
create directSale
DirectSaleFactory -->> directSale: <<create>>
DirectSaleFactory --> Ctl: directSale
deactivate DirectSaleFactory
Ctl -> directSale : identity()
activate directSale
directSale --> Ctl : directSaleId
deactivate directSale
Ctl -> DirectSaleRepo : containsOfIdentity(directSaleId)
activate DirectSaleRepo
note right Ctl : Happy path
DirectSaleRepo --> Ctl : false
deactivate DirectSaleRepo
loop itemId : itemIds
    Ctl -> itemRepo : ofIdentity(itemId)
    activate itemRepo
    itemRepo --> Ctl : item
    deactivate itemRepo
    Ctl -> item: getSaleStatus()
    activate item
    item --> Ctl: NotOnSale
    Ctl -> item : markAsDirectSale()
    deactivate item
end


Ctl -> DirectSaleRepo : save(directSale)
ref over DirectSaleRepo
[[sd-ref-diagrams/Save_Item_Direct_Sale.puml Save item status as on direct sale]]
end ref
activate DirectSaleRepo
DirectSaleRepo --> Ctl : directSale
deactivate DirectSaleRepo

Ctl --> UI: directSale
deactivate Ctl
UI --> User: Your item was successfully %n()put up in a direct sale!
deactivate UI

@enduml