@startuml
title "As a User, I want to put for sale a publication %n() in my library in a direct sale" CD

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0

top to bottom direction

class PublicationInLibraryForDirectSaleUI {
}

package "controller"{
class PublicationInLibraryForDirectSaleController {
  + getItemsIdInLibraryByUserId(userId: UserId): List<ItemId>
  + putItemIdOnDirectSale(itemIds: List<ItemId>, price: Price, timeLimit: Duration): DirectSale
}
}

package "ddd"{
    interface IRepository<ID, T> <<Interface>> {
        +save(entity : T) : T
        +ofIdentity(id : ID) : Optional<T>
        +containsOfIdentity(id : ID) : boolean
    }
    interface AggregateRoot <ID >{
     }
    interface DomainEntity<ID, T> <<Interface>> {
           +identity() : ID
    }
}

package "domain"{
    package "repository"{
        interface ILibraryRepo {
        }
        interface IDirectSaleRepo{
        }
        interface IItemRepo{
        }
    }
    package "library" #b0c4d4 {
        class Library {
          + getItemsIdInLibrary(): List<ItemId>
        }
    }

    package "directsale" #b0c4d4 {
        class DirectSaleFactory {
          + createDirectSale(itemIds: List<ItemId>, price: Price, timeLimit: Duration): DirectSale
        }

        class DirectSale {
          - price: Price
          - timeLimit: Duration
        }
    }

    package "item" #b0c4d4 {
            class Item {
              + getSaleStatus(): SaleStatus
              + markAsDirectSale(): void
            }
        }

   package "valueobject"{
       class LibraryId {
        -_email : Email
        +fromUserId(userId : UserId)
       }
       class ItemId {
       - _sku : SKU
       }
       class UserId {
       - _email : Email
       }
       class EditionId {
       -_eId : String
       }
       enum Condition {
       LIKE_NEW
       GOOD
       FAIR
       POOR
       }
       class Description {
       -_description : String
       }
       enum SaleStatus {
       NotOnSale
       OnAuction
       OnDirectSale
       Sold
       }
       class Name {
       -_name : String
       }
   }
}


PublicationInLibraryForDirectSaleUI "1" ..> "1" PublicationInLibraryForDirectSaleController : invokes
PublicationInLibraryForDirectSaleController "1" --> "1" ILibraryRepo : calls
PublicationInLibraryForDirectSaleController "1" --> "1" IDirectSaleRepo : calls
PublicationInLibraryForDirectSaleController "1" --> "1" IItemRepo : calls

Library "1" --> "*" ItemId : has
Library "1" ..> "1" UserId : uses
Library "1" --> "1" LibraryId : has

IDirectSaleRepo  ..|>  IRepository
IItemRepo  ..|>  IRepository
ILibraryRepo ..|> IRepository
PublicationInLibraryForDirectSaleController "1" --> "1    " DirectSaleFactory : <<use>>
DirectSaleFactory "1" ..> "*" DirectSale : <<create>>

IDirectSaleRepo "1" --> "*" DirectSale : persists
ILibraryRepo "1" --> "*" Library : persists
IItemRepo "1" --> "*" Item : persists

Item "1" --> "1" ItemId : has
Item "1" --> "1" EditionId : has
Item "1" --> "1" Condition : has
Item "1" --> "1" Description : has
Item "1" --> "1" SaleStatus : has
Item "1" --> "1" Name : has
ItemId "1" <-- "1" DirectSale : references

AggregateRoot -|> DomainEntity
DirectSale .|> AggregateRoot
Item .|> AggregateRoot
@enduml