@startuml
title "As a User, I want to put for sale a publication %n() in my library in a direct sale" - SD
hide footbox

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

actor User
participant ":PublicationInLibrary\nForDirectSaleUI" as UI
participant ":PublicationInLibrary\nForDirectSaleController" as Ctl
participant "libraryId:LibraryId" as libraryId
participant ":ILibraryRepo" as LibraryRepo
participant "reconstructedLibrary%n():Library" as Library
participant ":DirectSaleFactory" as DirectSaleFactory
participant "directSale:DirectSale" as directSale
participant ":IDirectSaleRepo" as DirectSaleRepo
participant ":IItemRepo" as itemRepo
participant "reconstructed%n()Item:Item" as item

User -> UI: I want to put an item in %n() my library on direct sale.
activate UI

UI -> Ctl: getItemsIdInLibraryByUserId\n(userId)
activate Ctl

Ctl -> libraryId : fromUserId(userId)
activate libraryId
libraryId --> Ctl : libaryId
deactivate libraryId
Ctl -> LibraryRepo : ofIdentity(libaryId)
activate LibraryRepo
ref over LibraryRepo
[[sd-ref-diagrams/Retrieve_Library.puml Retrieve Library from persistence (via JPA)]]
end ref
LibraryRepo --> Ctl: reconstructedLibrary
deactivate LibraryRepo
Ctl -> Library : getItemsIdInLibrary();
activate Library
Library --> Ctl : itemIds
deactivate Library
Ctl --> UI : itemIds
deactivate Ctl
UI --> User: Which item?
deactivate UI

User -> UI: itemId
activate UI

UI --> User: What is the price and %n()time limit for this sale?
deactivate UI
User -> UI: price, timeLimit
activate UI

note right UI
The below method accepts List<ItemId> %n()as its first argument (for if a user wants to %n()put a **collection** of items in a direct sale) %n()%n() For the purpose of this functionality, a user%n() is only putting **one item in a direct sale**
end note
UI -> Ctl: putItemIdOnDirectSale\n(itemId, price, timeLimit)
activate Ctl

Ctl -> DirectSaleFactory: createDirectSale\n(itemId, price, timeLimit)
activate DirectSaleFactory
create directSale
DirectSaleFactory -->> directSale: <<create>>
DirectSaleFactory --> Ctl: directSale
deactivate DirectSaleFactory
Ctl -> directSale : identity()
activate directSale
directSale --> Ctl : directSaleId
deactivate directSale
Ctl -> DirectSaleRepo : containsOfIdentity(directSaleId)
activate DirectSaleRepo
ref over DirectSaleRepo
[[sd-ref-diagrams/Verify_Direct_Sale_Exists.puml Verify directSaleId is not already persisted (in JPA)]]
end ref
DirectSaleRepo --> Ctl : false
deactivate DirectSaleRepo
    Ctl -> itemRepo : ofIdentity(itemId)
    activate itemRepo
    ref over itemRepo
    [[sd-ref-diagrams/Retrieve_Item.puml Retrieve Item from persistence (via JPA)]]
    end ref
    itemRepo --> Ctl : reconstructedItem
    deactivate itemRepo
    Ctl -> item: getSaleStatus()
    activate item
    item --> Ctl: NotOnSale
    Ctl -> item : markAsDirectSale()
    deactivate item



Ctl -> DirectSaleRepo : save(directSale)
ref over DirectSaleRepo
[[sd-ref-diagrams/Save_Direct_Sale_Of_Item.puml Save direct sale of an item]]
end ref
activate DirectSaleRepo
DirectSaleRepo --> Ctl : reconstructedDirectSale
deactivate DirectSaleRepo

Ctl --> UI: reconstructedDirectSale
deactivate Ctl
UI --> User: Your item was successfully %n()put up in a direct sale!
deactivate UI

@enduml