@startuml
title "As a User, I want to put for sale a publication %n() in my library in a direct sale" CD

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0

top to bottom direction

class PublicationInLibraryForDirectSaleUI {
}

package "controller"{
class PublicationInLibraryForDirectSaleController {
  - libraryRepo: ILibraryRepo
  - directSaleRepo: IdirectSaleRepo
  + getItemsIdInLibraryByUserId(userId: UserId): List<ItemId>
  + putItemIdOnDirectSale(itemId: ItemId, price: Price, timeLimit: Period): DirectSale
  - addDirectSale(itemId: ItemId, price: Price, timeLimit: Period): DirectSale
}
}

package "ddd"{
    interface IRepository<ID, T> <<Interface>>
}

package "domain"{
    package "repository"{
        interface ILibraryRepo {
          + getItemsIdInLibraryByUserId(userId: UserId): List<ItemId>
        }
        interface IDirectSaleRepo{
        }
    }
    package "library"{
        class Library {
          - _userId: UserId
          - _itemsId: List<ItemId>
          + getItemsIdInLibrary(): List<ItemId>
        }
    }

    package "directsale"{
        class DirectSaleFactory {
          + createDirectSale(itemsId: List<ItemId>, price: Price, timeLimit: Period): DirectSale
        }

        class DirectSale {
          - itemId: ItemId
          - price: Price
          - timeLimit: Period
        }
    }

   package "valueobject"{
       class ItemId {
       - _itemId : ItemId
       }
   }
}

package "persistence"{
    package "mem"{
        class MemDirectSaleRepo{
         +save(directSale : DirectSale) : DirectSale
        }
        class MemLibraryRepo{
        }
    }
}

PublicationInLibraryForDirectSaleUI "1" ..> "1" PublicationInLibraryForDirectSaleController : invokes
PublicationInLibraryForDirectSaleController "1" ..> "1" ILibraryRepo : calls
PublicationInLibraryForDirectSaleController "1" ..> "1" IDirectSaleRepo : calls

Library "1" --> "*" ItemId : has
ILibraryRepo "1" ..|> "1" IRepository

IDirectSaleRepo "1     " ..|> "1" IRepository
PublicationInLibraryForDirectSaleController "1" --> "1    " DirectSaleFactory : <<use>>
DirectSaleFactory "1" ..> "*" DirectSale : <<create>>

MemDirectSaleRepo "1" --> "*" DirectSale : persists
MemDirectSaleRepo "1" ..|> IDirectSaleRepo
MemLibraryRepo "1" ...|> ILibraryRepo
MemLibraryRepo "1" ----> "*" Library : manages

ItemId "*" --> "1" DirectSale : references



@enduml