@startuml
'==== Title ====
title "As a User, I want to use a Web UI to put for %n()sale in an auction a publication in my library." %n() SD


'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox
autonumber


' ==== Actor and participants ====
actor "User"
participant ":Frontend" as Client
participant ":Backend" as Server
participant ":db" as DB

note over Client
  Assumes the user has already opened My Library.
  GET /my-library returned item representations
  containing the "create-auction" HATEOAS link
  pointing to /auctions.
  That resource was previously discovered and is
  used by the Frontend below.
end note

User -> Client : I want to put an item %n()in my library on auction
activate Client
Client -> Server : OPTIONS {create-auction href}
activate Server
Server -> DB: SELECT
activate DB
DB --> Server: DATA
deactivate DB
Server --> Client : 200 OK + Allow: POST, GET, OPTIONS
deactivate Server

Client -> Server :  POST {create-auction href}
activate Server
Server -> DB : INSERT
activate DB
DB --> Server :DATA
deactivate DB
Server --> Client :  201 Created + AuctionResponseDTO\n+self link + bids link
deactivate Server
Client --> User : The item was successfully %n()put on auction
deactivate Client


@enduml