@startuml
'==== Title ====
title US007 - "As an Administrator, I want to register a new country in the system" - CD
top to bottom direction

'==== basic style ====
skinparam monochrome false
skinparam shadowing true
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ArrowColor #57595BAA
skinparam classAttributeIconSize 0

'==== entities ====
Class Country {
- _countryName : String
}
Class CountryFactory {
+ createFactory(countryName : String)
}
Class CountryRepo {
- _countries : List<Country>
+ registerCountry(countryName : String) : Country
- existsCountry(country : Country) : boolean
}
Class RegisterCountryController {
+ registerCountry(countryName : String) : Country
}
Class RegisterCountryUI {}

'==== connections ====
CountryFactory "1" --> "*" Country: instantiates through
CountryRepo "1" --> "1" CountryFactory: calls
RegisterCountryController  "1" ..> "1" CountryRepo: calls
RegisterCountryUI "1" ..> "1" RegisterCountryController: invokes

@enduml
