@startuml
title As a user, I want to get a list \n of the publicly published lists of a given genre - CD

skinparam defaultFontName Futura
skinparam backgroundColor CornSilk
skinparam classBackgroundColor WhiteSmoke
skinparam classAttributeIconSize 0

class GetPublicListsByGenreUI {}

package "controller" {
    class GetPublicListsByGenreController {
        +getPublicListsByGenre(genreId: GenreId): List<ListOfItems>
    }
}

package "ddd" {
    interface IRepository<ID, T> <<Interface>>
}

package "domain" {
    package "repository" {
        interface IListOfItemsRepo <<Interface>> {
            +findAll() : Iterable<ListOfItems>
        }
        interface IGenreRepo <<Interface>> {
                    +findAllKeys() : Iterable<GenreId>
                }
    }
    package "valueobject" {
        class GenreId <<Value Object>>
    }
    package "listofitems" #b0c4d4 {
        class ListOfItems <<Root>> <<Entity>> {
            +getGenreId(): GenreId
            +isPrivate(): boolean
        }
    }
}

GetPublicListsByGenreUI "1" ..> "1" GetPublicListsByGenreController : invokes
GetPublicListsByGenreController "1" ..> "1" IListOfItemsRepo : <<use>>
GetPublicListsByGenreController "1" ..> "1" GenreId : <<use>>

IListOfItemsRepo --|> IRepository
IGenreRepo --|> IRepository

IListOfItemsRepo "1" --> "*" ListOfItems : manages
ListOfItems "1" --> "1" GenreId : has


@enduml