@startuml
title As a user, I want to get a list (name and user) of the publicly published lists of a given genre - SD
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off


actor User as U
participant "UI:GetPublicListsByGenreControllerUI" as UI
participant "Ctl:GetPublicListsByGenreController" as CTL
participant "IGenreRepo" as IGR
participant ":IListOfItemsRepo" as R
participant ":ListOfItems" as loi


U -> UI: I want to get a list (name and user) of the \npublicly published lists of a given genre
activate UI
UI -> CTL:findAllKeys()
activate CTL
CTL -> IGR:findAllKeys()
activate IGR
IGR --> CTL:genreIds
deactivate IGR

CTL --> UI:genreIds
deactivate CTL

UI --> U: Select genreId
deactivate UI

U -> UI: genreId
activate UI

UI -> CTL: getPublicListsByGenreId(GenreId)
activate CTL

CTL -> R: findAll()
activate R

R --> CTL: listOfItemsRepo
deactivate R

create " publicListOfItemsByGenreId : List <ItemId>" as List
CTL -> List: <<create>>


loop for listOfItems : allList
    CTL -> loi: publicList = isPrivate()
    CTL -> loi: genreId = getGenreId()

    opt publicList && genreId
        CTL -> List : add
        activate List
        List --> CTL : true
        deactivate List
    end
end
deactivate loi

CTL --> UI: publicListOfItemsByGenreId
deactivate CTL

UI --> U: Here's your list!
deactivate UI

@enduml