@startuml
title As a user, I want to get a list of the publicly published lists of a given genre - SD
hidefootbox

skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

actor User as U
participant "UI:GetPublicListsByGenreUI" as UI
participant "Ctl:GetPublicListsByGenreController" as CTL
participant ":IGenreRepo" as GR
participant ":IListOfItemsRepo" as R
participant "listOfItems:ListOfItems" as LOI

U -> UI: I want to get a list of the publicly \npublished lists of a given genre
activate UI

UI -> CTL: findAllKeys()
activate CTL
CTL -> GR: findAllKeys()
activate GR

ref over GR
[[sd-ref-diagrams/Find_All_genreIds.puml Find all genreIds from persistence]]
end ref

GR --> CTL: Iterable<GenreId>
deactivate GR

CTL --> UI: Iterable<GenreId>
deactivate CTL

UI --> U: Select a genre
deactivate UI

U -> UI: genreId
activate UI

UI -> CTL: getPublicListsByGenre(genreId)
activate CTL

CTL -> R: findAll()
activate R

ref over R
[[sd-ref-diagrams/Find_All_Lists_By_Genre.puml Find all lists by genre from persistence]]
end ref

R --> CTL: Iterable<ListOfItems>
deactivate R

create "publicListsByGenre:List<ListOfItems>" as List
CTL -> List: <<create>>

loop for listOfItems : allLists
    CTL -> LOI: publicList = isPrivate()
    activate LOI

    deactivate LOI

    CTL -> LOI: genreId = getGenreId()
    activate LOI

    deactivate LOI


CTL -> List: add(listOfItems)
activate List
deactivate List

end

CTL --> UI: publicListsByGenre
deactivate CTL

UI --> U: Here's your list!
deactivate UI

@enduml