@startuml
'==== Title ====
title "Verify Genre Existence" SD

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox
autonumber

' ==== Actor and participants ====
participant ":AddGenreController" as CTL
participant "newGenre:Genre" as G
participant ":IGenreRepo" as IREPO
participant ":IGenreSpringDataRepo" as SDREPO
database "DB" as DB

activate CTL
CTL -> G : identity()
activate G
G --> CTL : genreId
deactivate G

CTL -> IREPO: containsOfIdentity(genreId)
activate IREPO

IREPO -> SDREPO : existsById(genreId.toString())
activate SDREPO
SDREPO -> DB : select count
activate DB
DB --> SDREPO : false
deactivate DB
SDREPO --> IREPO : false
deactivate SDREPO

IREPO --> CTL : false
deactivate IREPO

ref over CTL
[[../Add_Genre_SD.puml Back to Main Diagram]]
end ref

@enduml