@startuml
'==== Title ====
title "As a User, I want to use a Web UI to put for %n()sale a publication in my library in a direct sale." %n() SD


'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox
autonumber


' ==== Actor and participants ====
actor "User"
participant ":Frontend" as FE
participant ":Backend" as BE
participant "db" as db



User -> FE : I want to put an item %n()in my library on direct sale
activate FE
FE -> BE : GET /items/my-library {...}
activate BE

BE -> db : FETCH
db --> BE : DATA
BE --> FE : 200 [ItemResponseDTO + links]
note right of FE
Each item includes:
- self
- create-direct-sale only if item
 can be put on direct sale
FE populates the dropdown only
with items containing create-direct-sale
end note
deactivate BE
FE --> User : Displays direct sale form %n() with items NotOnSale only
deactivate FE

User -> FE : Submit selected itemId, price, %n()currency, and time limit
activate FE
FE -> BE : POST {href from rel="create-direct-sale"}\n{ itemsId, priceValue, priceCurrency, %n()timeLimitSeconds }
activate BE
note right of BE
Creates DirectSale
and updates Item
saleStatus as
OnDirectSale
end note
BE -> db : INSERT
db --> BE : SUCCESS
BE --> FE : 201 Created
deactivate BE
FE --> User : The item was successfully %n()put on direct sale.
deactivate FE


@enduml