@startuml
'==== Title ====
title "Retrieve Library from persistence (via JPA)" Reference SD

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hidefootbox
autonumber

' ==== Actor and participants ====
participant ":ILibraryRepo" as LibraryRepo
participant ":JpaLibraryRepo" as JpaLibraryRepo
participant ":ILibrarySpringDataRepo" as SpringDataLibraryRepo
participant ":LibraryAssembler" as Assembler
database "DB" as DB


LibraryRepo -> JpaLibraryRepo : ofIdentity(libraryId)
activate LibraryRepo
activate JpaLibraryRepo

JpaLibraryRepo -> SpringDataLibraryRepo : findById(libraryId.toString())
activate SpringDataLibraryRepo
SpringDataLibraryRepo -> DB : retrieve library by id
activate DB
DB --> SpringDataLibraryRepo : libraryDataModel
deactivate DB

SpringDataLibraryRepo --> JpaLibraryRepo : libraryDataModel
deactivate SpringDataLibraryRepo

JpaLibraryRepo -> Assembler : toDomain(libraryDataModel)
activate Assembler

Assembler -> "libraryDataModel%n():LibraryDataModel": libraryIdString = getLibraryId()
activate "libraryDataModel%n():LibraryDataModel"
deactivate "libraryDataModel%n():LibraryDataModel"
create "email:Email"
Assembler -->> "email:Email" : createEmail(libraryIdString)
create "libraryId:LibraryId"
Assembler -->> "libraryId:LibraryId" : createLibraryId(email)

    Assembler -> "libraryDataModel%n():LibraryDataModel" : itemIdStrings = getItemIds()
    activate "libraryDataModel%n():LibraryDataModel"
    deactivate "libraryDataModel%n():LibraryDataModel"

    Assembler -> Assembler : itemIds = itemIdStrings.stream()%n().map(ItemId::new).toList()

    Assembler -> Factory : reconstructedLibrary = createLibrary(libraryId, itemIds)
    activate Factory
    create "reconstructedLibrary%n():Library" as ReconstructedLibrary
    Factory -> ReconstructedLibrary : <<create>>
    Factory --> Assembler : reconstructedLibrary
    deactivate Factory
Assembler --> JpaLibraryRepo : reconstructedLibrary
deactivate Assembler

JpaLibraryRepo --> LibraryRepo : reconstructedLibrary
deactivate JpaLibraryRepo

deactivate JpaLibraryRepo
deactivate LibraryRepo

ref over LibraryRepo
[[../Put_For_Sale_A_Publication_In_My_Library_For_Auction_SD.puml Return to main diagram]]
end ref

@enduml