@startuml
'https://plantuml.com/class-diagram

'==== Title ====
title MiteLovers – DDD - Granularity 1
top to bottom direction

'==== basic style ====

'hides unwanted text
hide stereotype

skinparam monochrome false

skinparam shadowing true
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ArrowColor #57595BAA

'--- undefined objects ---'
skinparam object {
  BackgroundColor<<highlight>> 91C6BCAA
  BorderColor<<highlight>> 4B9DA9AA
  FontColor<<highlight>> 547792AA
}
skinparam shadowing<<highlight>> false

'--- Objects - Aggregate Roots ---'


package User {}

package Library {}
package ListOfItems {}
package Item {}
package City {}
package Country {}
package Listing {}
package DirectSale {}
package Auction {}
package Edition {}
package PublishingCompany {}
package Publication {}
package Author {}
package PublicationType {}
package Genre {}
package AppraisalEntity {}

'=== Correlations ==='

'--- Edition ---'
Edition "*" --- "1" PublishingCompany
Edition "*" --- "1" Publication
Edition "1" --- "*" Item

'--- Item ---'
Item "*" -- "1" Library
Item "1" -------- "1" Listing
Item "*" ---- "*" ListOfItems

'--- ListOfItems ---'
ListOfItems "*" --- "1" User
ListOfItems "*" --- "1" Genre

'--- User ---'
User "*" --- "1" City
User "1" -- "1" Library
User "1" --- "*" Listing

'--- Publication ---'
Publication "*" --- "*" Author
Publication "*" --- "1" PublicationType
Publication "*" --- "1..*" Genre

'--- AppraisalEntity ---'
AppraisalEntity "*" --- "1..*" PublicationType
AppraisalEntity "*" ----- "1..*" Genre

'--- Listing ---'
Listing "1" --- "0..1" Auction
Listing "1" --- "0..1" DirectSale

'--- City ---'
City "*" --- "1" Country



@enduml