@startuml
'==== Title ====
title "Verify the existence of a Publishing Company in persistence" SD


'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
hide footbox
autonumber


' ==== Actor and participants ====
participant ":RegisterPublishing%n()CompanyCtl" as CTL
participant "publishingCompany:PublishingCompany" as PC
participant ":IPublishingCompany\nRepo" as IREPO
participant ":IPublishingCompany\nSpringDataRepo" as REPO
database "DB" as DB

activate CTL
CTL -> PC : identity()
activate PC
PC --> CTL : publishingCompanyId
deactivate PC
CTL -> IREPO: containsOfIdentity\n(publishingCompanyId)
activate IREPO
IREPO -> REPO : containsOfIdentity\n(publishingCompanyId.toString())
activate REPO
REPO -> DB : select
activate DB
DB --> REPO : false
deactivate DB
REPO --> IREPO : false
deactivate REPO
IREPO --> CTL : false
deactivate IREPO

ref over CTL
[[../Register_Publishing_Company_SD.puml Back to Main Diagram]]
end ref

'deactivate CTL

@enduml