@startuml
title OPTIONS for user on /my-library %n()ref SD

skinparam backgroundColor CornSilk
skinparam noteBackgroundColor #FFFFE0
skinparam shadowing false
skinparam defaultFontName Futura
skinparam ActivationBackgroundColor black
hidefootbox
autonumber

participant "Router" as router
participant ":LibraryRestController" as REST
participant ":UserService" as userService
participant ":IUserRepo" as userRepo
participant ":LibraryLinkProvider" as linkProvider
participant ":AuthorizationPolicy" as authorizationPolicy

[o-> router : OPTIONS {library href}\nX-User-Id: {email}
activate router

router -> REST : options(emailString)
activate REST

REST -> userService : getUserByEmail(emailString)
activate userService

create "email:Email" as Email
userService -->> Email : createEmail(emailString)

create "userId:UserId" as UserId
userService -->> UserId : createUserId(email)

userService -> userRepo : ofIdentity(userId)
activate userRepo
userRepo ->o] : FETCH
userRepo <--o] : DATA
userRepo --> userService : user
deactivate userRepo

userService --> REST : user
deactivate userService

create "options:%n()RepresentationModel<?>" as Options
REST -> Options : add self link for\nOPTIONS {library href}

REST -> linkProvider : getLinks(user)
activate linkProvider

linkProvider -> authorizationPolicy : canGetLibrary(user)
activate authorizationPolicy
authorizationPolicy --> linkProvider : true / false
deactivate authorizationPolicy

alt user can retrieve library
    linkProvider -> linkProvider : linkTo(LibraryRestController.class)\nwith rel "library"
end

linkProvider -> authorizationPolicy : canAddToLibrary(user)
activate authorizationPolicy
authorizationPolicy --> linkProvider : true / false
deactivate authorizationPolicy

alt user can add to library
    linkProvider -> linkProvider : linkTo(addItemToLibrary)\nwith rel "library-add"
end

linkProvider --> REST : List<Link> authorizedLinks
deactivate linkProvider

loop for each link in authorizedLinks
    REST -> Options : add(link)
    activate Options
    deactivate Options
end

create "response:ResponseEntity<RepresentationModel<?>>" as response
REST -->> response : build ResponseEntity\nstatus = 200 OK,\nAllow = [GET, POST, OPTIONS],\nbody = options

REST --> router : response
deactivate REST

[o<-- router : 200 OK + Allow: %n()[GET, POST, OPTIONS] + _links
deactivate router

ref over router
Process_View_Level_SD_3.puml]
end ref

@enduml