@startuml
'https://plantuml.com/class-diagram
title US016 – "As a User, I want to put for sale a publication in my library in an auction" CD

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black
skinparam classAttributeIconSize 0

'=== Classes ===
class PublicationSaleAuctionUI {
}

class PublicationSaleAuctionController {
  - _iLibraryRepo: ILibraryRepo
  - _iAuctionRepo: IAuctionRepo
  --
  + getItemsInLibraryByUser(userID: UserID): List<Item>
  + putItemOnAuction(item : Item, startPrice : Price, startDate : ZonedDateTime,
                            endDate : ZonedDateTime): Auction
}

Interface ILibraryRepo {
  - _libraries: List<Library>
  + findLibraryByUser(user: User): Library
}

class MemoLibraryRepo {
  - _libraries: List<Library>
}


class Item {
  - auction: Auction
  + setAuction(auction: Auction): void
}

Interface IAuctionRepo {
  - itemsOnAuction: List<Auction>
  + addAuction(item: Item, startPrice: Price, startDate: ZonedDateTime, endDate: ZonedDateTime): Auction
}

class MemoAuctionRepo {
-_itemsOnAuction: List<Auction>
-_auctionFactory: AuctionFactory
}

class Auction {
- itemID: ItemID
- startPrice: Price
- outrightPrice: Price
- auctionStartDate: ZonedDateTime
- auctionEndDate: ZonedDateTime
}

class AuctionFactory {
  + createAuction(item: Item, startPrice: Price, startDate: ZonedDateTime, endDate: ZonedDateTime): Auction
}

class Library {
-_items: List<Item>
}

'=== Relationships ===
' UI → Controller
PublicationSaleAuctionUI "1" ..> "1" PublicationSaleAuctionController : invokes

' Controller → Interfaces
PublicationSaleAuctionController "1" ..> "1" ILibraryRepo : uses
PublicationSaleAuctionController "1" ..> "1" IAuctionRepo : uses

' Interfaces → Repos
ILibraryRepo "1" <|.. "1" MemoLibraryRepo : relies on
IAuctionRepo "1" <|.. "1" MemoAuctionRepo : relies on

' Repos delegate creation to factories
MemoAuctionRepo "1" --> "1" AuctionFactory : uses
AuctionFactory "1" --> "*" Auction : creates

MemoLibraryRepo "1" --> "*" Library : contains
Library "1" --> "*" Item : stores

' Tem sets Auction
Item "1" --> "1" Auction : sets

note as N1
 Only US016 SD methods/attributes shown
end note

@enduml