@startuml
title "As an Administrator, I want to register a Publishing Company in the system" SD
hide footbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---
actor "Admin" as Administrator
participant ":RegisterPublishing%n()CompanyUI" as UI
participant ":RegisterPublishing%n()CompanyCtl" as CTL
participant ":PublishingCompany%n()Factory" as Factory
participant ":IPublishing%n()CompanyRepo" as Repo

' --- SD (Happy Path only)---

Administrator -> UI: I want to register %n()a publishing company.
activate UI
UI --> Administrator:Name of the %n()publishing company?
deactivate UI
Administrator -> UI: publishingCompanyName

activate UI
UI -> CTL: registerPublishingCompany%n()(publishingCompanyName)
activate CTL
CTL -> "Factory" : createPublishingCompany%n()(publishingCompanyName)
activate "Factory"
create "newPublishingCompany:%n()PublishingCompany"
"Factory" -->> "newPublishingCompany:%n()PublishingCompany": <<create>>(publishingCompanyName)
"Factory" --> CTL: newPublishingCompany
deactivate "Factory"

ref over CTL
[[sd-ref-diagrams/Verify_Publishing_Company.puml Verify the existence of newPublishingCompany in persistence]]
end ref

CTL -> Repo: save(newPublishingCompany);
activate Repo

ref over Repo
[[sd-ref-diagrams/Save_Publishing_Company.puml Save publishingCompany and return saved domain object]]
end ref

CTL <-- Repo : reconstructedPublishingCompany
deactivate "Repo"

CTL --> UI: reconstructedPublishingCompany
deactivate CTL
UI --> Administrator: Registered successfully!
deactivate UI

@enduml