@startuml
'https://plantuml.com/sequence-diagram
hide footbox
title US011 - to add a publication to my library.

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off


actor User
participant "UI1:AddPublicationUI"
participant "Ctl1:AddPublicationOnLibrary"
participant "_ir:ItemRepo"
participant "myLibrary:Library"
participant "_lr:LibraryRepo"

User -> "UI1:AddPublicationUI" : I want to add na Item to my library
activate "UI1:AddPublicationUI"
"UI1:AddPublicationUI" -> "Ctl1:AddPublicationOnLibrary" : getListOfAvailableItems(user)
activate "Ctl1:AddPublicationOnLibrary"
"Ctl1:AddPublicationOnLibrary" -> "_lr:LibraryRepo" : getMyLibrary(user)
activate "_lr:LibraryRepo"
"_lr:LibraryRepo" --> "Ctl1:AddPublicationOnLibrary" : myLibrary
deactivate "_lr:LibraryRepo"
"Ctl1:AddPublicationOnLibrary" -> "myLibrary:Library" : getAllItens()
activate "myLibrary:Library"
"myLibrary:Library" -> "myLibrary:Library" : copyList
"myLibrary:Library" --> "Ctl1:AddPublicationOnLibrary" : List<Itens>
deactivate "myLibrary:Library"
"Ctl1:AddPublicationOnLibrary" -> "_ir:ItemRepo" : getDifferentOf(existentItems)
activate "_ir:ItemRepo"
"_ir:ItemRepo" -> "_ir:ItemRepo" : copyList
"_ir:ItemRepo" --> "Ctl1:AddPublicationOnLibrary" : List<Items>
deactivate "_ir:ItemRepo"
"Ctl1:AddPublicationOnLibrary" --> "UI1:AddPublicationUI" : List<Items>
deactivate "Ctl1:AddPublicationOnLibrary"
"UI1:AddPublicationUI" --> User : Select what available items you want to add
deactivate "UI1:AddPublicationUI"
User -> "UI1:AddPublicationUI" : Selection
activate "UI1:AddPublicationUI"
"UI1:AddPublicationUI" -> "Ctl1:AddPublicationOnLibrary" : addItemToLibrary(selectedItem, user)
activate "Ctl1:AddPublicationOnLibrary"
"Ctl1:AddPublicationOnLibrary" -> "myLibrary:Library" : addItemToLibrary(selectedItem, user)
activate "myLibrary:Library"
"myLibrary:Library" -> "myLibrary:Library" : addItemToLibrary(selectedItem)
"myLibrary:Library" --> "Ctl1:AddPublicationOnLibrary" : true
deactivate "myLibrary:Library"
"Ctl1:AddPublicationOnLibrary" --> "UI1:AddPublicationUI" : true
deactivate "Ctl1:AddPublicationOnLibrary"
"UI1:AddPublicationUI" --> User : Done!
deactivate "UI1:AddPublicationUI"

@enduml