@startuml
title US027 – "As a Buyer, I want to get the list of items on direct sale of a given publisher" - SSD
hidefootbox

'==== basic style ====
skinparam monochrome false
skinparam shadowing false
skinparam defaultFontName Futura
skinparam objectFontSize 20
skinparam backgroundColor CornSilk
skinparam objectBackgroundColor WhiteSmoke
skinparam noteBackgroundColor #FFFFE0
skinparam ArrowFontColor #3B4953
skinparam ActivationBackgroundColor black

autonumber
autoactivate off

' --- Actor and participants ---
actor Buyer
participant ":Mitelovers" as System

' --- System dialog ---
Buyer -> System: I want to get a list of items on direct sale of given publishing company
activate "System"
System --> Buyer: Select publishingCompanyId
Buyer -> System: publishingCompanyId
System --> Buyer: Here's the list! Done!
deactivate "System"

@enduml